experiment: ghz_state

input_type: bitstring_list      # Options: "regex" or "bitstring_list"

system_sizes: [8]
bitstrings: ["00000000", "11111111"]
methods: [ours, qualtran, qiskit]                 
ancilla_dim: 2         # Dimension of the ancilla register

plotting: False
plot_output: figs/ghz_experiment_output.pdf