ancilla_dim: 4
experiment: batch_run/dicke_60_3_state_benchmark_only_ours
input_type: regex
methods:
- ours_efficient
- ours
plot_output: figs/batch_run.pdf
plotting: false
regex: (0)*1(0)*1(0)*1(0)*
system_sizes:
- 60
