ancilla_dim: 8
experiment: batch_run/dicke_16_6_state_benchmark_only_ours
input_type: regex
methods:
- ours_efficient
- ours
plot_output: figs/batch_run.pdf
plotting: false
regex: (0)*1(0)*1(0)*1(0)*1(0)*1(0)*1(0)*
system_sizes:
- 16
