ancilla_dim: 16
bitstrings:
- '11000101000101001110111011001110111000101000110100011110111110011001'
- '00000100011001100001100111010101001000000000001000010001100000011001'
- '10000110111011010010101110011000010001001011100100111111000000111010'
- '10000011100100111011101001101110001000010111100000000011111110110011'
- '11100001111111110011011101000100110010000011011110110010101110100101'
- '11010100100000001110011001101001000001100011000110001111111110011110'
- '10000111000101010101001000011011101000011000000101110010010101101110'
- '11011100101110001011110111010010111000101110110011011110001000101100'
- '11100000011000111110000101100001000100000001001110001111010011111000'
- '00010001111111001101010110101000100101111101001000101011001100100101'
- '01101101010101110110000111010001100100111011001001111111010001110110'
- '10011111000000000110110100111100101101110000101010111000101110101101'
- '11001001101010001110101100001110001000100001000111001110000011110111'
experiment: batch_run/rand_str_68_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
