ancilla_dim: 16
bitstrings:
- '011111000000011000101100111101111010'
- '001010001011010100011011110000011110'
- '100111010110001110101101000100001100'
- '000111100111101011011110011011111000'
- '001000100001101010110010101011001011'
- '111100110010101111111001111100111000'
- '100001110001011110111111101010001101'
- '001101111111000011101000111011011100'
- '010101010001110110110001101100100000'
- '010110111000110101101111011100100100'
- '111100100101100101011100001010101111'
experiment: batch_run/rand_str_36_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
