ancilla_dim: 64
bitstrings:
- '010111010001'
- '000011001111'
- '011110110110'
- '010111110011'
- '000101011010'
- '010110011000'
- '110101100111'
- '111101011011'
- '001000110010'
- '011101111011'
- '111101000101'
- '110000100001'
- '100011011011'
- '111010011101'
- '010111001001'
- '100011000101'
- '011101110010'
- '011110011110'
- '100010001010'
- '010010101100'
- '010011000011'
- '011101101011'
- '101111011010'
- '001100001010'
- '100010110000'
- '010001100011'
- '111000000110'
- '110001100010'
- '110000100100'
- '100100011001'
- '101100100011'
- '001100000011'
- '100111011010'
- '011101010000'
- '010111110001'
- '010010100001'
- '000001101110'
- '010011101010'
- '001111100110'
- '101011111110'
- '010010111010'
- '011011010011'
- '010100000100'
- '011011101111'
- '001001011000'
- '010010000101'
- '011011100110'
- '011100101101'
- '110111000110'
- '111011101000'
- '110000011100'
- '111011111101'
- '001111000110'
- '001101001101'
- '101101111010'
- '101101001110'
- '011010011101'
- '100010101011'
- '010010011010'
- '100010111111'
- '000111001101'
- '011110110000'
- '011101001001'
- '101001011000'
experiment: batch_run/rand_str_12_64_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
