ancilla_dim: 32
bitstrings:
- '111110111110010000111000010000011111000101111110'
- '001110001111000000000001111000000101101011001011'
- '000101000111001111101011001110111110110011001000'
- '100100001100101111001011010101100110010110110010'
- '111000110100010110011111001011100110101000110110'
- '000100010011111000000011011100101011001100100010'
- '001110011101011000100011110111100011010000001000'
- '010111011001010011010110111110010000111010001111'
- '100001011010110110001100101010100011001101100110'
- '000101111010100010111011111010101001111100011011'
- '100111110011101010000010101011010100000111101110'
- '000100101011011101011110001011101001001000100001'
- '111001000000101100101101111001010110000010000101'
- '111010001011001110001010111100111111111101100010'
- '010101101011101001110011111011010101001000011100'
- '100010100101010001011100110100010111000111001010'
- '011111011011000110100111111110001110000100110110'
- '101110011101100110110011111010111111001011001000'
- '100000111101000101111011110111100110000011010010'
- '001001001000001011101110111001011000010001001101'
- '111001001000001001010101111000010010111100100011'
experiment: batch_run/rand_str_48_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
