ancilla_dim: 16
bitstrings:
- '1110100101111101100010110001100111110110'
- '1011101011100011011110011011110000110111'
- '0001101101111010111100000000000000101100'
- '0110101100000101010101001110110001111110'
- '0000111101110011101001110100111111111010'
- '0101111001010101101101001001011100110110'
- '1100011110010010101101111011111001111101'
- '1100011000111100110010100110000011000110'
- '1100101001011011110100001100100101101111'
- '0100000111011110111110010100000110100100'
- '0111010010001001000010101110110100011010'
- '1000000000110101101110101000110110101101'
- '0000101110101111010100101010100010010101'
experiment: batch_run/rand_str_40_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
