ancilla_dim: 16
bitstrings:
- '100110100111001001110111010110000011111001101010000110010011'
- '011011001010001011110011110000000000101000101110010010110100'
- '101011110111000001011101111100110001111000011011101101011110'
- '100010000111011100100110101011010101111001100001000110111011'
- '010000100010111111111101110101001110011111110110000110000111'
- '010001011001010110100110000011101000011011110000011111010101'
- '011100011001111011100001110100111010011101000110101101101011'
- '010000010101110110101011010000011110010110011110101000010111'
- '110010101001000011010010000100001011001110111111111100110110'
- '001100111110010110010100001011111110111111101100000111100001'
- '110111000010101000010010110011010101111101111001010101100101'
experiment: batch_run/rand_str_60_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
