ancilla_dim: 8
bitstrings:
- '110001001000111001100011010111101010101110100101011111000000'
- '010100010000000110011001100010000000000010010000011110011101'
- '001011110011100011110100110011000111110000000101000011111001'
- '111010011110011110000110110010111110001111010010010110011111'
- '000111111101100010010001001001001010111110111101000101101011'
- '100000011110011100111010001000010110000110110010101001001110'
- '011100001101000000100100100010111011101001110110011100110001'
- '111100011111101000100110001100000110101011110011110101111011'
experiment: batch_run/rand_str_60_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
