ancilla_dim: 8
bitstrings:
- '0100101001110111011011100001011100010100'
- '0110001000100010011110101101010010010100'
- '0010110110000011100001001011000010100000'
- '0001100010111101010001101011000111101101'
- '0110000100100001010000000010001010010101'
experiment: batch_run/rand_str_40_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
