ancilla_dim: 8
bitstrings:
- '0100111100'
- '1101001000'
- '1011010100'
- '1101111101'
- '1010100111'
- '1010001010'
- '1100011111'
- '0111101001'
experiment: batch_run/rand_str_10_8_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
