ancilla_dim: 8
bitstrings:
- '111101010111010101111000111110011111010110111111'
- '000111000001111111010101010100011001101111100001'
- '010110001101101100110001010000001010011011111111'
- '110110000100100011010001010110100111100110011000'
- '011101100110111001011011011011010001011101011100'
- '001011000111110110001111100111101000001110101110'
- '001110011111100101000110010011000110000110010111'
experiment: batch_run/rand_str_48_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
