ancilla_dim: 64
bitstrings:
- '0110000110'
- '0000001010'
- '1000000111'
- '1010110110'
- '1101110100'
- '1110110000'
- '0010010011'
- '0000011101'
- '0001010101'
- '0011011010'
- '1110011001'
- '0001000111'
- '0011000010'
- '0110011000'
- '0100101110'
- '0110010001'
- '0010110100'
- '1001101001'
- '0100011111'
- '1111011000'
- '1011100001'
- '1010111111'
- '1000011110'
- '1000000011'
- '0010110001'
- '0111110100'
- '1110101011'
- '1111111110'
- '0101010110'
- '0111001111'
- '0000001100'
- '1111011110'
- '0101001010'
- '1101100001'
- '0101101100'
- '1010101000'
- '0101111011'
- '1110101000'
- '0100000111'
- '1110100111'
- '1000001101'
- '0111110101'
- '1010100111'
- '0011110010'
- '0100010101'
- '1000111101'
- '1110000010'
- '1000010000'
- '1101100000'
- '1001110111'
- '1011110000'
- '1011011101'
- '0101111110'
- '1010101111'
- '0110010101'
- '1001011110'
- '0111100010'
experiment: batch_run/rand_str_10_57_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
