ancilla_dim: 16
bitstrings:
- '000111100011011111000100011111010001'
- '111011110000000011000010110101101000'
- '100001011010111101100100111111011010'
- '000001101000110010000011110101011011'
- '110010011000011101110111010001111011'
- '011001010111110000100010011111111000'
- '110111011101100101010110101110010111'
- '100101111111010011011110010111010011'
- '110010101000000111011001110111001101'
- '011101011100100001011100001010111011'
- '101001001110010011111000101101000101'
- '101011101000100000011000100110111110'
experiment: batch_run/rand_str_36_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
