ancilla_dim: 4
bitstrings:
- '101011000101001010101101010010000110000100110000111111011101001101111111'
- '010100001111000111100011111001000001000100011101000010001010111011111000'
- '110100010011001000000110001011101001100010001100101000011100110001000000'
experiment: batch_run/rand_str_72_3_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
