ancilla_dim: 32
bitstrings:
- '11011110110101001001001111011110001110010000'
- '01000011100000101110010011000001111111110111'
- '00001100100110000100101100000100011111010011'
- '11100100100000000010011001111001101110100000'
- '11110111111110101110111000001100001011001001'
- '11001001101101101011111110100111001000001011'
- '01011010100110110001111000000101110010011100'
- '01001011011111101101000010100100011111001100'
- '00010010111001100100111011111110010100110010'
- '11111100001011111100111101111010101101100111'
- '00000001000001011011110100110001010001100000'
- '00111100011110101011101011110100100111001101'
- '01110110111101110000100111011110100000101001'
- '11001110100001111000001101110011101101101111'
- '10111011110110011101111000001111001100010000'
- '11000100010100000011111000010111111010101010'
- '10000101101011011111100100101010010100000100'
experiment: batch_run/rand_str_44_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
