ancilla_dim: 8
bitstrings:
- '101100011101111111100000100111000101010100110001011001101011000100111000'
- '111100101001100100101011010001101001011100110001110101011101100100001000'
- '110000000111111111010001000011101101010010011110110000000100000011001100'
- '000101101011101011100001111001111100010011110100101111110100011111010000'
- '100001011110001110001010101111101001010001100011000000001000111001111011'
- '110000000101100010100001001001011011000111010100000000011100010100110010'
- '111000001011000100111000111000011000100011110010010100111011100011011011'
experiment: batch_run/rand_str_72_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
