ancilla_dim: 16
bitstrings:
- '10110010011110110110011010110110'
- '01110000110001110000110001110000'
- '10111001111100101101111000010101'
- '11110110000001010100001001010010'
- '01111010000011100101010110001001'
- '11100100000100001111001100011010'
- '10100010101001011011110100110110'
- '01100000110001100011001000000101'
- '00100010000110111100000100111110'
- '01111011100011001101110111100111'
- '11111100000100111101101001101011'
- '00001011000111111010110010000110'
- '10001011011001010111011101010000'
- '11011111101000110011010100011101'
- '10110001011111001111010101000010'
experiment: batch_run/rand_str_32_15_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
