ancilla_dim: 4
bitstrings:
- '0111111010101111111100011000100010010111110010000011110101110001'
- '0110111100011011001000100011101110110010110011111101101001111010'
- '0101111110111111101011000101111100010000000110011000101111000001'
- '0101101011011110011001000010011100000010111100001010001011010100'
experiment: batch_run/rand_str_64_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
