ancilla_dim: 32
bitstrings:
- '0101010111101100111000101101000011001011100010010100'
- '1001000010101001100111010000000011110111100011101011'
- '0010011000000000010000001110100100101011001010111110'
- '1011100011000100111010111101001011111000100001010110'
- '1110000001010101000111011101000110110110000010011010'
- '1000010110011011101111011001100010001101110001110100'
- '1111010100111010100010010011101001011101110110101010'
- '0110010110101010001110001111011010111010010100110001'
- '1001101111101100000000010110010100101101101101011100'
- '1011010110100100001011100001110001011100011101100111'
- '0010110100100100100010011000010101011110000111000100'
- '0110000101101011001000101010100010111010101001010110'
- '0000011101100100000011101000100010001111010100101000'
- '1011001101111111000101011000111111010110011110110010'
- '0001110010011110110111101111000101010110101100111101'
- '0011001110000100100011011011011001100111010100001100'
- '0001011011001011111101010101110110000001101100100000'
- '1110000000101001100101010000101100010111011010100001'
- '0101001110110000000110010010001100011111010011101101'
- '1010100001010010000001000000101011000101010110001101'
- '1111110101010001010111110001101010110000111000011011'
- '1010101001001111011001010010100000000101100010101001'
experiment: batch_run/rand_str_52_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
