ancilla_dim: 16
bitstrings:
- '10110110100000001110111011010111010010110001001001011111010100110000'
- '00010000000010111111101001101000011101110011010011000101010100110011'
- '11100001111111000111110000100000111100101000010001110101101100101100'
- '01101000001110011100001101011000100010110100110111011100110111000001'
- '11110111111011100000001001101110001010011000110111001110101011000111'
- '01011111001001000100100110111101000100000011110110111000011000110011'
- '11010110001111110100110110111001010011011011100110001001100001000111'
- '10011111111011111111000110000011011110100111111010100011010010011101'
- '01001011101010000111011011001101010010100010001101010110111010000101'
- '11111101011010010000110001110100001011110010101101010011001110011110'
- '11110111000100010011001011111000111011011011100111000000000111011010'
- '10011111011101000001101010110000000010100101111011000100110110111011'
- '01100111000101011000011101101011010010100010101011011110101100000110'
- '00100101000001000011011111100011110011001100111010100001101101010101'
experiment: batch_run/rand_str_68_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
