ancilla_dim: 32
bitstrings:
- '11110101111100100101101111000110010010110110011111010011100010111010'
- '11110111010010001111010001110001010010101011110100100111111001000100'
- '00011010010000101010100111100110001101101110010100011100001000100001'
- '10110001010000001110001110111010011101110001011001010110011000000010'
- '10001010001111011101110011000000100111010100100011011111000101110010'
- '10011001010101100101010101000111111101010010111001010000111000000101'
- '10101111010001000100010101000010110010110000000100010110111101011111'
- '00001001110010110010011001110111101110001010101111000100111001000000'
- '11111101011110111101000000100000000110101110011100110111011111110110'
- '00100100111000000101011111000000101000000000000100010001011000111100'
- '10010101010000000000110000100110110110100010100111101110011101011101'
- '00011111100110110001111011010111000010010001100100000110000111001101'
- '10101000011110111111111011111110100101011110111111110011001011100011'
- '00100011000110111000010111101111001110100111101101111001001010001110'
- '01011110110100010010000000000111101110010010101001010011110000011001'
- '01011010110000010010111010011110100010100000011101110001100110000100'
- '10101011011001101000101010111100000111011110110011101000001001110001'
- '01111111000001101100000010110100000010000101000111100111111001011010'
- '11110000111100100001001100010110010100100011111000101000000100001001'
- '01101001011010110001101100000101100011100101110101011011000100010111'
- '00111111101111101100110010101010001000101000001011100011110000100010'
- '00101001010010001011100110000011011100001011110100010010101010010011'
- '10001011111011000011110011111100000001000000101101000100011111111001'
- '01111101010000101111000100101010110110101101010001101110011011110000'
- '01100101010111110111001100100110011001111001000010110100110111100100'
- '01001011001101000001011100110000111111101100011110100111000100000101'
- '00100101111001000000101011100101110000010110001101110111111001101011'
- '11011011100011101111011111011001010111110101001111100101111000001101'
- '01101000100100010110110100111011001110110101010001100001100000000001'
- '01110000001110000101110100010010111101011011100000011001111001010010'
- '00101000010001111110110011110001010011001111111111010111100111010001'
experiment: batch_run/rand_str_68_31_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
