ancilla_dim: 32
bitstrings:
- '10111101000110100011101100111111110011100111010000011000001111110010'
- '10010111100001101100010101100101101011100110010011110000010110101110'
- '00011000000100000010100100001001001100111000100000100001100101110010'
- '01001000000011011100111011111001001111011000001011011011001110110000'
- '10011000000000010011110011001001011010000001101101011110110011101001'
- '00010011110001010001100000000011010100110111010111101001000000010010'
- '00000110110111110001001010011000010010100001011100100110110110000110'
- '00110100111011100111000110000001000001100101110101100101111010111101'
- '00110001100101001100110101010101001101010101000010011111011111000110'
- '11001001101000101001011001101011100100101000010101011110001101101101'
- '11101110001101101011001100010100001111000111000011011000001011011011'
- '00001110110001110100000011011100000010111001011111010111000111111101'
- '10000000000101111111101100011110110011010000111110001110000110100001'
- '11111111000000101010010011001110011010000011110010010110100101010110'
- '10000011111000011001001111001000001111101001101100101001100100101111'
- '11011110110111011011100110111111111101000011110001100001100100000011'
- '11000001000011010011111010100111011011100100010000010111010001111110'
- '10000001011100110100110101000100000010010111101100100001110001000100'
- '11111101010110101110011001111011010110111101110101111111010110010100'
- '01000011111000001100110000011001110101100001010100010101101111110111'
- '11001111100011000001110011010001011110100001011001010111001001101100'
- '01110111101110010010000011101000001101111111001110001010001100010101'
experiment: batch_run/rand_str_68_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
