ancilla_dim: 32
bitstrings:
- '1110011100100001110101110010000011100111000000100111'
- '1011101010110000000100111101000010111111110010011110'
- '0001101000101111111010110010001010111000101111100000'
- '0010100001001011001010001111000100101011110011110010'
- '1010111010110001100000001111011111100010110101101001'
- '1010010001011111100100101011110010110111001011110111'
- '0110010100110010100111001001101000000001100111101101'
- '0100111100010101110010010000100001010111001110111000'
- '0001011101011100101100001001010010101011101011010110'
- '1001110100101010101100100000010011111111111100100011'
- '1101001001000000000010001001001001111111001000111100'
- '1111110110111101100000000011011000101100111101011010'
- '0100100101000000100010011010000000001001110110000100'
- '1100110101001100010000010111101101100101110000010111'
- '1010011011011111000010100001100001000100111010011001'
- '0010111010111111010011100110110011011001111011101111'
- '0111000110010111110011100001101001101111000010100100'
- '1101010001110010101001000101111010001011011111111100'
- '0001111000010101010100010111000111011101101101111111'
- '1001100100011010001100011111100011110100111011100111'
- '1000100111010010110101001001011011010100001010011001'
- '1000110111000011100110100000110000100010000100010010'
- '1000001110100011011001000001001101101101000111110011'
- '1110000000000101010100001101111110001000110100001100'
- '0110000011101110110010110111110010100110110001110001'
experiment: batch_run/rand_str_52_25_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
