ancilla_dim: 16
bitstrings:
- '110101000001001000110101100001110110101000011100010100000100'
- '100000011011011001000001010101110011101000101111100111001011'
- '001110000110000011000001001000010000111000011001011110100101'
- '001111011000010010001011111010010001100010010001101001111001'
- '110000000001101100100110100000010111001110111010011011001011'
- '111010011101101011101000111000101100111001101101000110000011'
- '100000010100011110010000110000000001011111001010011000001000'
- '101011101110011000010110000011000000010100011000111111110001'
- '011111100010111001000111111101100010101000111100011110001101'
experiment: batch_run/rand_str_60_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
