ancilla_dim: 16
bitstrings:
- '001001001111110001101000'
- '100000010000001110111010'
- '011101111100001000101011'
- '000111000110000100101110'
- '011110110001010000101110'
- '111011000000001010011010'
- '110001111001001001100011'
- '011111011001100010010000'
- '001000110010010111010110'
- '000100110011101101000100'
- '011111000101010101100010'
- '001110110011111100101110'
experiment: batch_run/rand_str_24_12_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 24
