ancilla_dim: 32
bitstrings:
- '1100011001001111110110101011011111101101111011001011'
- '0110110100101100011010000000010100010100101011011010'
- '1101110001101000010001111110111011011000010000110101'
- '1100011101011100001010000110110011000001111101101000'
- '0111000101111000110110001001101000011011100100100001'
- '1010001110010000110011111111110101000100110110011010'
- '1110001100000110001100100000011100001011010101010011'
- '1111110011011111100011111000000100001010111011000011'
- '0111110101000010100100010100001011000101001111100111'
- '1000111000111110000010110001110001001001100100000111'
- '0101000001011101111010000001001110010101100101111011'
- '1001111001110101101100011110110000011000010001011110'
- '0111101001001100100100111110101100101110101111110000'
- '1000111000111111111001000111111111000110010111101101'
- '1111111010010000010011110000001010101010010000100001'
- '0110000100001011111100000101010011010111100101010111'
- '0100100100101000011011001100110010011101000100111001'
- '0110111001110011100001010101000011011110110110011101'
- '0100101111000000011001101111110011100010100010110000'
- '1101011000011000111101100001001011101010011111010001'
- '1101001001001001100110000011111100001011110110000010'
experiment: batch_run/rand_str_52_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
