ancilla_dim: 8
bitstrings:
- '11000010101110000111000111010111'
- '00011101101010101000000000110011'
- '00001000101011100110111111101001'
- '11100000101000110001110110000001'
- '01010101001100111110111110101011'
- '10110111011011111101010100110100'
- '01011110111111010011000011111000'
- '00001000000100001000110100010101'
experiment: batch_run/rand_str_32_8_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
