ancilla_dim: 32
bitstrings:
- '10101000011001001001000001000111100010111010110000111010111101011010'
- '01110011111100101011011010101001111000001110010100010111111011100011'
- '10111100110011000000010111000010100110000010011001100011000001010010'
- '00110110001001111011001110101000011100111010110100110001001000000101'
- '10111010111111100100111100000111010110111101000001000101101110110001'
- '11111111011000110100000010111111011100011101101111101100000100001000'
- '11000001011101001001110101111010101010001100010010100010101111101000'
- '10101000010010110011011111000100001101010001011000101000010000101110'
- '00001110100001011110111011010010111010000110101001011010000000100111'
- '01111010011101111101101101100001101011001101111010101011001000011111'
- '01001001011110000110111001111111000111001110011111000111100001011000'
- '01101010000001101110101110001100001101011101011010010111101000001011'
- '00011101110101101000101000011111000000000010110000101110101010000001'
- '00001100001010101101011100011100011101111110011000110010110101011100'
- '10110101100000111110011011111000110001100000110100010111111111001111'
- '11010000101100111111001001000000001000101000011101101001010111111111'
- '10100111110010101100110100000111111001110011011010001101110100000101'
- '01111010111011111010100010100000100001000110100110000100011100010000'
- '01111100001001011100100000111001001110001100011011011110101001111000'
experiment: batch_run/rand_str_68_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
