ancilla_dim: 32
bitstrings:
- '1010111010101011001011011110101011010110100100100100011011000001'
- '0111001100001111111010011010100010110001001100101010001011001111'
- '1100010110101001101100101111011001101110101110010010010000101101'
- '1011100101110010100000110110001011011111111101101011010010010101'
- '1101000001001100000001101001111001110100100101110111000010001100'
- '0101111011001111111110101101000000101111111001010010010000110101'
- '1010110101010101110000101000000101101111101011100101100111101000'
- '0001000010001101001001010001100010000110010011000000100110000100'
- '1001011011110000010000000001101001111011011010000110011100011010'
- '0101100011100010110000010010100101110101111011111011111110111100'
- '1110110011000010111110000010010000000101010111000011001111011001'
- '1101101111001001011111111011001010101110000011100100011001000000'
- '0001100001101001001011011001010001100110110011110110010100101011'
- '0011001101010111011011110001011110000110110110110010010001000101'
- '0101011000000111101011111010101010100100010100110111010001001000'
- '1100111011111101010100001101110101100111010100101100110100010011'
- '1010011110111101111111011000001100011111100111110101100011001001'
- '1110001010110101010111110010011010001111111011111000000011010001'
- '1110101100000111011011001011110101000111001110110111110100001001'
- '1101001101110101111100000110101010000010100111010010111110111111'
- '1110001011111110100110000101010101100111000101000001010001111101'
- '1111111110000000101000101000001010100101000000101001000111111110'
- '0111001111010001110000001011111011011010000100101011001000010100'
- '0110001011100001111000110101110110101100101010101111110111010011'
- '1010011010100000001100001100000000100110110011110100000100110011'
- '1000001101110000001111011000100101111010001110110101110100110001'
- '0010010101001111010110010100010000011100001101111000110000101100'
- '0101110001010100001011001101001011001101110100111110100101100001'
experiment: batch_run/rand_str_64_28_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
