ancilla_dim: 16
bitstrings:
- '11101101110100101100010101110011'
- '10001011001011011100110011011001'
- '11010101000111111000010001000101'
- '00101110111101010010001001001100'
- '10000000101010000110001011111001'
- '10010010111100001101011101001001'
- '00100110100001001111000001101000'
- '00001111110000101001010011010001'
- '00011110000101000001101100111010'
- '01011001101101010100010101011100'
- '10111110001010101101110111011110'
- '00101100001000100110000010011101'
experiment: batch_run/rand_str_32_12_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
