ancilla_dim: 16
bitstrings:
- '010000110111101001011101110110110100000101100101110100010000'
- '010110110111110110011011000111111100100000100000000011000011'
- '111000001110010001000010110001110010011011101011001101011000'
- '101011010110100000101010011001010000000111100010101000010101'
- '001111100001000000111001111001011101010100001100010000000111'
- '110000000011000100111100110001010011111001000001010110101111'
- '000111100000000001001101011000100001000001010000001110111010'
- '111001111000100011001111110011111111011111011011100110110110'
- '010101101100001010001111110100010111011010010110100100101001'
- '101001000110100011100100101110100110000010110110010111110100'
- '000111011111000000001100101011110110000100110110011101000101'
- '110100001010000001010011001001010110101110101111011110011100'
experiment: batch_run/rand_str_60_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
