ancilla_dim: 32
bitstrings:
- '11000101001000010001010100110100001000101101'
- '01100111111101110111010110001100110101100111'
- '10000101000111011010101010100011110010011000'
- '11000010101010011000101111111111011100110111'
- '01011110111110110011111101101011001111101100'
- '10100001101010101101110010100011001010111000'
- '11100000000101010101001001000000001011100111'
- '01000000100011110001111001100111101000010010'
- '11110111111110000000001101011100101011011100'
- '01000101110001010011111100110000010111100101'
- '10101101110101111011011100011001110101100001'
- '11000110101001010100100001101101000100101010'
- '01010000011101100100101011100101000010000010'
- '11011000011101111100000110001000111001100010'
- '00001110110010001101110111100000011011101010'
- '00011111011010110100001111111011101101100110'
- '10110100000010010101011000011100001100110111'
- '01010011101011000101111000101111001101010100'
- '01111110010001010100011001100000110100100101'
experiment: batch_run/rand_str_44_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
