ancilla_dim: 32
bitstrings:
- '0010100100'
- '1101111011'
- '0000101101'
- '0000100010'
- '0111000011'
- '0011011000'
- '0101011101'
- '1101100000'
- '0101010110'
- '0000100101'
- '1000100011'
- '0110001111'
- '0010111011'
- '1101101010'
- '0001011011'
- '1110000111'
- '1011100100'
- '0111011011'
- '1010001111'
- '1001000010'
- '1101111000'
- '0000110101'
- '0000011001'
- '0001000110'
- '1000100001'
- '0011001111'
- '0010001011'
- '0010010111'
- '1100001100'
- '0110010001'
- '1111010010'
- '1101010010'
experiment: batch_run/rand_str_10_32_end
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
