ancilla_dim: 32
bitstrings:
- '011001011010001111111100010001111010010010011100'
- '011011000100111010110000011000011001101010010101'
- '100101000101001000011010110110001001011101000011'
- '010001001111010100000110110110111011010010111101'
- '000000011000111000111111111100001111001110101010'
- '010000101111011101001001101100101001111111010010'
- '101001100000101000111110111100011101111100111000'
- '100010101001101110110001101000000101110110111001'
- '100011001111101001110000000111001010101000100111'
- '010100001000010101111000000001001011010010101010'
- '100001010100100011000011101011100011101101111100'
- '000001110001001100110001100001010000111101101000'
- '001011101111110011011011100010011000011110011100'
- '011101100010011101100100001000110100001101010110'
- '000101110011011111001001101011100001011000010000'
- '011010110100100101001001101111001101010001010000'
- '000110011011010111011000001000001011101001001000'
- '110100011100100111000110101001111000010110100010'
- '101110000101100001001110111000000011110111011011'
- '101000011011111011011011111101001010101101000011'
experiment: batch_run/rand_str_48_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
