ancilla_dim: 4
bitstrings:
- '111111110110110000110101011011000001110001000101'
- '001110001011111101111011100111100000111010010101'
- '010111000001000100111101011111101011100011100101'
- '001010001010101111111011101010110011010001010111'
experiment: batch_run/rand_str_48_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
