ancilla_dim: 8
bitstrings:
- '10000111111010010100111110001001100110011110101110010010'
- '01110001101010111001101001100010110010011110111100101100'
- '11011010010111010111111001101011001110101001010011001110'
- '11011101000000000101100100001011001101011110011011101011'
- '11101001101011001110010100111011100110011011101001010000'
- '11000110011100100110111000010100000000011010111001000100'
experiment: batch_run/rand_str_56_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
