ancilla_dim: 16
bitstrings:
- '0111110000000010100110011111100000110101110110100001100010010000'
- '1001011100111010000010010101110011000110110000110100010001000011'
- '1101111110000001011000101101110010010010110001000010011110010001'
- '1011110110100010110111101101101111010000000000101010101110001100'
- '1111101111100001100110101101101011011101101011101010101001100011'
- '0011101010111010011010101110111100110111010000110010111001010110'
- '1001001000000010001101000000111110000101010010011100000110011100'
- '1110010000101100101001100011001011111011100000001110000111110011'
- '0110110010001011000000010100001001110001010010011101100111000000'
- '1100101110001110101011001110001101101010011101100100110101111110'
- '1011011111110010010001010011101001010111001110101111110101011100'
- '1001000001101011100011110010011010100010001001010011110101000101'
- '1001000010011111110101111011101100010101111010001111110111010010'
experiment: batch_run/rand_str_64_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
