ancilla_dim: 16
bitstrings:
- '0100000001000010101101000001001111010001000100100100001111011111'
- '1010101101011100010001000001111110101110110100010000010010100100'
- '1111100100000011000101101000001001011111101100001000111001100101'
- '0011000000011001001000010010110001101111111011001111000101010000'
- '0101100101011101011000101110010101101110110011100101011111110011'
- '0001010000000110000011010100001000110010010010011111110010111101'
- '0001100100011110111000111110011010110010001001000111110101100011'
- '1101100111100110101111110000000011001100100000101100111111000000'
- '1110100110000000101000011101101110101000000000000111110001011110'
- '1101001100010000011000011111011010011011100010000000101100100011'
- '0100000100010100011011001110110111101100000100110111011000010110'
- '0001111101110101001010000010011001101100010010001010111111100010'
experiment: batch_run/rand_str_64_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
