ancilla_dim: 8
bitstrings:
- '0001111010111011110010100011101111001111'
- '0011000100001110110010010100010000110010'
- '0100110100101111011100010111100011001101'
- '0111110000010010000101010111011101110100'
- '0010111011110100001010010110101100101100'
- '0100100111011110011000001001011000101101'
experiment: batch_run/rand_str_40_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
