ancilla_dim: 16
bitstrings:
- '000110101111001111110000001011010110100001001001'
- '010110000000011000000001110011111101111001110011'
- '010001011110000110010001111011001110101110110111'
- '101011100000000111010100011100011110000110011111'
- '110111111110101011011000001101010101111000000100'
- '011001010110111111101011110000100101110011010101'
- '010010011100101111000100011101100001010100000011'
- '110001110000100100100111101110101000010001010110'
- '000101011101000001001100111111110100101101100110'
- '111010000101001110110001010011111100100110000011'
- '100011100111010101001100100000001100111011100010'
- '111101011001111100111000110011000101010101101001'
- '100101101100000001110001001101000000111100111000'
- '100000100001100111011011011001100100011011110101'
- '111011001011011010010111110001010001100011110110'
experiment: batch_run/rand_str_48_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
