ancilla_dim: 8
bitstrings:
- '1000011101010010010001111110000110111111100000000100'
- '1101101100011100010010110100000101101011010011100010'
- '1101101101001000100110001111000001101100000011001101'
- '0101100010010110100111011001111000010100011011011100'
- '0001111001000100001100011011000110011011111011001100'
experiment: batch_run/rand_str_52_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
