ancilla_dim: 32
bitstrings:
- '100010000110'
- '110011000011'
- '000000101110'
- '000000111001'
- '011010001111'
- '000011011101'
- '100010100011'
- '000010110011'
- '001100100100'
- '010001100001'
- '010011111001'
- '010110000001'
- '010111010010'
- '000010001010'
- '001010100110'
- '110111010000'
- '101100110100'
- '100011100010'
- '111100100111'
- '101010010110'
- '100101011000'
- '000111000010'
- '011100001101'
- '000011011100'
- '010001110011'
- '100101010101'
- '110100001011'
- '111011000100'
- '111110000011'
- '001100111110'
experiment: batch_run/rand_str_12_30_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
