ancilla_dim: 4
bitstrings:
- '110110001100101101100101101000110011101110011001'
- '100101011100110111000111111000011110111010011101'
- '101011111100010011100101100011011001101010110100'
experiment: batch_run/rand_str_48_3_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
