ancilla_dim: 16
bitstrings:
- '1101101001111000011100100010001011011010000011101011000100111011'
- '0000100101011101001000111100111000100000001111100010111010011110'
- '1001010101011111010101011100010010101111101000110110111010111001'
- '0110000111111001011101000010111100000010010101000101011010010111'
- '1011111000010101000101011010010001000000111010101001010001011000'
- '0010110100010000101111100111001000011001100110000111001100001001'
- '1100110101001101011100111011101101011001011110001011101101000010'
- '0000011001111110101000010100011000001011100110101101001100011000'
- '1100010101011010001111011000001001000111111011011101110101010101'
- '0000001111011000100010100100011011100100100100001111010010011101'
experiment: batch_run/rand_str_64_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
