ancilla_dim: 16
bitstrings:
- '1011110110110111110111101001101101011001110010010011'
- '1000110101010100000001100001011001011011010111100011'
- '1100010101111111010101000001110000010111100110101101'
- '1010111100000110000010110100000010010001100000110100'
- '1011000100101000110100100000111110100011111001100110'
- '1110000111101001111101001100101100001110011110010010'
- '1111010100110100000001011011110110010000001101111001'
- '1100010001011100111010101010010001110100000000011000'
- '1110000010001001101000110001010101110011111011011010'
- '1111110100000100010000100000110110000010011100001110'
- '0000011011001011011100010010011011001001100111001100'
- '1101011110111001010001110001010111000001101101011111'
- '1001110101100000110011111100111011111010101101001111'
- '0011001110111000001111101010011110101101001010100110'
experiment: batch_run/rand_str_52_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
