ancilla_dim: 16
bitstrings:
- '1011110000100001011000101000'
- '0011000000101111010010010011'
- '1000010111101110010011001111'
- '0110111000110101101000111110'
- '1111010011001100100101011010'
- '0010000011110011101100000001'
- '1110110011100100000100100111'
- '0101001100011110100101000100'
- '0110010010110110100011101001'
- '0101111110100110011010101110'
- '0110111100001010001000000001'
- '0001001101110011111011111100'
experiment: batch_run/rand_str_28_12_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
