ancilla_dim: 2
bitstrings:
- '01000011010000111110101101000100110100110110'
- '00101111000010000010010010100000010101011101'
experiment: batch_run/rand_str_44_2_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
