ancilla_dim: 32
bitstrings:
- '101101110001100000101000011111010111'
- '111001110001111001001010101110101011'
- '001100111001000111111100000000111100'
- '101101010111011000110101010001100110'
- '110111000001011111010001010000110100'
- '110101000101000001110101000110011010'
- '011111001010001111110000011110000100'
- '001101111011001100010000111010001111'
- '010011111100011011101000010000101000'
- '010010110000110000110101011110010001'
- '111011010101000010110110011111100100'
- '110101011011100011111100110101011111'
- '110101011000110110001000001010010100'
- '010010101101101111001010000010011011'
- '001101110101001011100000000010011111'
- '101101100011101110110001010111011010'
- '110011010100111100000010100110101011'
- '111110010111101100001110010000000011'
experiment: batch_run/rand_str_36_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
