ancilla_dim: 16
bitstrings:
- '01100100011100001011101100010101000001111001010101000001010000101011'
- '01101100100100000111111100101101001100110001011001100001100001101000'
- '00100001110001111111011010001011000011100000010001011111110100011001'
- '01101101000010111111001001101110010010011101111001110011010100011111'
- '00111101000100101001010101001010000100110000111111110110101110111110'
- '10001000110000100101001010100110100011011101000000000010010110101000'
- '00000100101001010110010110100101111001011011100010110111110111010110'
- '00001110010010101101100110001010100110000110111100010101100011000011'
- '00100101000100101000001110010000111000111111000010101011010001011011'
- '10011101100001010100101100111100101100000001100011011000001010111001'
- '11111101010100011100010101011001010101001011001101010100110110001100'
experiment: batch_run/rand_str_68_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
