ancilla_dim: 8
bitstrings:
- '000010001001101001100110101010111011000001100110010000010100101111001111'
- '010101111100011011010011010010010001101111111011110100000110011111010010'
- '111101000010101010010100111000010100111011011001001110011100110000101100'
- '101010100100011101110111010111000000000110001000110100011101001110010100'
- '001011111000010111111110000101110011000010010100011101010111010100010110'
- '100110110100010000101001010001100111000010100010010011010001001101110000'
experiment: batch_run/rand_str_72_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
