ancilla_dim: 64
bitstrings:
- '00011000111010110001010110011101100011011101110110100101011111111001'
- '10000000110111001001111000000110110010111110101010001010101100100001'
- '11000001011000011011011110100101100011001001100001101011110011010010'
- '11101110000011011010110100101101011110100101110110100101000101100010'
- '01011000011111111011111011000010111101001110100000110101000100000101'
- '10101010110011101100011110111100011111010101110010011010010110111101'
- '01101110100111001110001100010100101010111100010001011101001110001100'
- '01110000001101101110101011100110100110111101001000101001001100110001'
- '01110110111110001111010110001110000010000010101111101100001001001000'
- '01100011100101101100000011000110010001011101001011011100100001110100'
- '10101100000110100111011010100010100100001011000010100101011101000100'
- '01010011001011010100010100001001010011110101011011010101110011000100'
- '00010110011001111001100000001100010000110001001010001100111111101001'
- '01101000011101001011111111001011010001101011101010001000110111010001'
- '00100100010010110000001101111011000010011101010010111110101010010100'
- '01011100010101111100011010011000011011110100111100110011000101011000'
- '10011011001011100100100100111011101000010000010001000110100111110111'
- '11001111111010101110011100001111100101010011010110011110001100111111'
- '10000000101110011101001100101000001010001110000110010111100111110001'
- '11000000011010101001101101000101101000111101011000101100000101010010'
- '00110111001100011011010110110100000010010000111010000101101100000111'
- '11001101000110001101010110100000111000011010101101101001101001110111'
- '11000010100010101011100010110110011111110010110111111010111000111011'
- '11011111110001001001111001001100000001010000101000100000000011100110'
- '00101001111001011111100110001010001110010000010110111111011010111010'
- '10100111001110001001010010010010111010001111010100011011001111000111'
- '11010110111010000001000000111001100000010001000000000110011001000000'
- '10011011011100100110000000001101110010010110000101110000110101001010'
- '11011110000110000000010110000101101001011001010111110100100001100011'
- '10101101001010001100111010000110111110100101010010001001101010000100'
- '00000101000001101111101000011100011011101010000110011011110010110101'
- '01000100001000011011100110010100101000000110111001101100111001000000'
- '00010011001101000100111010100010101010001111101001010010011010010101'
experiment: batch_run/rand_str_68_33_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
