ancilla_dim: 16
bitstrings:
- '100010000100110010000001'
- '110010100000111011000011'
- '110101010111011000011101'
- '010000001011101110000111'
- '100010000100110111001111'
- '010001000110001000101011'
- '010110010100011010101111'
- '111111101001010001000000'
- '100111110001111100011110'
- '001010100011001010000101'
- '100100111000010011100101'
experiment: batch_run/rand_str_24_11_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 24
