ancilla_dim: 32
bitstrings:
- '10010011100011000100100010110100100010101111'
- '01001110100101001101001100001101111100001011'
- '10000111011101101111001000000001010110001011'
- '00101110100000110101001001101000101000001011'
- '00011010110101111111110010010100001110100011'
- '01101100011110101000010101000101100010110110'
- '01100110010101110110101101011100101011101000'
- '11100100001001011000100110111111111000001010'
- '00111101010100000100000011001001010010110000'
- '01000111000011110111001101100100010101010110'
- '00000000000010111101011000000111000010111111'
- '10111111010001101001000111010111100100111100'
- '11011111110010111011101010111100101111101100'
- '11100110011010010010110110011011111011010100'
- '01011011110001101100001101010011011011011110'
- '01011001001001000110100101100111000001001000'
- '10100011111011111001111111011011110110010111'
- '01111100000101100000111000010010111011100101'
- '11010110011001011011110111100111011011001110'
- '11100010100101000011000001001000110010111011'
- '10101010001010100001111010110000000110111001'
experiment: batch_run/rand_str_44_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
