ancilla_dim: 32
bitstrings:
- '10110100001001001110110110110010100111110001011001110000101001100101'
- '10111010010100110000011011010010000110011011110011101111010000100001'
- '11101111010100111101001011001010100111010011010111011011010100000101'
- '10101000110010000010000011101100101110111101111111100100000000010111'
- '10001001010010100000110010100100110010001110110100101000001000010100'
- '00011100000010100100000111001010001011001100011000111011001010110000'
- '11000000000111011111100010000100101111000100110100100100001100001110'
- '01110110100000100011110011001010111110011011000010011101111101011010'
- '01010000101100100100001011100000100010110000100100101101110000011100'
- '00111110010110110110011001100110101110111001111110011001000110010010'
- '10110101011010110100101001000100000000001110001010111111001110000111'
- '10011000110101100010010001100001000110100100111101110011111110001000'
- '11110100111101000011010000101101100010100011100100101011001100110000'
- '10101101000110000001111101101000000100011001100101010101100101111110'
- '01111100010010010010011001110111001010110001001100010011011110110001'
- '01100010101111100101001110101110001010000000011011011100110101111111'
- '11110001111111100001110101111110011001001000000001111001001111101100'
- '00100011001101100001010110010111011011101001100101000010101100010111'
- '00001110100001110011101001000111010010000111111100011110111100101100'
- '01111010100110000110000100000001111010001011110001001000000001100010'
- '00010001001111110110111011101011110000000100111100011001010100011011'
- '00001101101111011101111100101101100011100011000111000010111010101111'
- '10000011011110000010101001001000001101100001111011110010110010000100'
- '11101101011111110101000001111010101010001100000101111111110011010011'
- '10001100011110011011101110111010110001100000100010001101100010111111'
experiment: batch_run/rand_str_68_25_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
