ancilla_dim: 16
bitstrings:
- '00101011001110001110000110111111011110110101'
- '11101001001110100100001101101110010010100110'
- '11111110000010111101001110100100111000100101'
- '00010101001011010110000001001001010101011100'
- '11100001101101101000001111101001001101110010'
- '10110001110011110000001010111011010111010000'
- '01111001110100001000011101111010100001101010'
- '00010001011100111000100010000100010100101111'
- '10011010001001100001110100100110011110011101'
experiment: batch_run/rand_str_44_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
