ancilla_dim: 32
bitstrings:
- '1010001001110010010001101010110011011011101110001001010011001100'
- '0111011010111000100111110011010011011000011011100101011010011010'
- '0110111101111001110100000010100101010100000010101001001100010001'
- '0111001111100000010001101011000101111100010010001011111101101001'
- '0000001101001001010010111000100010010011110100010110111000110101'
- '1011111010101100110110011101000110011001001001101000100000001101'
- '0100001011100001110001100010011110111101100010001000111010000110'
- '1001000011101010111110001000100111110101111011011100011110010100'
- '1001101011001011101100001110000010001101100111000100011100111000'
- '0111000000100011010001100001100111011100100101110111011001001011'
- '0000100111100011010011110011001011000011001111111111100111101010'
- '0111011111001110000110101101001110100001000000110010011111011011'
- '1011000001101011010010011001100101110001010110111110111011110010'
- '0000000000111010110000100000101001001000010111111000001100110010'
- '0001011101010011100110000101110011110001001000101011010011001100'
- '1000000111110101100101001001101000010001110101111001100100011110'
- '0111010111100001001110100100111111110110011110101000111010000111'
- '0101100101111001111110110111011111110001011111101000110100001111'
- '0111000001111101010101010111010101100110001100000010100111010001'
- '0010111000100011101001001000000110011010101000101101110001001010'
- '0100011101010011011100000001001001111101101001111110111100101101'
- '0001101011011100001110001101110111000011100010001100001010111100'
- '0000000000001101110001110111100100001001001010111101100001001100'
- '1011011101001011111001100010100000110001101101000010110000001101'
- '1101100000011000110101001011000101001011000001110011110100010110'
- '1010111111110000100111001010011111110001111011011100001011011000'
- '0100100100101010110010010110011100000111100110101010100010001000'
- '1000010000100010000101011001010000100100111110100100011111000100'
- '1010000001011010000001101110001010110000110101000000100010111010'
experiment: batch_run/rand_str_64_29_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
