ancilla_dim: 32
bitstrings:
- '011001100100110011110010010001111011011110011110100001100011'
- '000101110100010100001001101101101000110001110001101000010111'
- '100010001011000011011100001011011011010011110100101110111100'
- '010001010101000000100010110110010000110001011010110110111011'
- '010111000001010001110001100011110100011010111101011010111111'
- '011000001100111011100001110110100100101001110001010101111010'
- '010001000010001100011100111001011000110010001101111000000011'
- '101000011000101001011000110001010101000100010011110011010100'
- '011111011000000110011111111100010111010011010101010101111110'
- '000000110011100000101000101011011010000000001000101011010110'
- '010111010101010110110001110011111001100000101110101110110010'
- '100011000110000010101010000000000000000011001000010111010110'
- '000010001111010001100100010101100110001101101010000000000101'
- '101110001001111010001101101001111111001110000110001111110111'
- '100001011100110100110111000010110000110100101110001101110111'
- '101101010111110011010111110000010111001010111011111010011101'
- '010110000001111101000000011010101010101011000001111011111000'
- '001100010011111110101101111011010100001001111011000001001111'
- '001110010001111011101110101100111111100110001100100101110001'
- '111111100000010110001101010010001001111010011000001111111110'
- '111100111001011001101110111100000100100011010011001001101000'
- '000110100100110111100110100111111001100100011010000011100001'
- '001101101010101011100000111001111000110011010001001001101100'
experiment: batch_run/rand_str_60_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
