ancilla_dim: 32
bitstrings:
- '00001100011101111001110101110101011110100110110110110100111110010001'
- '11011100101011011100010100110110110010000110001111000101101110111101'
- '00100101010111101010001010000011011111000001011001110100000111000011'
- '00101000111001111010001000101111111111001010100001110010100010101101'
- '00111110101111011101001110101100001101000011000000011000110011000110'
- '00000010111100001101000101111110100000010101110101011001000011011011'
- '00111100000011111010010101011011001110111011001000000110011010110110'
- '00111010111110000111101010000000001001001111011001110110011001110010'
- '00001101010101101000011011110100100010011011011001000001100010001101'
- '11000001011101110010110011111011110101101010000010011000101010000100'
- '11001110000000111111011101001101100110111100000011100000111101110011'
- '01110111001010110100000010010100011001100111110010101000001001011110'
- '00011101110010010100100111001000100011001010010001010100101000001011'
- '11100110111110011011111010100101110011101101000010010111101111100111'
- '00010011001100110011111001100110001010000000100001011001010010110110'
- '11110100011111101000000101100010001111100100001111000010001101110111'
- '00101111100000110001011000010011111010100011010001011100011010110011'
- '10101010110000100010001010011101001000110110101111100001010111110111'
- '11000101101101000101110010001000110000000010110011001111001110100001'
- '10011000110110101111000100010000101010100000000001000110001011001101'
- '00000111010000111100001100101110000000101111001011010111001110100000'
- '00001101100000101010110000010011111101011111100010110111011000101011'
- '01010101101011010111111001011101011110111010101011001010011110011011'
- '01010001101101000001111100001010101011100011111100100101011001110110'
- '11101100101111101000001101100111100001010011010110110001100011011100'
- '01011001011101100111110110101100111011001110001110101111000111100100'
- '00010110100110011010101001000111001110101010100001000101000001101100'
- '01101011111110000101100011011101100111101000011100000110111100100111'
- '11001011101000100001110000100011101011010101110010011100000010100100'
- '01000111111101010010110011010000001001000110011110010110101100100111'
experiment: batch_run/rand_str_68_30_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
