ancilla_dim: 2
bitstrings:
- '0011001010100000110100001111'
- '1000100011011101110011000000'
experiment: batch_run/rand_str_28_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
