ancilla_dim: 32
bitstrings:
- '11011000110110001011101110000101100000010001011000101001'
- '11011101111100110101011111100010100010010000001000110011'
- '10101000001001100010000000110001000010000100110000111010'
- '10001011010001010010101110100011100101000101110011010011'
- '01110000101010111010101101101010010000010010000111111011'
- '00001000010000111101111010000101000101110101000000110000'
- '11101100010000100100001010111010110011010001010001011101'
- '01011100000100111001000001000010000100100001100010001000'
- '01010010101010011100100000010010110011011101010101111100'
- '11110101010110100101001001111101111111010001110100101100'
- '10010010101010100101101001101111000100110010101000101100'
- '00001010111010001110010000100111000111001011001101010101'
- '00011000011000100010100100100011011101001110010111100001'
- '00010101100001111010001100111110000111000100000100100010'
- '11101110001001001110000100000101101101011001000100100110'
- '00111100100011010011000100101101111101010100100010000011'
- '01111010010000001010000111000100001101000001100001011100'
- '00111011100111000011000110110111111101110110100010000000'
- '01101011110011111100100111011101010000011001001110100001'
- '00010101000001011001101000101000001010011101001110000111'
- '10110001110111010000111101001101011101010111001100100110'
- '01111110010100011010011100110010101101011100001101111000'
- '10000110100000011100110011011101111100111000011010010111'
- '11010011110001101101111111011010011000101111101000001001'
- '00111010101101000000010100101101101111111001101101111001'
- '11100011010101100111001101100011110110011100000101001100'
experiment: batch_run/rand_str_56_26_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
