ancilla_dim: 8
bitstrings:
- '011000100110101010111000111001111110'
- '000000100100111110011000010101100110'
- '110011101010100111111010010110111101'
- '001011100010001011001011110001110000'
- '110010111011100000001010000010110011'
- '011110101010100011100011001010101111'
- '110101101100011111011110100011101100'
experiment: batch_run/rand_str_36_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
