ancilla_dim: 16
bitstrings:
- '10000001100000111100100010000001110011000001'
- '10110001110001010110110001010010001011011011'
- '01011101101011011101110100100011011011001111'
- '10101101000101001011111000000010111110101101'
- '10100100111001111010010110000101111001100110'
- '11011101100101100010100110111010011010100111'
- '01000110001011000000000011101001001110100111'
- '01101010110110111111000011011110011100110111'
- '01101111010111001101101010001011000010100001'
- '11010111110110100100010100001111001011011000'
- '11101100001000011011101110000111010111110101'
- '01001111011001010110111011011110100101101101'
- '01110100110010110010100011000001111001010001'
- '11000100010101011101100101000101100110110100'
- '00101100100110010110111001101111010011000001'
- '00010110000111111110001110001010101100100101'
experiment: batch_run/rand_str_44_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
