ancilla_dim: 32
bitstrings:
- '010110101101'
- '010010110100'
- '011010011100'
- '100010001011'
- '100011011001'
- '011000110000'
- '011111001101'
- '101010111010'
- '100101110001'
- '011101111100'
- '000110111000'
- '010100010101'
- '011101111111'
- '001011011101'
- '111101010111'
- '001011110000'
- '110011001100'
- '101101011110'
- '111110111001'
- '011100011111'
- '101111101011'
- '101110011100'
- '101101000010'
experiment: batch_run/rand_str_12_23_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
