ancilla_dim: 32
bitstrings:
- '01111010000001000101000011111100011001001000'
- '10010111011111011001111100011011111110100111'
- '00011100011010100110000111101100000010111000'
- '11010000010001011110011010100111101011000010'
- '00011100111100111001100010101110110000011000'
- '11100011010110000110010101110001011010110100'
- '01011010010101000111010101110001010110110101'
- '11010100111001111001100111010101110110011110'
- '10010011000010110001000101010101101100011001'
- '00011011000100111001101110000100111110010101'
- '00100100001110111010111101100100011011101011'
- '10100001001000001011011000001101100100111110'
- '11011110011001010111110110110110010111111000'
- '00110010000110001010010011011101010100111001'
- '11010101100000000111111111110100001000111010'
- '10000001101111011110010110111111001110100101'
- '10001011110100011111111001110011111111111001'
- '11000100100001000010011010111001011011110011'
- '00000101100110000100001110101000010011100000'
- '11111011111000111000010101110100111100011100'
experiment: batch_run/rand_str_44_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
