ancilla_dim: 16
bitstrings:
- '000011010111110110011010110001101110000001000100'
- '001110101001111001111011000110010001100100110110'
- '001110101001101101001011011110110001001100101110'
- '100111110000001111100111001101100010000001111100'
- '110101000101010000011001010100100110010010011111'
- '010000011110011001110100100110100011110110011110'
- '000101001111010001101011101001001101000001011010'
- '000001110110101111110010100001000110000100100000'
- '001111010011110100001100110111010110001100100101'
experiment: batch_run/rand_str_48_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
