ancilla_dim: 32
bitstrings:
- '01000111111011110101110000111110111111010101100011010001'
- '00011011011100000001101001011001111000010110001001010100'
- '10001001000111111111011000110010100011011111110110010110'
- '11111111000111101011010111000011111101111000001101010000'
- '11100110111010001010111001110001111011010001110000101111'
- '11011011111011101111010100100011111110101111001011111111'
- '00101101110011010111010001110100110100010000111001010010'
- '01111000100010100100101000010101110000000101001111011011'
- '00011101111011101011000110100010011110001100010011110010'
- '11110011111101101111100100001000101011111001110110111100'
- '10000111010110001110101110011111111001101100011010100110'
- '11000001001010000111011000000000000011010010001001110011'
- '10000100111101101010000110010100101011100110001111110111'
- '11110111011000111101101111111100010001100011000000000100'
- '01110110101011000100111001101100001000100000111101111100'
- '01111111010010111010001011100011101111100100100000010110'
- '10111000100111011100001101110010101001001001111100010001'
- '10010010011100001100010100010110001011101000000001000101'
- '00001100111011001000111101010111000001000001100011100111'
- '01000010100000111001011101111011001100101000000000100101'
experiment: batch_run/rand_str_56_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
