ancilla_dim: 16
bitstrings:
- '0110001110011101011101000100'
- '0110100001100000110000110101'
- '0100111011010100001001111000'
- '1001000010011111101000001101'
- '0100000111100010011111010101'
- '0101110100011011101100110101'
- '1010011100101001110011100110'
- '1010001011001010000101000001'
- '1101011100010111101101000101'
- '0010101110110100110011100111'
- '1000011101101010110100001010'
- '0000110111010111101101110001'
- '0010000100101100001111110011'
- '0100110100001111001000001000'
experiment: batch_run/rand_str_28_14_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
