ancilla_dim: 16
bitstrings:
- '00110110111001001011100100110011111101010000'
- '10001100100111100100010111101100010011011001'
- '10111101010010100101000010001011111111001100'
- '10001011000100001001001110001010010001101011'
- '10011100000101110110100101110101111001011110'
- '00010101000010001001100010111011100101000101'
- '10101111100111110111111110011101110110100111'
- '01100110001010001001110011011011101011011000'
- '01000001111111100010111110001000101101111011'
- '01111101010000000110010101111001010110100011'
- '11110011010011111110111011010110101001111101'
- '00010110111100110111111111111100110110011101'
- '00011100010100001000010111101011100111000011'
experiment: batch_run/rand_str_44_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
