ancilla_dim: 32
bitstrings:
- '00100000001010000000000001000010111011110010111101100100'
- '10011111010110111111011001110000001100100001011101101111'
- '01010000001001100101010001110010101110100011010011011100'
- '01001000010001101111011000000101100100101111111011100000'
- '11001100111001001101110110111111110111010001010011001100'
- '11001101010001010110100010010011000011001111010011000001'
- '01000000110011110111100110001101001101110010101000111010'
- '10001101001010010010100111010110100011110010010110110101'
- '11111000011000001110100101000001111100111011110001111000'
- '11011100001110000000101001111010100000010101100101101000'
- '10110011110010011101011001111110111100101101000110001100'
- '11000011010111010111110101101011101001011010101101101110'
- '01100110101011010011110110110110101001100001001011111000'
- '10100000100000001110110000010001001111110001011010100011'
- '11111000110011010010000100000000110010101011010111100110'
- '11100100010001010001001110111100101100010001001001010001'
- '00110001100010100011011101100010110000001110100011010110'
- '10000101111111101111111111110000000011001011010110011110'
- '01011011001111011001101101111110000110100101011110100011'
experiment: batch_run/rand_str_56_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
