ancilla_dim: 16
bitstrings:
- '10111010010110010111011101101110000111001000110001110111'
- '00100010000110010101101111000110011111011000100100111110'
- '00001000000010110101001111011000110000101101011101001001'
- '11110111010010100101101111110110010010011110110010110100'
- '01010011110101000000111110000011111010110001011010000111'
- '11010110110101000101110100100011010001111000000111110110'
- '01001110011010011110000100001111011001010011000011011111'
- '01000001011011000001011100001000000100111001110010110111'
- '00000100001001011011011111110010111101100010110100011000'
- '00001011100011101001110110100101011100111111010101100100'
experiment: batch_run/rand_str_56_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
