ancilla_dim: 16
bitstrings:
- '10101011100110110011111001110011'
- '10000100111100001011100011110011'
- '01001011000110101011010100011110'
- '10010101011000101101011010100101'
- '01000110111111001010010110010000'
- '11001001010111100110010000001101'
- '10111110001111010011011110010110'
- '01100101001001001101101110001111'
- '00101001110001101111010000001000'
experiment: batch_run/rand_str_32_9_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
