ancilla_dim: 2
bitstrings:
- '00010010100101011110'
- '10011001011001000110'
experiment: batch_run/rand_str_20_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 20
