ancilla_dim: 8
bitstrings:
- '01110100000110000000101110011010010010100100010000101110000101011001'
- '10010101111011011100101110101100100100011101000000011111001010001100'
- '00011010110010111101000100011000001000111110101001011010100010001111'
- '10000001011111001101000000010110000011101110101000011000000000111101'
- '00000110001000100000100101010000111011010000010111010011010111010011'
- '01110100100000110101001110101011000101010010111101000000100011001001'
- '01010101100110110110010100011001010110011000101100001011110101111100'
experiment: batch_run/rand_str_68_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
