ancilla_dim: 4
bitstrings:
- '011110000111110000111110111110101000011001101011011101101001'
- '010001110010100100111111000100011001010001000010010100111010'
- '110000001111000110100000011001110111000001111000100110111110'
- '001001000100100101001010011111110000001100100010011011011101'
experiment: batch_run/rand_str_60_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
