ancilla_dim: 32
bitstrings:
- '011100011111010010111111001111111110011001100110'
- '001000101101000101000000111001011110110011111101'
- '010101000011110011111001000011011100111001101001'
- '110100011000011000000000101110011000000111010111'
- '001101001101011101101110110001110110101100000110'
- '101100111001100110000010011111010110011111011001'
- '011001110111110110001100110100100001001001011010'
- '010011101001010010010001001111111001101101000010'
- '010010010101001111010110010100010011010000101101'
- '000100011100101001111011110101110101011000101010'
- '010011101111110010010111110001101111111111100011'
- '101100011011100010100110111010010001010110111000'
- '011001011111100010011111111000011100110011001101'
- '100110000101001001100011110010011001101101111110'
- '100100000001001101101110001000010111001010010001'
- '001000011100100101110100011111111101101001101011'
- '100100100110010100010111011100001010111011011000'
- '111001110011011011010001100001000010010001111110'
- '011101110011111011100111000001010011000111110101'
- '110001101001101100101011100010000010001000110001'
- '011001101010010010010011101101100011001001001100'
- '000011001010111010011010110010011110010011001110'
- '010100110010100111100101100101000001010101001101'
- '110010101010111101101011001000001001100001000010'
experiment: batch_run/rand_str_48_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
