ancilla_dim: 8
bitstrings:
- '0001101100010011000001111100000000111001100001111100'
- '1010001000101001000111101000100111100100111100111100'
- '0010011011101100010011100010000010111110010000000100'
- '0000000101100011101100001001001111101111111011011000'
- '1110000001011100101000011101111100011011011110110100'
- '0110010011100100100100001101001100100010000100110010'
experiment: batch_run/rand_str_52_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
