ancilla_dim: 32
bitstrings:
- '0000101101011010010001001110101111100001011000100111110111111100'
- '0101111000011011001010000100011000000000101100001001000000110000'
- '1011111110000100000110101000010011111011111100001011000000010001'
- '1000101001110100101010111000000000111011110011101101100000111101'
- '1111000100100001010000001111010000100000010100101010001101110100'
- '1101100100000001110101000001011110010101001100011001100100100110'
- '1100111100011011010010000101001000101110011101101111101111100011'
- '1110011001001001000000000011000100001111001100101001101101000001'
- '0001000111000010101000101101110011100110100110101101001111110100'
- '1000011000011111000110111010100000011000100101001010000110101100'
- '0101010000001010001010000101010011100000001001001110001111010101'
- '0001010001000001101110111001011000001110100100001101011000001010'
- '0011000100110010010100101011001100001011110010011101101011110100'
- '1000001000111001100011101111000110111110101101010000101001101010'
- '1110000100010010101110111000111001000101011011001011000101101010'
- '0001111000011100100011100100100100111101000001011101101100001001'
- '0010000100011000010000000100110110011001110100001111000011111111'
- '1011000011010111001011111010000100001000001000101001101100000101'
- '1000101100110101100101111001001100001001000100100001001101110110'
- '0111101011011001110000111011001101000111111000010010011111101010'
- '1011011111011000011011101111111000100000011000010011000000001111'
experiment: batch_run/rand_str_64_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
