ancilla_dim: 8
bitstrings:
- '1101110010011100111001100011001001001100'
- '1110010011100100000111000110101001111001'
- '1001110011001011011000001000000100011010'
- '1010001001000101100001010011000011010110'
- '0101000000111111001100111111110000010100'
- '0011111010111101000001101011001010101110'
- '1110011001010101000010001111110100101110'
experiment: batch_run/rand_str_40_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
