ancilla_dim: 2
bitstrings:
- '0010110111100010101011110000111100011100'
- '1110111011100101111110010001101101101011'
experiment: batch_run/rand_str_40_2_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
