ancilla_dim: 32
bitstrings:
- '11101000'
- '10000110'
- '00011000'
- '11001000'
- '10101011'
- '00010001'
- '00101111'
- '11111001'
- '11010000'
- '01110110'
- '10110110'
- '11011100'
- '11001111'
- '00000100'
- '11110111'
- '00110001'
- '01111110'
- '11011101'
- '11010100'
- '00001010'
- '11100011'
- '10011101'
- '00101010'
experiment: batch_run/rand_str_8_23_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
