ancilla_dim: 64
bitstrings:
- '00111000'
- '10100001'
- '10100000'
- '00001101'
- '00001001'
- '11011001'
- '11000011'
- '10110110'
- '11111111'
- '10100101'
- '00100110'
- '00100101'
- '00100010'
- '01001001'
- '11111011'
- '10011011'
- '01101111'
- '10011111'
- '11001110'
- '00001100'
- '11100100'
- '01100111'
- '11110100'
- '01000100'
- '10111010'
- '11111100'
- '01100110'
- '00001000'
- '00111110'
- '01011011'
- '10001001'
- '00101110'
- '01000000'
- '10001101'
- '11101011'
- '11110110'
- '11000001'
- '01000010'
- '10001100'
experiment: batch_run/rand_str_8_39_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
