ancilla_dim: 16
bitstrings:
- '010011011100011111111101101011010011'
- '001010111100001001101001000010011010'
- '011111010000100101001111001110110011'
- '011101001111101111001001000111011111'
- '011111100100011100000100000110100011'
- '001111110000110001110110111111010000'
- '011100111001010010100010101110111111'
- '101010010001011010010011110101110111'
- '000100110000100001001001011001001100'
- '101001110100010100011001011001010110'
- '110100100111010101100101000011100110'
- '100110111011010011110110110100110010'
- '010000100101100100110010110110100011'
- '000001011101010111101101100110100000'
- '101001010100010001100101110110010111'
- '010000001111111110000010111000100000'
experiment: batch_run/rand_str_36_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
