ancilla_dim: 32
bitstrings:
- '10011001111001010000000100101111111100010011011111110000100010110100'
- '01001101011110010110001101100000000100000001111100100000111100011101'
- '01010101101101101000101101000011110111001101111000000011111010101100'
- '01011110000001001111110011110101001110110000100011101011111000101000'
- '00011001111010001101001111110101111001101101100010101010100001011011'
- '01001100001110111100100011010111110001101001010100011101110101001100'
- '11110001101111011001001110001110001100111001001101111100000010011010'
- '01011001001100011001000111010101011101000110011100001111010000101100'
- '01101001110001111100010010010111010001111111100010010000101100110010'
- '00100110010111010000101111011111100011101100110001011111001010000000'
- '01100110101101011110111110111001001101000000000011001000001101001111'
- '11001100000110100010111011011110101110000100101100010111001111011100'
- '10010101011011110000110010000101000111111001111100111011011001100100'
- '11010011011110110001011100010101000001011010010110011100101010001000'
- '01001111010111110001111001000110011111111110100110100001101110011100'
- '10100000011001101011010110000101001101001000001110000101010011000101'
- '01000100111000110100000111001011001000100111101101100100011000000001'
- '00000000100010111000101000010100011101100010011001100110111011110101'
- '11010011011010101100111110101111110000100110001110010001001010111111'
- '10100111000111101000011000000100110001010011100110011000010010011100'
- '11101101000010010111101101111010010110101100010110111000100111001101'
- '10000001111000010001001010010101001011010100001011100000001110000000'
- '11011010110001010110100100111011111011111110001000100011111111111011'
- '01100101001111001101011101100010101000001001101000010010011101010111'
- '10110100111001100111000111101011101111110001100100000110011111000111'
- '01100101000100000001100101000101000101000111001101000110000110100010'
- '00111001001001010100001101111100111000110101001000011010100010110111'
- '10001010111100110111001111001001000000100111110010101000000111111001'
- '11111001011000011101110000100011001111111111100010100101110111110110'
- '11111111010111111011101010010000001111010000111010110101000101101011'
- '00111101011000101100000001011001011000000001111111000110101111010001'
- '00110111010010100000100101001101000110001000001001010101111100001001'
experiment: batch_run/rand_str_68_32_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
