ancilla_dim: 8
bitstrings:
- '11101011111011111110111001011101100001001111001100010011011011000001'
- '11111010110010110001110011001100101000001011010110110101000011101101'
- '11100010011100011111000001010010101001011011010101110110101100100010'
- '10100110110111110110000000001111110011000100011001111001111111111000'
- '11000011001100111000100110111111111110101111000111100101001111101001'
experiment: batch_run/rand_str_68_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
