ancilla_dim: 32
bitstrings:
- '100110111100000000110100111100100100'
- '011011110001100010110010010100011101'
- '001000000001101000111001100000101000'
- '100000110111100111001000101011100010'
- '111100110111111001110001000000000011'
- '101111111011000001101010010010011110'
- '100110101101101011101010101010000111'
- '001111111001100101101101000001111111'
- '100111110000001101111010110010011011'
- '111110011101010101101011010011110110'
- '101101010010000100010011001111101101'
- '110000000000001101001101000001111100'
- '000001100010010100010100110111100100'
- '010100110100001000001100101101110011'
- '001110110100101101000111101001111110'
- '101110100010100011111001110111000111'
- '000100111100011010000111111010100100'
experiment: batch_run/rand_str_36_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
