ancilla_dim: 8
bitstrings:
- '011101000001011010010001001000100110001000110011000001011001001011000111'
- '011011001101011101000110100001111001001100000101110010010001010010011101'
- '101000010111110101100001011010010110110111111011111011001011111100100110'
- '101111100100010001101111001001010100001010101101110101000111110101001111'
- '111001000100101111100000101110010110110011111101100110111110000000001011'
- '001010000001011101001101110010111111001011011110111100010101010100110011'
- '011110101111010001110111101011000000110101110100100011001001011101111000'
- '011000001011000010101101010001010010110101000100000111010111010001100110'
experiment: batch_run/rand_str_72_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
