ancilla_dim: 64
bitstrings:
- '11110101111000111100000110001011001011001111010101100111111101010111'
- '10001111011100001100100111010101011010100011000011000100100001011000'
- '10111010110111001011000000110101001101100001111001100111101000011001'
- '01000011011001010011000010011000011110000111101111000010011001001000'
- '11111010100100100001101110100110100100101010011001011100010110111001'
- '11111000011001111001011100010011000000110001110000010110011100100100'
- '00010111101100011010101000010010001100001010000100110000110010011011'
- '10011011100011011010110010010110000001101110110101110110110010110001'
- '11100110110001100000010011110001011011101001100111001000010011001001'
- '01100100101010011110000111011000101010010010011011100001001110000110'
- '10001011111001110101010011011110100101110011000101011101011101111110'
- '01100001011000011100110010111101101100000010000001101000010010111110'
- '01100100110101010111101001100000111110101111100101010000110000000101'
- '10001101111000111011100100110100101101001111000101011010010011001010'
- '01101111000010001000001001100011000110100110000111001010011010101001'
- '11011011000011000111110011101111010011110000111011111111001001010111'
- '00000100111110000101111000101011000010110011101010110000100000000100'
- '10100011101110110010001000110101110110100101100111011101110000000101'
- '01110101011001110001110010011111110100100111011101110001011111110101'
- '00001110011011100110110100001001000101110110101100100111001001100000'
- '11100111011001001110001100100011101111010100100011011110000111101110'
- '00101100100010000110101011101101111100010100000011110010010011010101'
- '11111001111101011110111101000001000010101001001101011111001000001100'
- '01001101100110111001100111001111100000010111111000000001101111101000'
- '10001101110011000110100110100100111010110000010011101110001001011000'
- '10001100010110110010110001011101001010101011101001100000111111111011'
- '00101011000011000110001011001011010100010110111111010011101001011001'
- '01011100101011100100110100000010110110000000101011101011001001010000'
- '00010010100011011111001000000101000000000001010000000101010101100010'
- '01100010110100100001000111000010011011000100011000110101010101100101'
- '10110011000010011101000001010010100100100101101011011100110010001011'
- '00100110001110001010110101001111010100110100100011111000010101000110'
- '10011011011011100100111011101111001100011100100011111100101011101101'
- '10110000100100101001100110100101101110000000011110101110001001101101'
experiment: batch_run/rand_str_68_34_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
