ancilla_dim: 32
bitstrings:
- '0000001101001111100000111100010101111110100000000001'
- '1011101100111111100110011101100001111010101101010110'
- '0001111111011001001011010000111001011111101111110101'
- '1000110011111001010111011101111011011100000000111111'
- '1001110101000001010111110000101101110110011010000101'
- '1001011011000101111100110011100111110100001111011000'
- '0101010010101111100010101011111000011101001101000101'
- '0001111101011001010001010001011000101010011100010100'
- '1010111011000001110110100000000100011110001000110011'
- '1011110010011001101011001101110010111011001000011111'
- '1011011011000110110011110011000110100111100000001110'
- '1011111110100111111110011100100011100101000000101001'
- '1001110101110000010010101010101011001011000010000001'
- '1010100011100000101101010001011110111001111000101001'
- '0001010110001101111111001110100110101000110110010100'
- '1110110000110000110010011010011101010000001101001110'
- '0001000110101101111101001101101111010101101001100011'
- '0010111100100010111010010110000101100000100100110001'
experiment: batch_run/rand_str_52_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
