ancilla_dim: 32
bitstrings:
- '01011001101001111100100001011000110110010100100110110101'
- '11101011111110011110110101100111011100011110011101011011'
- '00010011111000110000101000100100100001111001111110000010'
- '01010101111100110111100001011010110000010011011001101111'
- '11001110100111101011000100100010111001100001111101010010'
- '00011100110011001111101010001011001001010011110010000101'
- '00100110110001000011100000100111111010111001111111011010'
- '00010100110000001110110001110011011100101000001010101011'
- '00000011101010101010111010011111110011100011010010101010'
- '01000011110001010110101101001101101011100110111011001111'
- '11010011010101000101110011101101100001100011110011000100'
- '10110100100101101010011011100000010011111011110111111000'
- '10000101000101111011100111111111011100000110011101000110'
- '10010100001001011001111001110000101110110011001010111000'
- '10001101100000100101111011100011100010101010011010110111'
- '00100100110101010110010000111001000000001100000011001000'
- '00101011011110001001010010011000100010110101110100101011'
- '10011100010000110110011001000110011010000010111000111001'
- '10101101111111000101000101000101000011111101011010101011'
- '10011100101010111111110011110110100111010101101111011100'
- '01011011011110111001011110010101010010101101110110010001'
- '00100111101000000001001100011001001110110010101011010001'
- '11111011010110100110010001011100011110001000000111011101'
- '11110000110111100100111010110000100100101000100101100111'
experiment: batch_run/rand_str_56_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
