ancilla_dim: 32
bitstrings:
- '0011000111'
- '1011001101'
- '1010001001'
- '1001011000'
- '1000101101'
- '1111001111'
- '1100111001'
- '1011001010'
- '0010011101'
- '0010111110'
- '0000010011'
- '0011001111'
- '1011011110'
- '1111100110'
- '0000011100'
- '1110101110'
- '0111100100'
- '0001001011'
- '1100000001'
- '1001000010'
- '0011110110'
- '0110000001'
- '0011101111'
- '1001011101'
- '0110110111'
- '1101001010'
- '0000011111'
- '1111111111'
experiment: batch_run/rand_str_10_28_end
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
