ancilla_dim: 32
bitstrings:
- '0001101101101010010000010011110101100001101101100000101011111101'
- '0111001011111011000101110100000001110011011001001001001001010011'
- '0011110011001101111101011000100110101101001011110100011111101100'
- '1010101011001011000011100010110111100101100000010000010101100011'
- '0101001001100101111110110011011111110100111000011001011010101000'
- '1101001100010000110000000011111001010100001011110010011001111000'
- '1011111100000111110111111001100000111001000101111101010101100010'
- '1100000001001100100011100000101011100001011111111011010000110010'
- '0100001100111100000101010110001010000001110000010101011001101011'
- '0100100010001011000000101011111001001001000100000010011111110100'
- '1000100000100100011010011010101100011101011001000100001010001110'
- '0110111110110011011101000011101100001010000101111001001010000101'
- '1111100101010000010010011011011100111000100000111100110110000101'
- '1100101111111001000000111110100111101110010100001100100111110101'
- '1110001110010011011001111101100111011100111101001001011110010011'
- '0001101000110010110110010010111100100011111001101100011111111110'
- '1100101001100000100111011011110101010100001111011011011010001110'
- '1011111100011000100111011011000011101001011111001101000011110100'
- '0100100111101101101011100001001001010100111100001000001101100101'
- '0010100000010111101111000110110001100011011011110100010100111011'
- '0000001000001110100100010100111100011110011010010010011011110000'
- '0110010110000100010001110001010011011101100111101000111100011011'
- '0110001011110100100111110001111010111010110101110100100100111011'
- '0001111101100010110101000000000100100101111101110001010001110111'
- '1110010001000111101101111101000111000011001100000001000100111011'
- '1001101001011010000011101110001101011110110101001100000010110101'
- '1011011001001001011010001110111001010110000000011010110010100010'
experiment: batch_run/rand_str_64_27_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
