ancilla_dim: 8
bitstrings:
- '10101110001011011000011110100101101101010010011110110010000110011000'
- '00010101011000100101010010100111011100101101001001011100010010110001'
- '01010110001101110000111100111010010110001000001010111101010100100101'
- '00100001101110110001001101011101010110000011001010011111001100011110'
- '01001000101111000000100111101010100110010001111110000000001111000010'
- '11110001000010100100111101000101101111110110000101010101101000010010'
experiment: batch_run/rand_str_68_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
