ancilla_dim: 16
bitstrings:
- '1000100010'
- '1011011110'
- '1000100100'
- '1011000100'
- '0110010000'
- '1001100101'
- '1111111111'
- '1111100010'
- '1001111010'
experiment: batch_run/rand_str_10_9_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
