ancilla_dim: 2
bitstrings:
- '01100001001001101001001100011001110001010000111110110000101101000111'
- '00011111110000010111101001111111111011110010011011011110000101011000'
experiment: batch_run/rand_str_68_2_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
