ancilla_dim: 16
bitstrings:
- '101001000011111110111100010000001101100010100101'
- '011010001011101111001000111110101010011111101010'
- '001001011001110011101000100101000100000100011010'
- '110111111111011111110011000000100110111101110001'
- '010101111100010001000010111110101111010110001011'
- '101110111111001001110010100000111001010111101001'
- '100110110000000000101001100011010011111000111011'
- '010111011010000100000001010101001011110011000111'
- '101100111000111111001011100111100010011011001000'
- '100111111010110011011101110100010000011011010001'
- '110000101101100100000100110000000010110000110011'
- '010101110110100001101000001110010111100111010101'
- '001110111000000100010101101101001100000011001001'
- '111100110101111100010111001001001001110000010001'
experiment: batch_run/rand_str_48_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
