ancilla_dim: 16
bitstrings:
- '01001011001101001100101010100101010010011100111001100000'
- '00100000101101110001100001101000001001111000110000001110'
- '10101001011110000001100000101101101011000100100000011010'
- '11001001110110101010001010110100100000000101010111011000'
- '00110010110000011011110100101001101110011011111000010010'
- '00010000111010101111000100011010010001110000010001001101'
- '01011000000011110001010111101111000101010000011101111110'
- '00101010000110011110110101010001100100110010000100011000'
- '10011000111000000110011001111000000011010010100101111100'
- '01111010100111101101011010001010011101100000110010100010'
- '00100010011000100010001011000000010011010000000011110111'
- '01101100101010010011001000001011100001101100111100101100'
- '10110000111011010110100000011101011100000001010101100101'
- '00000101000100011000011010111111100110111111010011011111'
- '10001110111001110110000010000111010000000010110000000001'
- '01100001111100011110110001100110011101010110000100000111'
experiment: batch_run/rand_str_56_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
