ancilla_dim: 8
bitstrings:
- '11000110010001000100101000010000000110111111110111111111'
- '11101100010001100011100110001100111001101110111011100110'
- '10110111001000011101111010001000101001011100011110101100'
- '10011001000011100000001000110100001000010110001010110010'
- '11111011111111100010100011111010001001100011000011011110'
experiment: batch_run/rand_str_56_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
