ancilla_dim: 16
bitstrings:
- '001100010010100110010001100011100110001100110100100010110101110001100100'
- '101011011100010100100000101010001001010010100000111101100101110011110101'
- '000011100001110101011111010010010111010000000010100101110110101011110101'
- '011000100111101101001001011001111010111101110111101000011100011000110000'
- '011001101101000011110101000011100100011010011111110110101110100111000111'
- '001111101001110101011000001111011010001111010111001001000110001000111011'
- '100000100110010111010001111101110010000011110001010101101010001111111000'
- '011000101000110001001110011011000100101001010110100100010101000111000001'
- '011110100000100010111001110100110100110011101011010001000101101111000001'
- '111010001010101111110000001110001000001111010100100100001010111100001100'
- '111110110111011111010110100001110000011110011101011011001000011000001001'
- '010010011011101110110111110000100010000101101000101111011111000100000000'
- '000111011010000010111010001011100110010100100110001101011111100010100101'
experiment: batch_run/rand_str_72_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
