ancilla_dim: 16
bitstrings:
- '1001100111000010111001001011111101100001'
- '0010000111011101110110010000111101000001'
- '1111111110101100101001010101101010001001'
- '1001111000110001001001101100101111001001'
- '1001101111001110111100110111110111111111'
- '0100101111011100001101010010001100100000'
- '0110100000110101100111001011010100101001'
- '1110010110111000110111001101010110011010'
- '0101011011100011010000100110111011011110'
- '1000111110100100011010001101001001101101'
experiment: batch_run/rand_str_40_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
