ancilla_dim: 32
bitstrings:
- '00000101101010100000000001101010011001100011011110010000'
- '00111111100101110110101000000000001010010000010010110001'
- '11111001111011001111110101001101001100101000010010011001'
- '01001000100001110010110100101101011010111100100100100100'
- '00100110011001010100110101110010100100011110001100001111'
- '00001011000100010100000111111100110101010110100000000100'
- '10101110010000001111000001011111100000000011011010101010'
- '01001000010001000100010101100011001000101011110000111000'
- '10101001010001010001000101100111001101100110111000011001'
- '11000001111001111011010011110011011111110101100011110001'
- '00010001111010111001111101010110011111010001101101000000'
- '11011011110110111001001101011110100001111110001000001100'
- '10011011010110011100010011000100011010010101110001101001'
- '11011011111101100011000010011101101010101000001010000001'
- '00111001000010110111000010011011100011010010011010111000'
- '10101110110111100100101101101101101110000110111101110111'
- '10010000110011111101101000111111010011110001111110000010'
- '11111101000101010110001111110010101010000101001000000100'
- '11001011011111110000110001101100100001111000101000110011'
- '01111010000000010010000011000111001111101100001011011011'
- '10110100011101000100011011001001001111010101010111111010'
experiment: batch_run/rand_str_56_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
