ancilla_dim: 16
bitstrings:
- '00100001101001001110110101010001001011011110001100111101'
- '00001111000100111001011111001010110011100011101000100100'
- '01001010100110110101101100101100010011010101100101111010'
- '00111011000100011010111110110101001011001101010101001110'
- '01011000110010010001111011000100111110100011100100111100'
- '00101100000101000110111000111101010010010001110010101110'
- '00011100001000001101000000011111000011110111010111101111'
- '01011010001000111001010100110010110011110110011111100110'
- '10101001101000011110011011011110101101011100101001110011'
- '11111100110110110110111110010000011100011001001101111100'
- '10001101000011011011001000100111001111101110000001110101'
experiment: batch_run/rand_str_56_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
