ancilla_dim: 4
bitstrings:
- '0000101011101010110000110011100101011000111010000001'
- '1111111001101111110100100000100100110001110001101011'
- '1000000001001011010101001011000100110111101100001011'
- '1101101011111001001000011000000000011100101110100011'
experiment: batch_run/rand_str_52_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
