ancilla_dim: 4
bitstrings:
- '111011011010'
- '111101100111'
- '100011111000'
experiment: batch_run/rand_str_12_3_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
