ancilla_dim: 32
bitstrings:
- '10001101010010100001101110000111001101011111100101010110'
- '01000100100100000010011000101010111000001001100110100101'
- '11111100101101101111100100011011000011110011010011000000'
- '01101111001101101111110100110011110011011110001111011010'
- '00001000100100011111001011101010000001010110000000111110'
- '01111111010101000110011111011111111111100010101010110001'
- '10001111101011101010100010000110110111101100111110011111'
- '00010000101100100110011010001110110010000100101110010111'
- '11000001100111000010001010001000100110011100111001001111'
- '00111100000101011000010011100000110111110100101010111100'
- '10101101000110011000010011001110110011001111001110010000'
- '00111011100000111001010101010100000010011011000001111010'
- '01101100111100101111001011000010011011110001111110000100'
- '11011101010010110010000011110001100000110101010000111010'
- '11100010001110110001000100001010111011011001110010011110'
- '00010100001110101011011001110110111110010011110010001001'
- '01100110000111101110010000100001101001001110000111110101'
- '00110010100010100010110111111001000111000100101110101010'
- '11101011110011111101101000010010110010000111111100100110'
- '01100101101101000101111100111111110011011010101011000110'
- '00111111110100001100101001110100001001000101111010011010'
- '00010010101100011100100000010000100101111001110101101100'
- '10000010111011100101001101101111001000010011000100101000'
- '01110011010010000001100000001101110111011111001001111010'
- '10111111100011101010000001100010101000000100101001101001'
- '10101100011000100001100100111111100100101011000100010100'
- '01111111101001000000100010000010010001010111100101110101'
experiment: batch_run/rand_str_56_27_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
