ancilla_dim: 4
bitstrings:
- '01110001101110000110000111110111100010010000111001011001'
- '00000001110001010111010101100110110000110111011110101100'
- '11001110100010011100010000000011000010101110100000100011'
- '01010000011111111010100001101111110011111110100000011000'
experiment: batch_run/rand_str_56_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
