ancilla_dim: 32
bitstrings:
- '0000000110000101000000001101001100100101110111011001001001011010'
- '0010000001110010010111110100110000110101010000011001000001011011'
- '1010000111111000111110100000010100010110111010110110000010001101'
- '0110011110101010000101101000011100111011101001000110100110100100'
- '1111001100000101011000111011110110100111010010000000011101101111'
- '0101101101101111101110111000011001001110110000011100100001111111'
- '1011101110001101001101110111000110111010010010111101101000100100'
- '1000001001110011100111011000100011001101110101000010001000111110'
- '1101011111110011100000111110101111111011010111110001111100001010'
- '0001001001100100100001111001110110011111001011100111001110011011'
- '0001101100010111100010111011111101101001000001110101101110110100'
- '0001100110100111001000011111101110000111001001010101101110100000'
- '0011011001100001011010011111101000101101000100111011101000101100'
- '1110011011011011101000011001000101011110110010010001011100010110'
- '0000001100111011110000000000011011100101101110000010001111100011'
- '0111011001011100101100001110111010011010110111010010111111010100'
- '1000010100100110000011011101110101110000111111011110010010011111'
- '0001010111111100110111111101110000100100111001000110110001100100'
- '1100011001000011001101101010111000011011010111010010111100000100'
- '0111010001000110001010010100001011000110010110000001011100000001'
- '1101111110101010001000000001000011010100010000001001101100001011'
- '1010110011010000000110111110011110000100000101001111101100110000'
- '1101110011010011001000001111110110111111001000111100100011001011'
experiment: batch_run/rand_str_64_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
