ancilla_dim: 32
bitstrings:
- '1101010011100101110000001110111111111010100100011011111010100101'
- '0101111111000011000011001001111100011000000100101101101000011111'
- '0000001011101110110001110110010111011101100001010100001111010110'
- '1100110111011111110101011000001010010110111101010010110111111000'
- '1101111110110000000101010011001110010000100000010110000001001110'
- '0011111110001001010101111000010110000011110001100010100111010000'
- '0000010011011011001111111001010001001010110010100011011011111111'
- '0010010111000110100100110111011001100111110110111000010011011111'
- '0101100000110001110000011111101111110101100001101111111011011111'
- '0111101010011001110000101010111100101110001110010011001000001111'
- '1111111001011100010001010110011000001000111001010111101011100011'
- '0010001100000101000100110011110101100010100111000110100010000010'
- '0000101101001001110011001101011111100011011100000000110100110111'
- '1000010010011010001111001001000001000011111010011101000110010100'
- '0011001111100111011011001011101001011110100100001011011010110101'
- '0000011011001010101111100011101001000111111011011110101111000010'
- '1111011100101010110000010001110100010110100100100100110001010100'
- '1001111111001000000001001100100000010000011110110100111110101111'
- '1000000100000110111100101000011000111000011011000100111000111100'
experiment: batch_run/rand_str_64_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
