ancilla_dim: 128
bitstrings:
- '1101111110'
- '0111001100'
- '0011101001'
- '0001110111'
- '0001001010'
- '0011001011'
- '0011001100'
- '1100100101'
- '0001010100'
- '1110000011'
- '1001001001'
- '1110000101'
- '1011001011'
- '0110110101'
- '1010101011'
- '1100100100'
- '0001110110'
- '0011001101'
- '1100011011'
- '0010001100'
- '0111011011'
- '0101100100'
- '0101100110'
- '1101101101'
- '0000001100'
- '1001001111'
- '0010101010'
- '1010111101'
- '1101010000'
- '1110000010'
- '0010011110'
- '1101111010'
- '0000110001'
- '1110100110'
- '0111110110'
- '1010101100'
- '1000110001'
- '1001111110'
- '1000100001'
- '0000100110'
- '1000000111'
- '0101100000'
- '1100010100'
- '1000110010'
- '0111110111'
- '0010110100'
- '1001011100'
- '1110100100'
- '0111000110'
- '1010101101'
- '0011111001'
- '0101000011'
- '0010111111'
- '0001010111'
- '1100011001'
- '1000111001'
- '0001100001'
- '1111101000'
- '1011010010'
- '1011011001'
- '1011100101'
- '0100101011'
- '0000101000'
- '1100101000'
- '1000010100'
- '0101000111'
- '0101000001'
- '0111100111'
- '1011011111'
- '1010011000'
- '1011000010'
- '1010110100'
experiment: batch_run/rand_str_10_72_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
