ancilla_dim: 32
bitstrings:
- '0001110101000000010001100101001000110000'
- '1100100010100110010011111000101000100111'
- '1010011111001100100011101110101001111110'
- '0011010100011001111001001001101011111011'
- '0111100001110100011101000011101111000110'
- '0000000011100101011011111001010100001010'
- '0000000010111101011111000100011000001100'
- '1100111110101001001000110111100010011001'
- '0101100101101110000011110000100110110001'
- '0010011001111000011101100110110011000000'
- '0001010110110111110110101001110111111001'
- '0001000011100101111110100110001101110100'
- '1011000010010110110110110010011111101100'
- '1110100000101011100010110111010101011101'
- '1001001100110111100001000100100111010000'
- '1001001000010111101000101011011001010111'
- '0001010011011100100110110001001001010110'
- '1100101110001100000111000110110011011011'
- '0100011110011011100011111010000001000111'
- '1111111101101110110100100000010001001110'
experiment: batch_run/rand_str_40_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
