ancilla_dim: 8
bitstrings:
- '001010101011010001100110000010000011'
- '000011110110111010101101010000110000'
- '000100110111101111001100000010010000'
- '110100100111001111001000100110101001'
- '101010010110101000010001101011001011'
- '100000100011001010011110101000010111'
- '010011000010010100001000111000011110'
- '010110011111001000011011101000010010'
experiment: batch_run/rand_str_36_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
