ancilla_dim: 8
bitstrings:
- '010100001001110001100111111000001110001000111001000110110011'
- '010101001101001001000111111000111100111100011010111110011001'
- '111011111101010110001100110001000100011101010011110100001010'
- '111101000110110111111000100001111100110000111101110000101111'
- '001010001000011111000110001100010010010000111101001001010011'
- '010101010001000001011011100101110011100100011110000101100010'
experiment: batch_run/rand_str_60_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
