ancilla_dim: 16
bitstrings:
- '00011000'
- '11111011'
- '01010000'
- '01001101'
- '10010100'
- '11000011'
- '01110011'
- '01000011'
- '00111111'
- '10000111'
- '00100001'
experiment: batch_run/rand_str_8_11_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
