ancilla_dim: 8
bitstrings:
- '0111100111'
- '1001111101'
- '1101011111'
- '1111111011'
- '1001011101'
- '1001101111'
- '0100111001'
experiment: batch_run/rand_str_10_7_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
