ancilla_dim: 2
bitstrings:
- '111011011111000011111111011100010000'
- '001111000010000101011001010101101110'
experiment: batch_run/rand_str_36_2_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
