ancilla_dim: 16
bitstrings:
- '0100010110101111010000101110110101100110011100011001100100000100'
- '1011101101001011001111110010000010011011011100110101111011101011'
- '0111100001101001011111111000110011010011101101111111001011010001'
- '1100100011101101111111101101011100101011000011000011111000100010'
- '0011100000000101111111111100100110101111001010001000100011011000'
- '1110000111101101011011001010111110000000101010000101010001010000'
- '0111110010110111011000000101111110110111110101110011010011110101'
- '0101001011001000000111110001010001000000110101000111111011111110'
- '1010110111110110010111010110101100001111000110110111110001010001'
- '1000100101100110001001100001110110011000001110010110010100011100'
- '1010111110101101110100000100100100100101010000001000111010010011'
experiment: batch_run/rand_str_64_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
