ancilla_dim: 16
bitstrings:
- '0101111001001010101111010110110000010011010110101001'
- '0000010101111111111101111110010001111110110101110001'
- '1111011110010001110100011011111001100110101110100011'
- '0110100110100011101110110110110100011010101100010010'
- '0001110110111110110100110010101011000100110011100011'
- '0010001101110011111000111111111001110100000010111111'
- '1101110001101111100000010010111011111100011001101101'
- '0100010101010011001101100011000011101010110010001011'
- '0100100111001110011111110111010110110110110000011010'
- '1011001010011111101011010110011011001100100000000110'
- '1001100110111111000010000110010101101000111011001101'
- '0100110111110001010100101110111001000111010111001001'
experiment: batch_run/rand_str_52_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
