ancilla_dim: 8
bitstrings:
- '011100010000'
- '100011011100'
- '010001110101'
- '011010010100'
- '011001000011'
experiment: batch_run/rand_str_12_5_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
