ancilla_dim: 32
bitstrings:
- '010001010110100110010111100001010001111001110010111100011011'
- '111001110111100101010011000101111011011011100110101001001110'
- '010110111001111000000011000000010010101000101100100011010100'
- '111000001011000110010011101010000101100001010110101000011001'
- '101011011111000000101100101001101001000010000010011100110101'
- '010110110110100010111011010010111111001011110001101000001001'
- '011100010001010001001000011111111100000010010100000000010001'
- '111010101010111101001001111100100010100001100110111010010000'
- '111000000011001100010001000100011011101000011100010011010110'
- '001100100100010011000110100100101010101011100111000011110100'
- '010100010011011111100010010010110110000110010001100000101010'
- '110110010110110011000111010100000000100010000101011011110000'
- '111001011010010101011101111011101000110000000110001010001110'
- '110110000011110110010011110001001100101100011100011100000111'
- '100001010011110110101100100110101001000001100111101110111011'
- '001000110110101010111110000001100100000110001110110010000100'
- '111001000001010000011111011101101101001011010000111101010100'
- '100100101000100010011101000111101011000001111000110000000000'
- '111000111011111011011100001111111101100111010110111011100101'
- '011111010100011111110000000101111110010100001001010101011010'
- '100011100101000110010111000001000011101010110010010101000000'
- '111010111010011011010001101001100100111101100000100010110101'
- '010010100000101001100000101000001010001110110001000010011011'
- '001001110000101100000011100111111110101010101111000000011101'
- '000000010000100010110110111001001010000000111110000001010011'
- '001010000111101000010100100111111101101111001111010011100111'
- '011011100101101010110001110111011111010100111001001001011011'
- '111110110011011000000111011101001010100101001000000111011100'
- '010110000001011011000001100010010111101011101000000100100100'
- '100111100001110010110011000100110000011100110001100001100000'
experiment: batch_run/rand_str_60_30_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
