ancilla_dim: 16
bitstrings:
- '000101111011100001100010111011011000'
- '111100111110011111001001001011101000'
- '101111001100000011010101110111110110'
- '011101111001111111111100000011001011'
- '001101001010000001010010100001100100'
- '000000001010000111000100110110110000'
- '100110000000011101010110001100100011'
- '111001110110011101011110000100000011'
- '010111011110111111010010110011010100'
- '000110001110011010111000001101000100'
- '010011001011101110011010110110010101'
- '001110100101001000000011001111100000'
- '001110111101001100100100001100010111'
- '010100101101101000010011100010010101'
experiment: batch_run/rand_str_36_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
