ancilla_dim: 16
bitstrings:
- '1111000110110110110000100101110100100001111111000101'
- '0011101111100000000111110010001000001100100101100100'
- '1001000000000011001100010101000100101010000001011110'
- '1101000000011001001110111000111110100101000101011111'
- '1010001010110010110100010111010100111100001011101111'
- '1010101111011000000101100110001011101011110001011010'
- '1111001011101001111000001000100110100011010110101100'
- '1001001000111101100001001000110101100101110101111111'
- '0110111000001011101110000011000000101110010010100100'
experiment: batch_run/rand_str_52_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
