ancilla_dim: 32
bitstrings:
- '1100011101101001111011101100010110000101101111100101000010111110'
- '0001001001010010001111100111100111101110010101001101010101110110'
- '0111010011011000001010100001010110110101000110011101111001011000'
- '1101101101001001111111010110001101001000111011111001110010001010'
- '0111000111100100011001001001011010110001110010110101101010110000'
- '0010001001101000000111010011101100001010011110001000110100000001'
- '1101101011001000111111011011011111111011101100000100111101011001'
- '1010001111111010111110111111000101111101011001001111110000011001'
- '0101101110100010010010000011010111011010000101111100000110110100'
- '1111110100011010011000011111001011000001010101010010110100010111'
- '0010101010000011101111001101101011001011010001111111000010000100'
- '1111000010000101011010001000100001011001001011001110101001111111'
- '0010010110000001110111100000111111011010110100111110100010000001'
- '0001100001011000101110100100101000111101110011000011000010001111'
- '0100111101011100110001000010100000101010000100101001101001111011'
- '0110011000110100010110111111100101000111011010011111101011100101'
- '1110111110001011001111001111101011101010011100011111000010000101'
- '1111111101111010110111010010000010011100101101001110000110111111'
- '0101010100011111001010000101101100010100100111100111010011111101'
- '1011101110000001000100011000111001001001001010111110001101010001'
experiment: batch_run/rand_str_64_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
