ancilla_dim: 64
bitstrings:
- '0011101000'
- '0100010010'
- '1011010110'
- '0011011001'
- '1111001000'
- '1010011100'
- '1100111110'
- '0111110010'
- '1000011100'
- '1011000010'
- '1001010110'
- '1000011110'
- '0111110101'
- '0011011000'
- '1011001000'
- '1010110111'
- '1100100000'
- '1000111111'
- '0010101010'
- '0101011101'
- '1100001000'
- '1101001000'
- '1111001110'
- '0001010101'
- '0011100010'
- '0101111111'
- '1111011110'
- '1101010101'
- '1010101000'
- '1000001101'
- '1000101111'
- '0101111001'
- '1011111011'
- '0110010101'
- '1111000110'
- '1110100010'
experiment: batch_run/rand_str_10_36_end
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
