ancilla_dim: 32
bitstrings:
- '001000010111001111110110101101101100010100101100'
- '001011100001101000111111001111100000100010100100'
- '100100100100111111000000100101111010011000001001'
- '101010011101010011111101010011101011101010101010'
- '110011101111110010000100111010010000000010101110'
- '001010100110011000100001100100011100001110001000'
- '010001010110111101011110111101110000100100110010'
- '101100000011011101110100001010110110111100000001'
- '011010011101111101111110010101001101100001000100'
- '001110110110101100100001011000100101001000001101'
- '110010011110111100001100101000101110000010111010'
- '001001011111011111010001100000100010100001011010'
- '110010110110110011010101111000011000100010000110'
- '011000010011100111100011101010101100110010101101'
- '011011010011100000011100000011110011101010010111'
- '010000101000000010111000001000000100001101001100'
- '001011011100010000100010001010001001000100000011'
- '010110010100001000010011110000010001110001101001'
- '101110111110011001001011010010110000010000100110'
- '001100000111101111011111110101100111100010011001'
- '010011100111001101110011111101101011001011101001'
- '000001010100000101001010111011001000101000110001'
experiment: batch_run/rand_str_48_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
