ancilla_dim: 32
bitstrings:
- '011011110101100100010100001101011001111000100101011010111011'
- '100001001110111010101010010101000000011000111011001100011011'
- '100001011010010100011010100000100000111001111111111001010000'
- '000001001100000011011001100110101101111011011111111011000100'
- '000111110011111010101001000010010101010111101100110010010010'
- '100101011100011001011011110010001000001001010110100001000100'
- '100100101101000000111000101101011101100001100001101111001001'
- '000101100000101111000111111011100000010101000101110000111111'
- '111101100101100011001100001111000100011110001010000001001000'
- '001011110110011110000000000001011101010010111010000101000000'
- '101001001011001111010110111001111011000101000011101010101101'
- '111101011001010110101010011010110000010111111011010111011101'
- '011110111010110000001011110100101101011011001111011110110100'
- '100111000101000011001001011101101011011110010110101011100100'
- '100101011010011101111011101001010111010101010000011101010010'
- '010010100000000101101001000000110010100110000001100001011111'
- '001100100011001111110111101110001011010010101000001000100010'
- '010100111101010001010100010100010101110010010011000110011110'
- '001010011011010101001011100100011101110110010010100000011000'
- '100000111010101000001001101101100110100011011111110110000011'
- '011110110101111001000010011010111011010101010011110100001100'
- '001010110101101111111111111001111111111010001110001010001100'
- '111001101100000011101110100110011010011100011100100100101000'
- '000101101000000000110100011101111010011011101100000010000011'
experiment: batch_run/rand_str_60_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
