ancilla_dim: 16
bitstrings:
- '10111010110111010111111011001111010000111000'
- '01101111011110100010000100100001011110010101'
- '00111111110010110100001011011101101110011101'
- '10010011101011001111100110110001001101010110'
- '00000111111110100100011000010011100011001111'
- '01101110011111011100011000011111001101000111'
- '11101110100110000011000101001101000101111001'
- '10000111100100010101010110010100110111111000'
- '01000000000110111011110010001011111000110100'
- '01111001001110011111000000111000010011100000'
- '11011100001000011011000000010100110111000101'
experiment: batch_run/rand_str_44_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
