ancilla_dim: 32
bitstrings:
- '100101110011110000111100001000101101100100111100'
- '001101101111101000111010100000100111100001011100'
- '110100100000010000111010000001010010001100101001'
- '100000111001101110100100100011010101011000001000'
- '001011011010100101100010010101001010100000100100'
- '100000111000011101010011111001110010100011111101'
- '110111110011110000111110001100000100001010001111'
- '011100010001010000000110100011100111011111000000'
- '010001101111011110011010001110101010111000010110'
- '010110110111011001110110011011101101100100000110'
- '010111100010101100011010001101001001111000001110'
- '110011100100100110101010010110000000110101011001'
- '100010110001100000001011000110011000000011100001'
- '101001111011110011100001101111111110000010000000'
- '110111010110000001110110001010101011000010000001'
- '100000011010100111111011101000110011000000000010'
- '110011100110111010111000100000100010000000010000'
- '101000110010001100111011010010010100011111010100'
- '000001100011110110111100011101100011000010100100'
experiment: batch_run/rand_str_48_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
