ancilla_dim: 4
bitstrings:
- '00101010100101001100111110011000'
- '00110101011010100001010101011010'
- '00001000011011100000110010100000'
- '10101111010100011110000001001101'
experiment: batch_run/rand_str_32_4_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
