ancilla_dim: 32
bitstrings:
- '10100000110010110111000010100000011110100001001011011000010101000101'
- '10111100000111101101110110111110111011001101000001001010111101010100'
- '01100111011000100011010111111111001000011111010110000011111000000000'
- '11001001011110000010111100100000010011011001110111000100100111101110'
- '10011010001011010111101110101001000001010010010110011010011010001000'
- '10110111101010010110010010001101010000011011101101110000011011100110'
- '00101000001011111110100000001011101100011110011011111001010001000001'
- '11011000110001101011001010011111011000001001001101101100111101000011'
- '00001011011010100000101100000111101001001111010110111001101110111000'
- '00001010101010011011101011001100110011000001100100101001111011111000'
- '01110110001100101110101110001101110110010111000101111111111100010110'
- '11111011010110111110001110001101101111000101001010110001101000000110'
- '11010001000101100011100110001011011001000100101010001111010110001011'
- '01111101110000111111010011010110000011001100101111001001111100110110'
- '00110001110110100011000100000010011101011100101000011101011101111001'
- '11001010010001011101011111110111010001110101111010110010100011010001'
- '00010100000000000010101101101111001111000001110001000011000010000101'
- '01100110101011100011000011001100110011001111000111100100110100111111'
- '11001100000011100010101101100010100000001001011101001011111100111110'
- '01001000000100001010001010000001010001101000110010101111111010100001'
- '10011100100111110100111011000001001001001110011110010111000110010111'
- '01011001101010001001110000011000001111111011100010010011101111011011'
- '01101000101111001101011101100001001011110010011100101101101100100110'
experiment: batch_run/rand_str_68_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
