ancilla_dim: 32
bitstrings:
- '001111100000101110001000010110000100111001011001100000111111'
- '011100100000010010010110110000010011101100111101101101010100'
- '011111110110111101010000001000001111111110110101101001011000'
- '001110011000011100001100101011000111100111101000010100001101'
- '000010100001010111111111100011010100000111010110100011000010'
- '010100100010010001110111000111000100010100000101101101101001'
- '100000000110100011001100000001000100110010001010000001010100'
- '110101010110011001011001101101010100111001000001100100011010'
- '001011000001111110111100101000111001010010011100001011101010'
- '001101110110011111000011100100001101110011100001000010111010'
- '101001101100000100100101110010111001110101010101101101110001'
- '010111000010110101001010000000010100001011101100111101010110'
- '010110111011001010100111110111100110001100010000110010100011'
- '111010000100100101010001101010011100000110011011100111110011'
- '000010111110011000100001101000001100100111010101011000011101'
- '001101101000001100001001011000101000100111001000000111110010'
- '100100101111011010011000001001000001100100110110010001101111'
- '100001110110000000110101100110000100001010101011001010111010'
- '100011110100000110010101011011011010110110000110100110011110'
- '111001101111010111100011010100001100111000000100001100000111'
- '010011001111011000011110110010111111011111100101000000100001'
experiment: batch_run/rand_str_60_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
