ancilla_dim: 8
bitstrings:
- '1111110001100010011100110000001000010101111001011000111010000100'
- '1010001011101101100011001001101010011001001101100000000101110001'
- '0101000010101011000101100000101000001110011111010100001010100110'
- '1101111111010111000100111010101100101001100010011010101110001010'
- '1100101110100100101000001111110110010010010000001100100001010010'
experiment: batch_run/rand_str_64_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
