ancilla_dim: 16
bitstrings:
- '1101011111001000000010010000'
- '0111001001110001011010101111'
- '1010010100010110001101110101'
- '1101101101110001101010100001'
- '1100001001001100110011110010'
- '0100001110000011000010111000'
- '0100000110101000011001111010'
- '1000101000000101101100111010'
- '1101010101110111000111000101'
- '0010001101000000011001001011'
experiment: batch_run/rand_str_28_10_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
