ancilla_dim: 32
bitstrings:
- '011011000111110101111011010100101110001101011101'
- '001111100000011010110001011010001011010000011101'
- '000111001000001001110110000101100001011001011010'
- '010000101000011110101001001011011101001101001000'
- '100110010101010001110000001110010001111111101101'
- '100101010001110001101100000001111011101111100110'
- '011110110000011000100010111011101001011100001000'
- '000001100001010000011010110110000111100000000100'
- '110010100001101010001001010100111000110101100100'
- '111001111101100000000101010001110111000101010010'
- '011110010010010000000110110110000111001110010000'
- '000001001001011010110011011101100110101000101110'
- '001111101000010110001010001000101111100010111101'
- '100001011000101110011111011101010111111111100111'
- '010011001001011100100101010111110110111000110111'
- '110110110000000010110111111111110111111011101101'
- '110000000110110111110011010010011010100110111100'
- '100011000110010001100101011010000000111100101001'
experiment: batch_run/rand_str_48_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
