ancilla_dim: 32
bitstrings:
- '1011010011000100110101011100101110011100101110100001001001101011'
- '0110001100110000000010111000100110000110111100111111111011110101'
- '1010001111000111010010011001001110101000110110010011100101110111'
- '0010000100110100100000000100011001011010100100100101111101010011'
- '1110111101101011110110100100100110100100110000110110010000001100'
- '1000100110101100110111000111101111011110001110011111101111010100'
- '0111010110010101110001011001011001100011010111100111001001011101'
- '0000100010000001001101110011001001111011101010110110011000010001'
- '1011101000100100000010001110001011011001100001111101100111000100'
- '0110101000110110101010100101010110101011001011110111100100100101'
- '1101110110110101001110101011111001100000010110101111001010000111'
- '0010101010110101010100010001000001001011010011111011000111000100'
- '1011111101010111100010101111110110010011111101011010100001100011'
- '1001110010110001001110100110000100110110100100100101000001111110'
- '1001100011100001000101101010001011010010111010110010101000010111'
- '1110010011111100100101101111111100101110010101100011100110000100'
- '0101101101111001111100011010110111111111111110110001010000010110'
- '0111001111101011111110101001100101001110111110001111001110000000'
- '0001100011111111011100011000000101100010101100000001001100110111'
- '0100010010000100001010101100000010010001100011100001111000110100'
- '1101101110000001000010100111010100011001100101000101010101111000'
- '1100101101001001111110111010010111000100000100110101000110010011'
- '1011100101110000110010000111000101010101100110101100100000001010'
- '1100100000100001110100010011110101111111010101001101000011110000'
- '1101010110011111011101101001100100111100000100110110110001110111'
- '0101011011101110000001101010110000110001001110100001110111101100'
- '0101001100100011111000000000101011111001000100000001111101100001'
- '1000101000000111010001100110000101100000011110000110001001110101'
- '1010111101001101100000101111000110101110001000100101110011100010'
- '0111010000001110000000100110001001111001001110011000011101111011'
- '1010010001111110000001010110111111010011111110011111011000000101'
experiment: batch_run/rand_str_64_31_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
