ancilla_dim: 256
bitstrings:
- '0001110111'
- '0111101101'
- '0001101000'
- '1001010010'
- '0001101011'
- '1010110011'
- '1000110100'
- '1000001100'
- '0110011011'
- '0011110111'
- '0101010001'
- '1110000110'
- '0001110110'
- '1101110000'
- '1111000000'
- '1000001110'
- '0010001001'
- '1000111011'
- '0001101100'
- '0101100111'
- '1010101000'
- '0000000110'
- '0011100110'
- '1001110000'
- '0010100101'
- '1010111001'
- '1100001001'
- '1010101101'
- '0010101100'
- '1000110110'
- '1000111001'
- '1010010011'
- '0110011000'
- '1110111110'
- '0000101001'
- '0011010001'
- '1100111101'
- '1001110110'
- '1001010111'
- '1111010101'
- '0011110101'
- '0011110110'
- '0011111111'
- '0111011000'
- '1101111101'
- '0010101001'
- '1010011101'
- '1000100110'
- '0100110111'
- '0100100110'
- '1111001111'
- '1001110011'
- '1010110110'
- '1100011110'
- '1011100100'
- '1001001001'
- '0110011100'
- '0100001011'
- '0001111110'
- '1111000001'
- '0011011101'
- '0111101100'
- '1111101100'
- '1101100001'
- '1100110100'
- '1100101100'
- '0111110101'
- '1010100001'
- '0100111011'
- '1010111100'
- '0000010001'
- '0010100010'
- '1000111111'
- '0010011011'
- '1110010001'
- '1001111111'
- '0110110000'
- '1110110101'
- '1110110011'
- '0010110111'
- '1111000100'
- '1000000000'
- '1000101000'
- '0011100101'
- '0001000101'
- '0101011001'
- '0011001110'
- '0001110011'
- '0010001110'
- '1101110011'
- '1011000011'
- '0001110101'
- '1101000000'
- '1100011111'
- '0101010100'
- '0000001001'
- '1100000001'
- '1001111000'
- '0010110100'
- '0010110010'
- '0010001010'
- '0011100011'
- '0101101000'
- '0000100001'
- '1110000001'
- '0001000011'
- '0010100111'
- '0111011110'
- '1110101001'
- '1110100010'
- '0101111101'
- '0011101000'
- '0111000011'
- '0110110101'
- '1100100010'
- '0010000011'
- '0100011101'
- '1100110000'
- '1111000101'
- '0111000010'
- '0110100010'
- '0011011011'
- '0101100101'
- '1110111111'
- '1100101011'
- '1001111011'
- '0100000111'
- '0001100001'
- '0111001111'
- '0101010000'
- '1001000101'
- '0110111000'
- '1101100000'
- '1101110101'
- '0000011011'
- '1100100101'
- '1001110111'
- '0101001100'
- '1000010001'
- '1001110101'
- '1110110111'
- '0010000100'
- '1010110101'
- '0100011111'
- '1101011111'
- '0000000111'
- '1100010110'
- '0011010101'
- '0101000011'
- '0111100111'
- '1101000001'
- '1010111010'
- '0100101000'
- '0101001111'
- '0001010111'
- '0111001011'
- '1100110111'
- '1011010011'
- '0111000000'
- '1101011001'
- '0111100011'
- '1001001100'
- '1000000001'
- '0101101101'
- '1010011000'
- '0001110010'
- '0001001001'
- '0001001111'
- '1011101000'
- '1101110111'
- '1100100011'
- '1001001011'
- '0011000101'
- '0111011111'
- '1101100111'
- '0010000001'
- '1001011100'
- '0001011100'
- '0111111110'
- '1000101110'
- '0010011010'
- '1110001101'
- '1111101000'
- '1011001100'
- '0010110001'
- '0011000110'
- '0100011110'
- '1111110011'
- '0000000000'
experiment: batch_run/rand_str_10_189_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
