ancilla_dim: 8
bitstrings:
- '10101111100111100100101101010111001110110011111110100110001011001010'
- '11101100011010111100110100100010100101100111010010000101110000111110'
- '10100010011000100011011001011111100001000110110010000011100100010001'
- '10110110101100001101000101110001110111001011100010010011000100111111'
- '00101010101010111110100110111000011111101001111100001010111010110101'
- '11010011100100101101101101101101111011010010010001111011101000001101'
- '11010111000011011100101000000001000000011000011011000100010000110010'
- '10101000100100100101100000001110110101011100000000011010010001001010'
experiment: batch_run/rand_str_68_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
