ancilla_dim: 32
bitstrings:
- '10011010000000101110000101011011100111110010100000001000101011001110'
- '10111000001010111101110100001100011111111010101101010100111111001011'
- '00101100110011110111100111111000100011100000011000000111101111010011'
- '11110101011011100100000110101010001001101111010111011100110010011011'
- '11111111101100101111000110100101111000100011111000110100000000001110'
- '10001110011011010011111011110100011001100000001010110000100110100111'
- '11001011010111001010101000011011111001111111110111111011010100100001'
- '10101001101010010001110111100101000001001111000111111001100011101001'
- '01111111010001001000110011100100010100010010011111010001011100100110'
- '10011011101011000100100111000000010100110010101001111001111111011110'
- '00100111000000001111010101011100010110011100000110100110110000111100'
- '01110010100100010110111011000000110010011111101001001000101011010011'
- '11111011001101100010101011111111001101010110111001101100010101010110'
- '00010011010010011000111001000110000001001100011001000110001001110101'
- '01111110011000110000000001100110011100010111111110000001000111111100'
- '10010110011101000000000011010110111000010001100101001101010110110111'
- '00001111100100110001111011101000000010100111100011000100010010001101'
- '11110011001010000001101010110100101100110010010110001110010111011010'
- '11111110001100000110010111110101001011000010011111010010101101010100'
- '10010110011010011110111110011011100011011111010110111100001101010100'
- '01100001010110011011110001010100001110010010001000101011001110010100'
experiment: batch_run/rand_str_68_21_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
