ancilla_dim: 64
bitstrings:
- '1101011100'
- '0100011011'
- '0110100000'
- '1100101111'
- '1110011011'
- '0000010010'
- '1101000011'
- '1101010110'
- '1110100011'
- '1001001000'
- '0000101100'
- '0010101011'
- '1010000011'
- '0110010001'
- '1000010010'
- '0111001000'
- '1010110010'
- '1110010100'
- '0101000111'
- '0101111010'
- '1001111011'
- '0100101001'
- '0101110010'
- '0100011001'
- '0111010100'
- '0010100011'
- '0101000010'
- '0100010101'
- '1110111010'
- '1101000000'
- '1000101000'
- '1111111101'
- '0101100101'
- '1001101100'
- '0001110011'
experiment: batch_run/rand_str_10_35_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
