ancilla_dim: 16
bitstrings:
- '000110011000001001001110101101000011101110111001011011100010'
- '011110100010100011111011001010101100010001010101111000000101'
- '101110101111000010100010110010110111111000011111100110111100'
- '001000010100101010001001010001010001101001000000110101010010'
- '011111111011101011000111010101110100100101100101101110100101'
- '001111011011010010011100101011000101010111000010100011010100'
- '011101011001111101100011100101101111110001101010101111011011'
- '000111101000110111010110000001111100110001111001110100011100'
- '100110100010110100111011110010001001000111110110110001110001'
- '011111101011100110000110001111111010010000010100101100000010'
- '101011101111100000011000110000011000111101101101100011011011'
- '000100101011001001100100000010111101110000100110000101111110'
- '100111001001101000011000110010100010000000100001001010111001'
- '011010101111111111111011011001100101001110111010001100011111'
experiment: batch_run/rand_str_60_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
