ancilla_dim: 64
bitstrings:
- '101111001100'
- '111011001101'
- '001001100101'
- '010001001001'
- '011000100000'
- '100001100010'
- '000100011111'
- '000111101010'
- '111100011101'
- '110100111110'
- '110101110011'
- '110001001111'
- '110011001110'
- '100101010011'
- '000001111100'
- '001101111000'
- '001000100000'
- '110111001010'
- '111111000100'
- '011111100001'
- '010000110000'
- '000110001111'
- '000110100100'
- '101000011011'
- '010000110011'
- '000110010110'
- '101010100110'
- '001001101011'
- '100000111001'
- '001100111110'
- '111111000010'
- '110011111101'
- '000100100001'
- '110111010011'
- '110100101100'
- '100110110000'
- '111010001111'
- '010000011101'
- '001011101110'
experiment: batch_run/rand_str_12_39_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
