ancilla_dim: 8
bitstrings:
- '00111000100111100001110101010001000111100000101110101001'
- '10100110101011101100010111110110100101101110101110110110'
- '10000001101000101100111001101100011001101100010110111011'
- '00010110001010111011000001000110011010010001000110110110'
- '11101111011110100010001110111011000100011110000110110010'
- '10101101111000011100101101101111000011100011001111001101'
- '11011010001111011101010111101001000000100000010011101110'
experiment: batch_run/rand_str_56_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
