ancilla_dim: 16
bitstrings:
- '11110100000010100000010010000110100111001010011111001001010100010011'
- '11100101100000000000101001001000101011101011011010100000010100110001'
- '01100010011111101011010011100101001001101110001101011101000111011110'
- '10010010111010111100011111101010000011100110111010100001001101001000'
- '10101011010100101111010101101110100101010001110010001000010010111001'
- '10010001110100110000101011110100011001000110111011100000111010010001'
- '10110000011010000110010101000110101001101001101100000101111111101110'
- '10011110001100110000101000100100101111001011101111010011100011111101'
- '10011100100101101001110010101010101010110110010010010011001011000101'
experiment: batch_run/rand_str_68_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
