ancilla_dim: 32
bitstrings:
- '1001100011100001101000001110001010000111010000101011001000111000'
- '0110111001000001011000100001011100010001101000101001101101101010'
- '0111100001100001101001011001011111110110110000001100111001100110'
- '0000101001101000001010010101100011111100100100101111000110100111'
- '0100011010111001101110101111110011100011110000010100010111000100'
- '1101011101011000000111101100111111111011001100010110010111010101'
- '1011001011110110110100111110111100111001101101100000001011000000'
- '0110000110011000101111111110101010101001100001110000101111011111'
- '1101111010011110100011000000110110100011100111010000110101010000'
- '1001000100010001000001110000100101110000000010011111011001110101'
- '1011101000011100001000110001100000100010110111100011110101001010'
- '1110101101011010010001011011100001101100010110110010111110001110'
- '1100011101110001110000110111000000101110111001011010010101111001'
- '1010111101011110010110001000010001001111101011111110110110110110'
- '1101000111000011101011011010000000110000011010000111110100011001'
- '1001100010010000101110100100110001100011110101111001100110101000'
- '1000010110101011110011100001110111001010101001001110000000001000'
- '1011111111101010101101101000101001011100101001101110111011000101'
- '0111001000110101101000110001111101000001000001100010110110001010'
- '1101011010011011101011001000110001011001010000110010100110110100'
- '1001100001000111100000101101110110011011010111011101011001011010'
- '1001000110111010101011101100011100110011000100100000011100001011'
- '1100101100011111001000011101101001011111101110100011111000011010'
- '1011010011110101100011000011011011100100111000110011110001000011'
- '1010010100100001111111001000111001100111101011000100100101010100'
- '1010001010000001111110001000001111001000101010001001111011010100'
- '0101110110011011111100111001000111011001101100100101111001000010'
- '0000011010001011100011110010000111001100010010100001011010010001'
- '1010001011010001000000011001000101101011110000010011100111000110'
- '0011000011011110010010100001000010101111110101000010011011110011'
- '0000001001000011100010110010000111011101000000010111111100110110'
- '0110011101100100101000011111000111100110111110000110111010001000'
experiment: batch_run/rand_str_64_32_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
