ancilla_dim: 16
bitstrings:
- '00001110000111101001101000100111010011010000'
- '00001011110100101000001111101101110101001011'
- '11111101001000101011000110011111111100011111'
- '01100000001110000111111011100100011001110110'
- '10110010110101111000010100000010011001111100'
- '10110010100110010011100110110111010101110110'
- '01111001011000011101010110100001010111111011'
- '10100100110011000111101110000000000001000100'
- '10001101110100010001001100111001100011100000'
- '00110000100110101011011000100110111010010110'
- '10110000110101010101100010101110010110011111'
- '00001101000010111101110111110100001111001010'
- '10001101000000100001101010101011011101100011'
- '01011011111010110011100001001110011001011100'
- '01001100011001011011110001001001100101010000'
experiment: batch_run/rand_str_44_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
