ancilla_dim: 32
bitstrings:
- '001001100000001011101101001001000101011111111011011000010011'
- '101001010110101111110001001101000110011011000011000101000111'
- '000100111100001110001001000110001100010000001110110011101111'
- '011111001101111011000001000111011001010110110111100000110111'
- '000001100110100001111011000011000100011001111011110000110011'
- '111100110000110011101000011101000011110001100101001000110000'
- '010000000011100001101110001100010111101000000101001000010011'
- '101101110111000000100010101011110100000010100000101010010001'
- '011000001011010011110100101010011001100001011010110001101101'
- '010000001100011111000100110110101000101101001010000000110000'
- '110110000110011100001011110101100100001110010100001110001101'
- '110011100101010001001111111101110010100100010011000101101011'
- '010111110000011001111000111001100010011101011010011000110001'
- '001101111010111000111110000100011011101001001100011001101000'
- '100110001111001010111000110011010001110100000101010010010100'
- '100001111011001000000001000110000111101111000100100101110000'
- '010100100010110001011111011100001100000000110010010101010001'
- '001011011000000101101011010100110011101100010011110110001010'
- '111001010101011001101110000011000011000010001011101010000101'
- '001110010110110101001000011101110100010010001100101000110111'
- '001010101001010000110100100101001001010011011011111111000001'
- '101111011010100000111000010000010111111100000101010100101000'
- '100101110110111011111001001000101011101011010011011110110101'
- '010011000000101100101011001110001011000001110010001101110000'
- '011111000001001100001100011101100000001100011110111111001101'
experiment: batch_run/rand_str_60_25_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
