ancilla_dim: 32
bitstrings:
- '01110101111101111010100010010011100000101101011001011001'
- '00101001000011001111010001101111010010011110010110110000'
- '10001001111100011101001010011111010001111000001111101111'
- '11011011001001110110001011001111111001000110101111100100'
- '01101011110101010010011110110011001001011100010100000101'
- '11011001010000010100011100010111111011111110101011110001'
- '10000000000011110001010101010011001010100010001001010010'
- '11111100011011000111100011010101011001111000100100010100'
- '11100111110110001100001010110011011100000000000010001011'
- '10010001110100100101000111010111101001011101100110010110'
- '01111000011000101110111010110101111010101101101000110110'
- '10000110101100110000101101011010001000000000010101001101'
- '00001111111111101110001101000101111111000011000010110100'
- '01000011000001111100010001110100011000011100011011011001'
- '01011111011111100111101001011010100110000110011000110101'
- '10001011001110001110011100011100001110001111111011011011'
- '01011101000011011111101000101111101001001110101111010001'
experiment: batch_run/rand_str_56_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
