ancilla_dim: 64
bitstrings:
- '110011100010'
- '100000000010'
- '000100000110'
- '110111111101'
- '100010110110'
- '001101111101'
- '011111101111'
- '111110101011'
- '000001001011'
- '101011001110'
- '101111010000'
- '101100100101'
- '000101010101'
- '001110010110'
- '000101001111'
- '010001110110'
- '111111001001'
- '010111011110'
- '100101111110'
- '001010010100'
- '011110010000'
- '110011111101'
- '100001110001'
- '100100101011'
- '111101000110'
- '011010000011'
- '101100101101'
- '010110000100'
- '001001100110'
- '111001101011'
- '010100001111'
- '101000000001'
- '010001010001'
- '011000000010'
- '001000100010'
- '000000111111'
- '010111001000'
- '110101011010'
- '010111111100'
- '000001101001'
- '100101001100'
- '011100101111'
- '110110100101'
- '001000010000'
- '110110011000'
- '111010000001'
- '010110111001'
- '011011101000'
- '010000101001'
- '100111011010'
experiment: batch_run/rand_str_12_50_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
