ancilla_dim: 32
bitstrings:
- '0000111100011001000101001000000011100000010110011010000111100010'
- '0111101101111101000100111110100000001001010100101100101111000001'
- '1111010101100000101110000001101101001001011111111100110011111011'
- '1111100010011101001000101001101101001000010000000011100001001000'
- '1000001011111011100111110100111011111011111111111110001111101001'
- '0000110010001011100101100001111000110111011111100001000011110101'
- '1001101001110110011011011110101011010111001010101110100111110000'
- '1010000010100100111111100101110100110100110010011000000001101101'
- '0010111011111000001101110010100000110010000101011101000001001011'
- '1010001100011011011001011100111011101001010000110111100000100100'
- '1011100101111011111011111010011000100110110111110101000000000000'
- '1011000011000101101100010000110101001001000001000000111001001001'
- '0010010001101011111101100000001101111010010011101000001001100110'
- '1011011011111011011010110011111010001100011101101100100000010010'
- '0010011110111101011101110100001111111100011111110010010001110101'
- '0000000001001000100010000010110101110111001100110100111110111011'
- '0000100111011011100000010010010001000000010111010000110010000011'
- '1001101110101011100010011101011100011010100011000101011101110001'
- '0001111100001000010100100101010011011101011100001000011100011010'
- '0000110000110101010101011011011100111000001110100101101010111001'
- '1001111101100111100101101110010011110001010001101001001100100011'
- '0100101000011111010000010110000101010011100110111110110011111110'
- '1010101111011001010011000010000101001101001111110011011001010100'
- '0111000000011000010101001001101000010110010001001100010111000010'
experiment: batch_run/rand_str_64_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
