ancilla_dim: 4
bitstrings:
- '110110010010'
- '010111000000'
- '001100010001'
- '100000010111'
experiment: batch_run/rand_str_12_4_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
