ancilla_dim: 128
bitstrings:
- '0001101100'
- '0111110110'
- '0100011001'
- '0101001110'
- '0000111010'
- '0111000000'
- '1100100001'
- '1010111111'
- '0010001001'
- '1011000110'
- '1000001110'
- '1100100011'
- '0011111101'
- '1110001110'
- '1101010101'
- '0000110111'
- '0011101000'
- '1110110111'
- '0001000010'
- '1010110111'
- '0110100111'
- '1001100110'
- '0011011101'
- '1010000100'
- '0000101011'
- '1110111100'
- '0110011101'
- '1101100001'
- '1111110000'
- '0001000000'
- '1111000101'
- '0011111100'
- '1010010100'
- '0010111011'
- '0000000001'
- '1100000101'
- '1011000011'
- '1101000110'
- '0111011001'
- '1101010010'
- '0000011110'
- '0000000000'
- '0111011100'
- '0111111110'
- '1000101000'
- '0101000100'
- '1100011000'
- '0110001100'
- '1101111111'
- '1100110111'
- '1010001001'
- '1001111111'
- '1111001111'
- '1101110100'
- '0100001010'
- '0111111010'
- '1010100101'
- '0011100001'
- '0110110111'
- '1101110101'
- '1001101001'
- '0000001000'
- '1111110001'
- '0101111100'
- '0111011000'
- '0100110110'
- '1011100011'
- '1010011110'
- '0011010100'
- '1001111100'
- '0001011001'
- '1000011010'
- '1001010001'
- '1100011111'
- '0110010111'
- '1011000000'
- '1111100001'
- '1110011111'
- '1000100100'
- '0011101010'
- '1100101000'
- '1111101001'
- '1100111000'
- '0010101000'
- '0010101001'
- '0011111110'
- '0010100000'
- '1111011001'
- '0100010000'
- '0100010100'
- '1100100010'
- '1100001100'
experiment: batch_run/rand_str_10_92_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
