ancilla_dim: 32
bitstrings:
- '00101010100100110101101000110010011101011011010111110000101000101001'
- '11110100110000010110111111101111110100100000100011001011111011101101'
- '11001010010101100010110011010000111010100011001001010011100110011010'
- '10010100111011001000000111010101011001001000000100001101011001010100'
- '11111001010010110101010001101000110001000111001101010110100011010010'
- '01000011111101011111101110010001111110100101101011111010110010101111'
- '01100111100110111010010101110111001111010011111010000101111000010001'
- '00000110001101000101010011000001100000101101001100111000001111110000'
- '10010011010011100000001011111010010111100111111110011101111101011110'
- '11110001111101111011110111011101111000111100001111001111000110010011'
- '11010010010001101101000000001100010101110011010000101010011101011110'
- '01011010111110010100110101000111110010110111101110110011100011110011'
- '01101011001100011101010011101101100001110111011000001101001010101000'
- '10111000100110011000000010100011100010101101101011000011000000001101'
- '10000100000000100011000010010011010011110000001111111110000011111011'
- '01001111111010010010100101101111001101110010111010011101010000100100'
- '10010001000001000100111001110000000000000110100011101011110001110101'
- '01010111111010111000100101010000001100011111001000000011011000011101'
- '11001110101011101001011101110001000011001000011100000101110011111000'
- '01001101001110000101000001001101001110101100100010010110001101100110'
- '00000000100001010000001011010000101110101000110111000001010011000101'
- '00111100010011011110010111101101110100011101000110011110100010100010'
- '10110110001100001001101001011010011011000001010011110001001001011011'
- '11100011000101000001100100011011011000000010010011001010100001011110'
- '10101110101101111111001110110000100110111001000010001110010001011111'
- '01000001110001100011001100110101100101000110011110100011010100100110'
- '00000011000101011001101011101001011111010101100000011000110001010011'
- '01011001111111010000010011010111100111111010010011100100011100000100'
experiment: batch_run/rand_str_68_28_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
