ancilla_dim: 4
bitstrings:
- '010100011100011100111000101101011100'
- '111001111011100111100100011010110001'
- '001011111111001111101000111000111000'
experiment: batch_run/rand_str_36_3_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
