ancilla_dim: 16
bitstrings:
- '10111100011000101101101101111010000111001000100100001100011011111100'
- '11110101101001000101111100111110001100100111000001001110011101011001'
- '11111110010110101011010111110111110100010110100100110000001010100000'
- '11011010110110000100001011010000010000000011111111111111001100010100'
- '00010101000010100101110110101001000010000110000011001110111100110110'
- '11001010011110000111100000110101100100101011110110011011011000111010'
- '01100010100001110010010001011001000101101111010100011011101001110010'
- '00001111001001110001100001011100001101000110110110000000010001000111'
- '00010101000001000111111010010111100000100000010101000000101000000010'
- '00010101000110110101101001100100011000010000100001111011111111001101'
experiment: batch_run/rand_str_68_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
