ancilla_dim: 16
bitstrings:
- '1001000000'
- '0100100001'
- '1111110011'
- '1000010110'
- '1100101110'
- '0110111101'
- '0100010111'
- '1010110111'
- '0011011010'
- '1111100000'
experiment: batch_run/rand_str_10_10_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
