ancilla_dim: 16
bitstrings:
- '00100110110011101001101100000101001001010010001011110110'
- '01101101100011100111111111010111100000000100010001010001'
- '00000111000011110010011111000110110010100011100001111100'
- '10011100100100101001110010011011110110101111111000100001'
- '11101011010001101110111110001011000011010110100010001110'
- '11010010001011110010101001101000000100111101110110000011'
- '00100111011010110011101101101001011011101000010011010101'
- '11010100110010100100101101010011100001111010111010001100'
- '00111011100000000110111111010000101011110101111001001000'
- '01111001010100010011011011010111010010001010010011000000'
- '11011100001100111011100110110000000001100011000110001101'
- '11011001000010110101010101001000010000111101111110101100'
- '11010111010001110001000011111110001100110110100001100110'
experiment: batch_run/rand_str_56_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
