ancilla_dim: 32
bitstrings:
- '1110001101111110000111011000011110111100'
- '0001010001011001111010110000101011001011'
- '1000111001011000101100100111110111001111'
- '1000001111000011011100010000110000110011'
- '1000001111001011010001010010111110000011'
- '1101001000000010010010000110100001100111'
- '1001100000101000010100101011010110001100'
- '1111101010100100101110011001000100010000'
- '0001101110011100100000101101011001100001'
- '0100111010110010110111011110000010100111'
- '1101110110111100011000100010010110111011'
- '1101110110110111110010011100001011101111'
- '1110110000100010000110011011001111101001'
- '1111011001111100000011100100101001000100'
- '1100100110110100101110100011011000110000'
- '1000110100001001101110011110010010001111'
- '1001101110110110011110111000000110010011'
experiment: batch_run/rand_str_40_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
