ancilla_dim: 256
bitstrings:
- '0110011100'
- '1000001100'
- '1101010000'
- '1000011101'
- '0111110111'
- '1011111001'
- '0011100010'
- '0110111011'
- '1110011000'
- '1000111101'
- '1111100011'
- '0010101111'
- '1101000010'
- '0101011101'
- '0110010001'
- '0010111110'
- '1010101001'
- '1100011111'
- '0110100001'
- '1101000111'
- '1011100010'
- '0010000111'
- '0010100110'
- '0111000011'
- '1110000001'
- '1001001110'
- '0001000011'
- '0100111110'
- '0000100011'
- '0100011110'
- '1111110100'
- '1011011110'
- '0110110010'
- '0110101010'
- '0110101000'
- '0101110100'
- '0000010000'
- '1110000011'
- '1111010111'
- '0100110111'
- '1010000000'
- '1000110111'
- '1011110010'
- '0100000011'
- '1001001101'
- '0111101110'
- '0000000010'
- '0110001000'
- '1111101100'
- '0000101100'
- '1100010010'
- '0010000101'
- '1011001101'
- '0000000000'
- '1010010010'
- '0110100111'
- '0110001001'
- '1000000110'
- '0100011001'
- '0001100001'
- '1100011001'
- '0111110101'
- '0001101011'
- '0010110011'
- '1010111101'
- '0000100100'
- '0011101111'
- '1110111000'
- '1111110011'
- '0000110110'
- '0011011110'
- '1111111110'
- '0111101001'
- '0010110101'
- '1000111010'
- '0101000110'
- '0111011100'
- '1011011001'
- '1000010101'
- '0010000010'
- '0100010010'
- '1100101110'
- '1010101110'
- '0010101011'
- '1011110011'
- '0010101100'
- '1111100000'
- '0110100000'
- '1001001011'
- '1101000101'
- '0100001010'
- '1001011011'
- '0100010110'
- '1110001001'
- '1011010101'
- '1100011110'
- '0010101101'
- '0100011111'
- '1100101100'
- '0100110100'
- '0011100101'
- '1101110101'
- '1100011011'
- '0011100000'
- '0000010101'
- '0000000011'
- '1110001110'
- '0111110000'
- '1000011011'
- '1111001110'
- '0010110010'
- '1001001001'
- '0101111010'
- '0110000101'
- '0011101001'
- '0100001111'
- '1111111000'
- '0010000011'
- '0010000000'
- '1000001000'
- '0000101111'
- '0110000000'
- '1101101110'
- '1111011010'
- '1100110111'
- '0000111110'
- '1110101110'
- '0000001110'
- '1001111101'
- '0000001100'
- '1101001100'
- '1010101100'
- '0101001111'
- '0100010000'
- '0101100101'
- '1011000101'
- '1101001101'
- '0000100000'
- '0111011010'
- '0010100000'
- '0010011111'
- '0110101110'
- '0011111101'
- '1110100111'
- '0011100111'
- '0010100111'
- '0000011101'
- '1101011100'
- '0001010000'
- '0101011110'
- '1011100001'
- '0101010010'
- '0101001001'
- '0110000001'
- '1011100110'
- '0001010001'
- '1011001000'
- '0011010000'
- '0000001010'
- '1101111001'
- '1001110111'
- '0111111101'
- '1100000001'
- '0111101111'
- '0101010011'
- '1100101111'
- '1010001100'
- '0100111100'
- '0010011110'
- '1110110100'
- '1110000111'
- '0111100100'
- '0011111011'
- '1011001011'
- '0001000001'
- '1110000110'
- '0001111100'
- '1101111110'
- '0101100011'
- '0111010111'
- '1100011100'
- '0011000001'
- '1001010001'
- '0000011011'
- '0100000010'
- '0000011110'
- '1001100011'
- '0010000001'
- '0110111101'
- '0100001000'
- '1010000111'
- '1010100001'
- '1100100100'
- '1010011111'
- '0100001100'
- '1111010000'
- '1011000111'
- '0101011111'
- '1011100000'
- '0110001011'
- '0100000000'
- '0000011000'
- '1010110111'
- '0001111011'
- '0111100011'
- '1101011110'
- '0011100011'
- '0110010101'
- '0110010011'
- '0011010010'
- '0100011011'
- '1001000100'
- '1010101101'
- '1110110011'
- '1101101000'
- '0001101010'
- '1111100010'
- '0100101011'
- '0111001101'
- '1111011011'
- '1101000001'
- '1111100101'
- '0001011001'
- '0101110101'
- '0110001101'
- '1101001001'
- '0001010011'
- '1000101101'
- '1100001100'
- '0011110000'
- '1010111010'
- '0011110010'
- '1001101000'
- '0010001100'
- '1000111000'
- '0111111111'
- '0110000100'
- '0011010101'
- '0110001110'
- '1111001101'
- '0011011101'
experiment: batch_run/rand_str_10_241_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
