ancilla_dim: 32
bitstrings:
- '000010100111011000001110101000001011001010100000001000111111'
- '100011000111111110101101110100100110001110100100001001100001'
- '111001110011000011010110000010101110000101000000011111100100'
- '000001101010100001011010101011001000111111111001010000001000'
- '001001001100110010101001011111000001010111101011010010010111'
- '010001111011001101010010110011000001010000100110110100111011'
- '111110111111111110100110010010101101010110100010000000100111'
- '101111110001001001001010011000000001100111101110101000001011'
- '110000111100111010011110001111000011110011011010000010100100'
- '000010010110011001111111111110111000011111101100000010101010'
- '010101110010001100110010110110100010110010010100110100001111'
- '011111011110000000000101111000000000000000111100011010111010'
- '101011000110101001110111000011000010011001110111100100011101'
- '111010000100001011010101010000010101001101001110000000101100'
- '100100010001010110101101001100100101001000111101100110010011'
- '011110001000100000111011100110100100100000001111101011010010'
- '000111010100110011111110010111010010010101000110001111011110'
- '110011100110010001101110100000011001110001110101110010100001'
- '100110110101001111011110110111110110001011010111100101011111'
- '010110100110001110111101100000001010001110111010000000110000'
- '100111110100011111001011101111010010001001001011101101100100'
- '100101011010101011110000101000111110101010001101001010000000'
- '111100101100110111001000010111110110000010011100000010111100'
- '111111011000001000111111100001000001111101110011011001010000'
- '110101110011111001000110100100001001110100101000111111001101'
- '101111111110101111011101100001000100000010111000011001110100'
- '100001011001101111110010001101101111111010100010001101110111'
experiment: batch_run/rand_str_60_27_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
