ancilla_dim: 16
bitstrings:
- '111111110101011010110000000101100001'
- '010000110000101101010100111111010111'
- '011010010001000111001011000110001111'
- '000110001000111001001110110110101000'
- '011010000010100001101111011001100000'
- '011110110000110101001010110101010111'
- '101111111101001011010000100110100001'
- '100011011110101000011010010000010110'
- '010100101011011001010111101001110010'
- '101001110101001001000110111111000101'
- '100011010000000001110100110100010110'
- '101000111101000100000101110011000110'
- '011110001101000111111001000101010110'
- '011000111111100100101011011010010000'
- '000001100111110010011111101010100001'
experiment: batch_run/rand_str_36_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
