ancilla_dim: 16
bitstrings:
- '0110110010100001011111000000101001001110100100010000'
- '1111110111110100000000000111111000101010110110010111'
- '0010001101010000110001001101001010010101101001011011'
- '1101001011010110010001011001010000010101001101100011'
- '0110011111000000011011111011111100100011110101000001'
- '0100100101010100001000011100100011011100010111001110'
- '1101010010100100110100111011000000000100100111010110'
- '0100110101001100100110111000100001001101010100011111'
- '1111110110111100010101000001101100001110101001101010'
- '1100111001111011111101100110110111000101001110111100'
- '1010001111100101001011010010010101011100000111011100'
experiment: batch_run/rand_str_52_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
