ancilla_dim: 16
bitstrings:
- '00111010100001100000010011111101110011101010'
- '00010111000010101010001010100111110101111011'
- '00110101101010111011010111001000011110001110'
- '11000001101111110000110010111101011000011111'
- '01101010000000110000001110110110011100110110'
- '01100000000101111100010111110011110100111100'
- '11100101001001011110000000100111000111100011'
- '00011111101110011111101111101101001010110010'
- '00101100010110111000110010011010110001000010'
- '10011010101001111111010110101000011011111011'
- '11010001110111111100101100010101110001000010'
- '10001110110001011010111101010000010011001000'
experiment: batch_run/rand_str_44_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
