ancilla_dim: 32
bitstrings:
- '1111010011000101101111100000011111101001000100101001001011000001'
- '0011001111110101001111010000000110010011111011111111100000101000'
- '1000000001110001100110011000111011001110011011111010111011111000'
- '0001111100011110101000100100001100100011000111000011001011011100'
- '1110000010001011010010000100001101010111010010000011000011010110'
- '0001011010100001011000110100111111100101000010100001101010101110'
- '0101001101010001010001011111111100011001011100011000000001011100'
- '0101110110000101001000101011110000111111011001011000001110000101'
- '1111010100100110001000111001100111111100101000001100011101010110'
- '1000100001100000010011011001011010111110000101010000111110011000'
- '0110011101100000110011010010111010101110100011000100011010101000'
- '0011010110101111100101101100110010010101010010011000100100111101'
- '0001010001100011011000001010011011011100000100100011101110110000'
- '0001110100010110001000001111111110010101100010001111101100110000'
- '1100111110101101110010011111010111011111011101001010100011111111'
- '1101110011000011111101101111000110001111000001000110111111010000'
- '1011110110001010110011010010001011110010110110110000110101000000'
- '0000101011100011100101110000111010001110110011100011001101110100'
- '1010111111000001000000000111110000111001001100011100011101100001'
- '1101001011010110111110110110111111001011110101000100101110010101'
- '1100000101000101101000010100010111011100100101010010101100000110'
- '0001110001101011100000011100001001001011000100110011001000101111'
experiment: batch_run/rand_str_64_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
