ancilla_dim: 2
bitstrings:
- '0011110100'
- '1100001001'
experiment: batch_run/rand_str_10_2_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
