ancilla_dim: 32
bitstrings:
- '0000010110100010101011110111110010101011000111000010'
- '0101001101111010011110111111000110101110010101100100'
- '1000100011100110101010110110000101001010100001101100'
- '0111000001110000110011100011001011110111011001101100'
- '1001001001100100101001000001101111101100100111011110'
- '0111101101101100011001100110111111110000010111000110'
- '0100011110100010100011111100011111110010101111110100'
- '1110011010011001011100011100001001110000011001101110'
- '1000101111101010001101000101101111000100110110110010'
- '0101001101010100001101110010110000010001000000101000'
- '1110010010000101010010000110010000011010010100100001'
- '1101110001100101000010000010111001000111001111110010'
- '0110010111011000100001011000000000100110010101100110'
- '0111011101100000110101000101011010110010001101010011'
- '0110101000111101000111011100010000110001000010001111'
- '1101110100001000011100101000100100100001000101001010'
- '1110011100100010111110111110110001011111100100000001'
- '0000110000000101011010110000100100010001111110101111'
- '0010100011101001101111111111110000100010111100001110'
- '0011010010001100001110011100100100101001001101011100'
- '1110101000010010000010110110100111001010111111100110'
- '1011101100101101001000001111010011100111110010110010'
- '0000111110011101000100011000010111001001100101101110'
experiment: batch_run/rand_str_52_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
