ancilla_dim: 8
bitstrings:
- '00010101000001010001001101000100010011000101010011100000'
- '00001101111011110001001100001010011111001111000100001110'
- '01111100111111110110001111111010001100001001010010111000'
- '00100100100011001110011110111011010100010101001111011000'
- '00010000000110111101101110100111010100100001101110011110'
- '01100001101101110110000101011000000000100011000110000001'
- '11101111111000011100101001111110000110111011011111010110'
- '11111101101110100010101010110101101000111101010010101101'
experiment: batch_run/rand_str_56_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
