ancilla_dim: 16
bitstrings:
- '01110011'
- '11110011'
- '10111110'
- '11000011'
- '11101010'
- '10101000'
- '01010000'
- '10100111'
- '01111111'
- '10101011'
- '00101111'
- '11111100'
- '01010111'
- '00000001'
experiment: batch_run/rand_str_8_14_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
