ancilla_dim: 4
bitstrings:
- '1110001110'
- '0100101010'
- '0000100010'
- '1100001010'
experiment: batch_run/rand_str_10_4_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
