ancilla_dim: 32
bitstrings:
- '01101001110110010111111010100111010101010010'
- '01010110100011010100001000110110000101110101'
- '00011001011100110110100110000001010111011101'
- '11101100010001010011001001111011101011001010'
- '01110101111100000010100101101000001110111111'
- '00110111111111110101100100110010000000100101'
- '10000101110100001000000010010100100011000111'
- '10000000000010010001110000111000011011000011'
- '11101010101001010110011000110101000011111000'
- '10110011110110111011010110011000010100011111'
- '00000100110000110011010110011000101101000011'
- '11010011110000011011011101111010101111011010'
- '01101001011110110111111011000101100011001010'
- '10010000100010111111100101000001100000010011'
- '01110100110111110010000000001100011101011001'
- '11101001010010010110110010001111110001000000'
- '11100000001000100011010011111010101011111000'
- '00111100010000101010111001111101101110011101'
- '10001001111101110101001001001010101010000000'
- '11000110000100100010001000101001100000010011'
- '01100100001010001100101011111000010001011110'
- '10000010110100110000010011101011101100110001'
experiment: batch_run/rand_str_44_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
