ancilla_dim: 4
bitstrings:
- '11111100000011010010101101101011'
- '00110100011111111111001010110110'
- '00001000001011111001101101111110'
experiment: batch_run/rand_str_32_3_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
