ancilla_dim: 32
bitstrings:
- '10111001011010110010001101101011000010011111100001001100101101111110'
- '11101000100100111100111000010111111000100110010001110101001110011010'
- '11000110111011101001001011101010111000011110000001110000000100110111'
- '10000100010111010110001110101011111010010000000111110110011110000010'
- '00001110010010101010111110000111000101011111000111011001011011011001'
- '10000110111100011100000011001001011111010110101111110010110101100100'
- '10100100011011100000011111011110000010011010010110000100101010101010'
- '10000001010000010011100000000110111001000011000101111000111100101110'
- '11110011101110110010011101110000111110101110110010110010110111001000'
- '00111110101111111100110000010000111111001110010011111101110011001110'
- '10001101010111111100100001101101011101110100000011101110001111100101'
- '00110100000001000111011011001000001010001100101100011100001011010101'
- '00111101101111101011101101011111100010010100001110100110001111000011'
- '10001111011011011110110100111010111110011000000010010011000000000001'
- '10011001001111010011011001100100111100100110000010000110100111001101'
- '00000001100000010111101110110000100000110010010000010000011000010100'
- '01011110111110001000100111011001010101011010011010001100000111011000'
- '01111110110100011101100110110011110110100101000100010010110111111011'
- '00000001010110101011100100000001100110110100110100100101111110101101'
- '00011011001110000001011000001101010101101101101101110111011000110101'
- '11001010000001111011001001101110011110001100100101100101111110101000'
- '11010111010111111111111011110101111000100001111011111100110101001011'
- '11010000001100000110110100100011001011110111110000001010000000110101'
- '10001011010011101010100101100111010001110100011000101000101111000001'
experiment: batch_run/rand_str_68_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
