ancilla_dim: 8
bitstrings:
- '1010110111010100001101101010011001110110'
- '1110111110001110000100101010010101010101'
- '1111100100111010001001000000011001110111'
- '0101110101100010000010110111001110010011'
- '1110010101010101011011000100111110111011'
- '1101110100010111101001101110000010101000'
- '0111100010100010000110001100000111001101'
- '0011011011001010010010100110110110011011'
experiment: batch_run/rand_str_40_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
