ancilla_dim: 1
bitstrings:
- '011001011101'
experiment: batch_run/rand_str_12_1_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 12
