ancilla_dim: 32
bitstrings:
- '0011111100110101000011000101101011000101000110100111110010010001'
- '0001110001011010000011010010100011001101101111011111001000000110'
- '0010011100101000000011000010110101101101011101110010100111110011'
- '1000100100010100010100010000000001100110001101011111001111001001'
- '0010101001110011101110100001011111010010111110011000000100010100'
- '0000010101111100001110101110111000101110000001100110111000100111'
- '1101101111111101101101111100011000101000110111110110101100010001'
- '0011110111101010001000110000100001010110001111001110111000101010'
- '1100011100111101000110101000001110101000100100110111000000100111'
- '0110001000010011010110011000000001011000111101110010101100000101'
- '1110111111100101111101010010100110111011110110101111111111000101'
- '0101111100001001110101010011110011001010011111111110110100100011'
- '1000001101100111111010000010011100101000011011110010101000110111'
- '0010000111011001000001011100110100101110110110001010000000110110'
- '1010111001100011110001000100110000010101101100110001011100011101'
- '0001010101100110010111000111010000010001101110001000101010101110'
- '0001010000101110001101001100110000000010110001010110100101110010'
- '1000000110001011111011000110000001101000101100001101101011101011'
- '1110000010110001111011010111111000100001001010110000000000010100'
- '1010100101110000101100011110011100001000011000101110111101110100'
- '1011111001001010010111110001010110000100011010110110110101101001'
- '1101010100101010100111101100101111100000100101101110101010000000'
- '0000100101010010110101011111001001010001010011001110101001100001'
- '1001000110010011001010010100011011000000001100111101001010110110'
- '1110011101111000101001010110101101101100011010011110111001110001'
- '0100101010100010110110100001000111111001111010111011100111011001'
- '0111000111011111011010000110110010001001001000000001101110011000'
- '0111011000101001111111101000111111111001001110111100100101001000'
- '1011111000011111101110100001110101110000000001110000101110100000'
- '1011010110100101011100100011111111011010100010100110011011001100'
experiment: batch_run/rand_str_64_30_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
