ancilla_dim: 8
bitstrings:
- '1001110001000010100101100000010000110111000001111010110000111011'
- '1010001110000010000110011000111101100001110010010110010000110001'
- '1110110010101110100000100110100111000001000000001110001001000100'
- '0011110001000010001001110111100101001101011000010100000100101010'
- '1001001001111100101110000111101000001001100101110010011000010111'
- '1001011001101001100111010110101001100111111010001111000000100101'
experiment: batch_run/rand_str_64_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
