ancilla_dim: 32
bitstrings:
- '00011100010000000101001101110001011100100001011101000101'
- '01001010101111101001010101011111111000001001100111111100'
- '11100000001000000101100111011110101001011000111100001001'
- '00101110100001011001000000100111100010100110101111110111'
- '11011101000100010111000000110000000110100010010100000001'
- '01110111010100000011011110111001101101110111000011010010'
- '10000010101110100110011011001011101011010110100101100010'
- '01000100100011111101100100110010110110011010010000010010'
- '01101011010010101111111001100011011100001010111111101011'
- '10001110010100001011110111011011000111100000001100010100'
- '10011111100110011100000100011011110111010111100111110000'
- '01100010111101000101001000001100101001101100011101001110'
- '11011101111011110101101010101110010011111011010001110010'
- '01110001110111100110101101010011111100111011101110010111'
- '00101001110101010111101101111001010001100101000111100111'
- '01010101100101101001001011000001011101100011111001111100'
- '01101110011010100000101001110011100000011100111011001101'
- '01000011010110000001000011010011111010001011100101010111'
- '10001001000101010111010000010010111110001011000000111011'
- '10110000001010100001110000100101010100100010011111111010'
- '11001010010100001111001100111110000001011011001100111110'
- '11011000101101100000010011110100101100000010100100001101'
- '11010011010111111101000011111100001011000110011110111100'
- '00100110011001100101100010010010010100100010110001100101'
- '00110101001011101101110010011000001000001000000101010001'
experiment: batch_run/rand_str_56_25_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
