ancilla_dim: 16
bitstrings:
- '11111111101001101001111001110101111000011110010100110110'
- '10001000010101011101100011010000101111110111101101110011'
- '01001100010100000111100000111011000011110100000101001101'
- '00010011001001111011101101011100110011101111110000011110'
- '11101101101100101101010011101011100100010101110000011001'
- '11001111111011000110000110101101110011100000100101011011'
- '01100100000100001111000010001010101100000010111100101010'
- '10110001000101010110101100000011110001111000010111000000'
- '10001010110000111100001011110111000000111000011001110001'
- '01011100111101100110010000110000101010110011110111110110'
- '01001101010001000100011101100110010000000010110101100110'
- '00010110010111000111101010001110110101011111110110000000'
- '00111011111010110010001111001101010000001000111000100101'
- '11101000110111001000110110000001010000010010100010110011'
- '01000101101010010101011001010110001011101000111001111011'
experiment: batch_run/rand_str_56_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
