ancilla_dim: 16
bitstrings:
- '1101000111111011100000101110110000011101010101000100101101001000'
- '0001011011111111011100000001110000011100000001011101001011101001'
- '1011111000100101110000101110000110110011111110001100000111011110'
- '0101001000101110000101000000100100111101010000110111001101011110'
- '0000100000000100101001111100011100001001011010001101000101011010'
- '0011111110101001001000111010000011111011101000110101111000011101'
- '1100100000100010100111000111111111000100111101110001010101101001'
- '0111101111110101111111111010110010101000010000101011001011011010'
- '0000110000011010010000010100010111000101111111000101001111011101'
- '0001011111101010011000100110111010011000011001010100000111010101'
- '0010101111100100001111000001000100011010110111110010101100011001'
- '0111100001001011110101010100110011110000010011011001010010011100'
- '1000000011001001100010001000010010101011100001100110011001111110'
- '0010010110110000011001110101110101000110101110110100001000101011'
- '1011000101101011010111010010001101000001101010001111101101100000'
experiment: batch_run/rand_str_64_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
