ancilla_dim: 512
bitstrings:
- '0110101110'
- '0010010101'
- '1000000111'
- '1000100100'
- '0001101101'
- '0000001110'
- '0100110000'
- '0010010000'
- '0110111101'
- '1101101100'
- '0111001110'
- '1101111110'
- '1110010001'
- '1010011001'
- '0010100010'
- '1110100001'
- '1100011011'
- '1001101100'
- '0101100100'
- '0011001101'
- '1101011100'
- '0000000100'
- '1110110111'
- '1110111100'
- '0001010110'
- '1110101100'
- '0010101011'
- '1011001101'
- '1100000100'
- '1111111010'
- '0010101010'
- '1111111100'
- '1111011110'
- '1100000000'
- '1010111001'
- '0110001011'
- '1011001010'
- '0011100001'
- '1101010111'
- '0011101101'
- '1000110001'
- '0011001100'
- '1001110000'
- '1111001000'
- '0101110000'
- '1001101010'
- '1001110010'
- '0000010110'
- '1111100100'
- '1101100001'
- '1000101100'
- '0101010000'
- '0001001010'
- '0011010001'
- '1011110100'
- '1011000010'
- '1011111111'
- '1100001001'
- '1000110101'
- '0001110011'
- '1100100010'
- '1100010000'
- '0010010100'
- '1010101111'
- '0111101100'
- '1111101110'
- '1001110100'
- '1010011101'
- '1111000101'
- '0100110010'
- '0110011001'
- '0010101111'
- '0111111000'
- '1101101000'
- '1001001101'
- '0001100011'
- '1101010110'
- '1011011100'
- '1101000110'
- '1010101101'
- '1100001111'
- '0101100001'
- '1011101101'
- '1100100001'
- '1001110001'
- '0000011110'
- '0100100001'
- '1010110111'
- '0111110100'
- '0110101001'
- '1111010001'
- '0110101011'
- '1100100000'
- '1001100011'
- '0101000101'
- '0001011101'
- '0110101010'
- '0100000010'
- '0110011101'
- '1010010111'
- '1010111111'
- '1000001110'
- '0100001000'
- '0010110100'
- '1101110100'
- '1110110101'
- '0001001111'
- '0010000101'
- '1111000010'
- '1000111011'
- '0110110110'
- '1000100010'
- '0110111000'
- '0111011101'
- '0000110111'
- '0101110001'
- '1110010010'
- '0010011010'
- '0111100000'
- '1010111011'
- '0000010001'
- '0101101101'
- '1010101100'
- '1000011001'
- '1111001101'
- '1000000000'
- '0010101110'
- '0110011111'
- '1111110100'
- '0110010111'
- '0011010010'
- '0011110010'
- '1010101000'
- '0111000101'
- '1101000111'
- '1111011101'
- '0111100001'
- '0100001001'
- '1101110110'
- '1111010100'
- '0000101110'
- '0011101000'
- '0101101011'
- '0100101110'
- '0010000010'
- '0111100110'
- '1001001001'
- '1000110011'
- '1110011000'
- '1110000000'
- '0101111011'
- '1011011110'
- '1100100100'
- '0100101111'
- '1111001010'
- '1111011010'
- '0001111001'
- '1001001010'
- '0101001101'
- '1110011110'
- '1010011000'
- '0100111111'
- '1111101101'
- '0010101101'
- '0100010101'
- '1010010011'
- '0010011111'
- '1011111100'
- '0101111100'
- '0000100111'
- '1110110010'
- '1100111100'
- '1110110000'
- '1110001101'
- '1001110101'
- '1100010101'
- '1000011101'
- '1000100000'
- '0011010000'
- '1110011011'
- '1010011010'
- '1111011000'
- '0000111010'
- '1110000111'
- '0010010010'
- '1011000101'
- '0111001000'
- '0010111000'
- '1101110010'
- '0001000000'
- '1001011000'
- '1100100111'
- '0001001110'
- '0000000001'
- '1011111010'
- '1001000100'
- '1100001000'
- '0110111010'
- '1101011000'
- '1111111001'
- '0101110110'
- '0011011001'
- '1000001011'
- '1101001100'
- '0111010010'
- '1000100110'
- '1000101111'
- '1101001101'
- '1110110100'
- '0100001010'
- '1001111100'
- '1111010000'
- '1111010011'
- '1011110011'
- '1001011100'
- '0101110111'
- '0011011101'
- '0000100010'
- '0001111011'
- '1011010011'
- '1100101101'
- '1100001010'
- '0010000111'
- '0001101100'
- '1001111000'
- '1001000011'
- '1011000011'
- '1001000110'
- '0100001101'
- '0011111101'
- '0111111111'
- '0101111001'
- '1111001111'
- '1011110000'
- '1100001110'
- '0011110110'
- '1110000101'
- '1100011111'
- '0111101010'
- '1011111001'
- '1000100111'
- '1101110001'
- '0111000000'
- '1000001001'
- '0000101100'
- '0101100111'
- '1000010100'
- '0001110001'
- '1110010011'
- '1111011001'
- '0110001001'
- '1010110000'
- '1110010101'
- '0111010110'
- '0111111110'
- '1100110010'
- '1110111010'
- '1100010011'
- '1000100101'
- '0010010011'
- '1010000100'
- '1010100010'
- '0101101110'
- '0000100001'
- '0100001110'
- '0111000111'
- '1011100110'
- '1110001000'
- '0010111110'
- '1010011100'
- '1100110011'
- '1100010001'
- '0011010100'
- '0101110101'
- '0110111100'
- '0000001001'
- '1110011101'
- '1111101011'
- '0000111011'
- '0011100111'
- '1100010010'
- '0000101111'
- '0011010011'
- '0010110010'
- '0100010110'
- '0111101001'
- '1011010000'
- '1010010110'
- '1100100110'
- '1011100101'
- '0001111010'
- '1000010011'
- '0101101000'
- '0110011110'
- '0101010111'
- '1011111011'
- '1101011010'
- '1001111001'
- '1111010101'
- '0000110101'
- '1111110101'
- '0010011011'
- '1011100000'
- '0100011010'
- '1010000011'
- '0111010011'
- '1000010010'
- '1010100011'
- '0110100101'
- '0110111011'
- '1010001101'
- '1100010100'
- '1101011111'
- '1000111111'
- '1100110111'
- '0011000101'
- '0011010101'
- '0011110001'
- '1100101110'
- '0000001011'
- '0001100101'
- '1011100011'
- '1001011010'
- '1101000101'
- '0100101101'
- '0111010101'
- '0101001000'
- '1100101000'
- '1100000011'
- '0001010101'
- '1011010100'
- '1101011110'
- '0111010100'
- '1101000000'
- '1001010011'
- '0110010110'
- '1111101000'
- '0010000110'
- '0011101100'
- '1101101101'
- '0000010000'
- '1011100111'
- '0001011010'
- '0001100001'
- '0010110000'
- '1000110100'
- '0101001111'
- '0001100100'
- '1011101111'
- '0001011011'
- '0001111100'
- '1001011011'
- '1110010110'
- '1111100000'
- '0100011110'
- '0111111100'
- '0110110100'
- '0100001100'
- '0100010011'
- '1011000100'
- '0011101011'
- '1111110010'
- '1111110001'
- '1110111110'
- '1100001101'
- '1000111110'
- '1011011001'
- '0100100000'
- '1001001110'
- '0111110011'
- '0001111111'
- '0001101001'
- '1001101111'
- '1010001110'
- '1110000110'
- '0011001001'
- '0010010110'
- '0011100010'
- '0011111011'
- '1010000000'
- '0100010100'
- '1111111111'
- '1010100100'
- '0010000100'
- '0000100100'
- '0010001001'
- '1000010110'
- '0111000110'
- '1011111000'
- '0101100011'
- '1011001001'
- '1110000010'
- '0011101010'
- '0100001111'
- '0100000110'
- '1010110010'
- '0010001101'
- '0010100100'
- '0110000010'
- '0001000011'
- '0111001100'
- '1000010001'
- '0001010001'
- '0001110111'
- '0000100110'
- '1101111101'
- '0000000110'
- '0101111110'
- '0000001111'
- '1100101001'
- '0100100111'
- '0001100010'
- '1001000001'
- '0111001111'
- '1111101111'
- '1011001110'
- '1010011011'
- '1001101001'
- '0110001101'
- '0110111001'
- '1110100110'
- '1001110110'
- '1000011000'
- '1101001010'
- '1111001001'
- '1011110001'
- '0110110101'
- '1111110111'
- '0110001100'
- '0110100110'
- '1101101011'
- '1101010001'
- '0010010001'
- '0000101101'
- '1110010100'
- '1101101111'
- '0001111000'
- '1101110111'
- '1110100010'
- '0001001001'
- '0001010011'
- '1101010101'
- '1010010010'
- '0011101001'
- '1111100101'
- '0110110111'
- '1100111000'
- '0000111100'
- '0110100001'
- '0110101111'
- '1010110001'
- '1100000010'
- '0011100101'
- '0011100110'
- '0111111001'
- '0011011100'
- '1001011101'
- '0100101100'
- '1111111000'
- '0111110001'
- '0001111101'
- '0001010111'
- '0000001010'
- '1101010011'
- '0010110110'
- '0100111100'
- '0100111010'
- '0001001101'
- '1000001010'
- '0010100111'
- '1000000011'
- '0110000000'
- '0010011001'
- '1110001110'
- '1001000010'
- '0111110110'
- '1011000111'
- '1010001000'
- '1111110110'
- '1110101000'
- '1000101000'
- '0101000010'
- '0111101101'
- '0010101100'
- '0111110010'
- '1010000101'
- '0110110000'
- '0110101101'
- '1110001001'
- '1111110000'
- '1101100010'
- '0111011000'
- '1101111100'
- '1010001001'
- '0010001000'
- '0000110100'
- '1001010000'
experiment: batch_run/rand_str_10_497_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
