ancilla_dim: 512
bitstrings:
- '11101010001111011110'
- '01000101110011111111'
- '11110010101100111011'
- '01011100011001001010'
- '10111011110011010010'
- '00111000111011001011'
- '10001000000100101111'
- '00100101000110111010'
- '11010111101000111101'
- '10100000100111100100'
- '10110001010100001100'
- '00011101110011010101'
- '10100100111010101010'
- '10001011101101100000'
- '11011111110101100111'
- '00010101010011111011'
- '11101100111110000100'
- '11010110100000001110'
- '01011101100110100111'
- '00111101110011110010'
- '10010011001010000100'
- '11100110100001101100'
- '00010000010010111110'
- '11110000000011010100'
- '10100110001101011111'
- '11011111001111101001'
- '10000111000110000110'
- '11011001000101000000'
- '11000110100100111101'
- '00010110101101101001'
- '01100001001000101001'
- '11001111001111011000'
- '01011011001010100010'
- '00011000010110010100'
- '11101011111110110010'
- '00101000001101011011'
- '01011010000010000010'
- '11000100101011111111'
- '00100001100010001010'
- '01100001000110101011'
- '00111000100110010101'
- '10010111100100100011'
- '00101100010111101111'
- '01100010101100111100'
- '11110110000010100111'
- '01111110010100010110'
- '00110011111101110100'
- '11101000110001100100'
- '10101100010101100010'
- '00111111111110001000'
- '00001101001100111101'
- '10011101010000001110'
- '01111101010001001000'
- '11101000101001101110'
- '01110000111000010110'
- '10111001011110001000'
- '11101000000010110011'
- '01011011001110000001'
- '10101001110100010001'
- '11010101000101100101'
- '01100001000011100110'
- '01001001000101111010'
- '01100000000010011110'
- '10001001111111000011'
- '00111011000010000011'
- '10010011011110111000'
- '11001110111101110010'
- '01000011010110110111'
- '10110010011000000110'
- '00000100011000110110'
- '01110111100111110001'
- '11111100100110100111'
- '01111000111110010011'
- '10100001001111000000'
- '11110010011001100001'
- '00010001110100101100'
- '11000110001101000101'
- '11111011011000011111'
- '11010010111101010101'
- '00110011111010101100'
- '01010110001101100100'
- '01000110011010101101'
- '01101000101010110100'
- '00001000111000011000'
- '10010011100001000100'
- '00110000101001101101'
- '11100100110100001010'
- '00011110001100100111'
- '11011110111010100000'
- '00111111010111101000'
- '11111010100100100110'
- '11010111100001000110'
- '11001110100111101101'
- '01100111110101010111'
- '01110001010011000001'
- '10000110000100110100'
- '01111110101101111110'
- '10001000101000011001'
- '10000111101100100001'
- '11001011000000010111'
- '11101101000111011010'
- '10101101010101110000'
- '01100001000100100111'
- '11000000001000011100'
- '11011011000100010010'
- '01001110011010101100'
- '01110000101000011110'
- '11111010001100011110'
- '10011111111010011101'
- '00011001100100100001'
- '01010011011100001000'
- '00001100100010100001'
- '11011110000000000011'
- '01001010101001011001'
- '01100001111010111110'
- '00110101110101010110'
- '00110000011100001100'
- '01011110001010101001'
- '11110000111000010001'
- '10101110001011111011'
- '01010110111010000111'
- '10110000011011010001'
- '11110011010010001111'
- '01010110011010101001'
- '10010100001110010110'
- '11101101011010111001'
- '10001011010001100111'
- '11000101001110101000'
- '01010100001001000010'
- '11011010100010010010'
- '01001111110001011100'
- '10011001111101111011'
- '10101010000001110001'
- '10110000100111110110'
- '11111001110110110011'
- '11101100000011001110'
- '11011011100001100111'
- '11001010000100111010'
- '11010001000100010000'
- '00111110010111001111'
- '01110100101011000000'
- '10111111000100110100'
- '11101111011100110000'
- '01011000011010101011'
- '01100101100010110011'
- '01001011011011000111'
- '00110011111010101101'
- '10101111001001110010'
- '11100000011111111110'
- '00000011001101110000'
- '11010001000101010101'
- '11101001010010101101'
- '10111101001011010001'
- '11001101101110011010'
- '01110001000101100010'
- '00011100101111000011'
- '10011011101001011111'
- '00000101011110100101'
- '00100110011111110000'
- '00001101100010010000'
- '11011110010000011000'
- '11011000000110000111'
- '10001111101001100101'
- '11101001011111101001'
- '00010110011010110010'
- '10010111110000110111'
- '10001111011011101101'
- '10101001010000101111'
- '01100110010111111001'
- '00110110011110011110'
- '10111010001011001101'
- '01111110110101101101'
- '11000100000000010001'
- '01000101110100000110'
- '01011110100000001000'
- '01111010100001001110'
- '11000100001010010011'
- '10110000110110010110'
- '10100100100111101110'
- '11111001000001001100'
- '01000101000010011111'
- '11100101111010101111'
- '10001100011100000101'
- '10110011000111101001'
- '01101101001111011010'
- '10111101110000010110'
- '01001001011010011110'
- '11110001110111010101'
- '01100001110110111101'
- '10001110010101000001'
- '00001011111011000111'
- '11101111101100011111'
- '00001101111011101010'
- '00010110100010001100'
- '01100000101010000101'
- '01001010001101000001'
- '01011111000000100000'
- '11100110011110110011'
- '10011011010110001010'
- '00000111011101011101'
- '10110000100110111100'
- '01111010011100001010'
- '00100100010000100101'
- '11110111001100011111'
- '11001110101111010101'
- '00101100110111100011'
- '01001010101001101011'
- '00001100000110111110'
- '01111110100011101010'
- '00000010110111010110'
- '01111000101000110010'
- '00010010010000110010'
- '01111000101000111000'
- '01010111101101011000'
- '11100000010011010000'
- '11010000110011010001'
- '00011010000101010010'
- '11111111101010111001'
- '01011010010100010000'
- '01010101011001110010'
- '00011010011111110000'
- '00000110111011110010'
- '11010101010000001110'
- '11111100010011101110'
- '11100100100011101010'
- '11001011110101111101'
- '10000111011011000000'
- '10000011000011000000'
- '11000000111000101100'
- '11010000100010011010'
- '11100000011111000011'
- '10101001111100111101'
- '01000101010001110010'
- '11100110011101111100'
- '11100011110111100111'
- '11000001110011101111'
- '11011100001010010111'
- '00101011110111110110'
- '10101000100110011111'
- '11011000110001100111'
- '11110110101110011001'
- '00010000110010101001'
- '01101010010110001010'
- '00000101111010101111'
- '00110100001001001110'
- '11001011001001111110'
- '10110100111111011111'
- '01000111010101110110'
- '01101100101001001101'
- '00100001011011000011'
- '01110111100010100111'
- '00101101000000101111'
- '01110100100100100011'
- '10000110000111000100'
- '11000001010011001010'
- '01011000101011010100'
- '01110101100101011010'
- '11010011101101011101'
- '10000001111110101110'
- '01101011011001010001'
- '11110100110111110100'
- '11101100100110100001'
- '00010100000110101100'
- '10101000100111001001'
- '11111000001111111001'
- '11011011110001101010'
- '10010101111011111001'
- '01010110111010001101'
- '10000001010101010001'
- '11011011110111010001'
- '10100100011000000111'
- '11000111100001111100'
- '01011100110000110111'
- '01000101100011110111'
- '01001111010100000101'
- '10001000110010001101'
- '11110011101010101001'
- '00000110101100011001'
- '01111011100101100000'
- '01010010101010011100'
- '10101110000000011001'
- '11010100011011110010'
- '10001001101110001001'
- '01100111110101110010'
- '00101111010111001000'
- '10001100001111010011'
- '11011001011100000110'
- '00011111010010010100'
- '01010011001101110100'
- '10101111001101110010'
- '10010011100110101100'
- '10110000010001001111'
- '10101110001111001001'
- '00001011001001110100'
- '01000001000101111111'
- '10101011111010001101'
- '01001110100111111000'
- '10010101010011110111'
- '11000100011101000000'
- '00101000100001110100'
- '10011111010110111010'
- '11111000110001011010'
- '01110100000110101100'
- '01011100000111000100'
- '00010010010011101011'
- '01100000010111000100'
- '01001001001111000110'
- '11011011000111001011'
- '00111001010000110100'
- '11101111111110011011'
- '00100001100011100011'
- '00100101110110110100'
- '11101000110000101000'
- '11011001111011110110'
- '00100000111010010111'
- '01101010000110001011'
- '11101111011101011011'
- '10101101110000001111'
- '01001100100000110001'
- '01001101100001011010'
- '10001001100101001000'
- '00000000001110001111'
- '01010111011100010010'
- '01010101111110010000'
- '10010001111010101111'
- '10010001110001100011'
- '00101010101011100001'
- '10101110000101011100'
- '01100100100110010111'
- '00101001100011110000'
- '10000000001101001101'
- '10000000011110010011'
- '00001001011110101100'
- '10101001000001010000'
- '10000101001110101010'
- '11110111000000000010'
- '01011110010110001011'
- '01011111111100110010'
- '00001011110001000101'
- '01100010110101000011'
- '00001101010000101001'
- '10011110011000101111'
- '11100110011100000000'
- '01110111010111111011'
- '01010001110110000111'
- '10110100001100000001'
- '01010011011101111101'
- '00100110111111100111'
- '11001110101011000011'
- '10000110000011000000'
- '11001010101111101000'
- '11000011110100000111'
- '00111100111000100010'
- '00000010110110001101'
- '01111000100111010111'
- '11011111001100101110'
- '10000001000001011001'
- '01110111010110000100'
- '01100000101011000010'
- '01010011000111110100'
- '10011000110110111101'
- '11100011010000010000'
- '11000111111110110001'
- '00000010001111011111'
- '10111110100101100010'
- '10000001011001100110'
- '11100011011100001100'
- '10000000100101001110'
- '10111001110111111110'
- '00011110110111001101'
- '10011100110111011100'
- '00110111001111000001'
- '00100011101101111010'
- '00110101110100010001'
- '11010100110100100101'
- '00001000001011010010'
- '11111110011010010001'
- '10100000010010100010'
- '00001010110100010101'
- '10101010111010100111'
- '00100110010110001101'
- '01010011011010010101'
- '01011100001001110100'
- '00000011011110000000'
- '10110010110101111110'
- '01010000100111000100'
- '10010000010010001111'
- '00101010001000100101'
- '01000111010101011100'
- '10000111111110100001'
experiment: batch_run/rand_str_20_390_comp
input_type: bitstring_list
methods:
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 20
