ancilla_dim: 32
bitstrings:
- '0010001111100110011101110001101100011000011100111011000010010100'
- '0101111000001000000100010100101001111000000100111110001111010111'
- '0000110101111101000110010110010000111011000101000010110000000101'
- '1010111011110111011011110000111011011000010110000000101000001111'
- '0000000110011011011011111100000000110001110101111001010100011100'
- '0011010000000000111001101000011100010111010110001011000100011110'
- '0110001001001110100011101100111000010010110110101010011111010011'
- '1011000010100000010000000010011001110111100100110111110111100011'
- '0100110110001101101000101101000110011001001111000011001011111110'
- '1001001111010101011001001111010010110001100100110001100011110011'
- '0111100000110111000000101110101100111001010000100101100001111100'
- '0000101011110000001011010010000101110101000110001110100101010011'
- '0010000110000100011001010110111000101110001111011100101111100010'
- '0001110111011100100010000001110001001010111100001101110001010111'
- '1011110001011011011111100010110000000101001011101011100011011101'
- '0100111011110111011111110100001000001000100011001110100111110110'
- '1010001010000111001001111000010100011110110110110111010111111001'
experiment: batch_run/rand_str_64_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
