ancilla_dim: 32
bitstrings:
- '10000010101110001010110111101001000111000101110100001001'
- '00000101101111000111110100101101101100110111011110000101'
- '01001101011100000000100010101000110101010001100101101111'
- '11111110011000011111110010010110001100000011101100101100'
- '11000001011110001001101110011001111001011100111100111011'
- '01001001000011000001000011000100000111010010010100101011'
- '00001001101110000000011101111101001110100100000110000110'
- '00100110011001111010001010101000100111011000110001111101'
- '01111111111110010111000110111000011000010000101111111010'
- '10110110100011001000100000100001110001011100101000111111'
- '00000011000010100101000011001101001010001011101111011100'
- '10101110101000101100100110110011010110010110000100110110'
- '10000001110110100101110000011101010010000111101110101001'
- '00110101011001101011100110111010000010101010011101101101'
- '00000100100111000110000000000011100010101011001010101011'
- '00100000101110101100110001100000111101001100011101011011'
- '11001000001011100011100011010111011100000111001001001110'
- '00010101001000100100001110001110110101101011001001100000'
experiment: batch_run/rand_str_56_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
