ancilla_dim: 16
bitstrings:
- '110001101100010001011100101101111100010000010011101000000101'
- '100011000101010010011100010100000100011111001101010011011101'
- '010010101001011111000011011011100100110000001111111001000110'
- '010111101110110000111011000000101011101011001000111010111110'
- '011011011011000000011001101000100100000110111011111110111100'
- '010101001010011111111001010011001010001111111011111110000110'
- '111111001000110111011110100011001110011011011100010011010111'
- '011100111000010011111001000010000000000111000110011111001110'
- '001100010111111101111100101011101101001110111000001100010101'
- '001111011101100110001010011000001000010100010010000000010101'
- '100011011110100111111001001011011000011010110011011011011111'
- '010101100110011110011010110011111110010110110010001101110001'
- '110011111101001001001011110110111111001010011101001011001000'
- '001010000010000110010001110100100010001010010011111000101011'
- '001001001110101110100101010110110011011010010100100001011110'
experiment: batch_run/rand_str_60_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
