ancilla_dim: 32
bitstrings:
- '00111010001111110100111010111011100011000000110011100111'
- '00011010110100100000001110111010011010100010000110001110'
- '11011000111101001100111011000100111111001000111100001001'
- '11100010110110101000010001010101010100110111001100001001'
- '00100000100111000100111011111001000010001010110111111010'
- '01111100111110101001100111000111011000001001001010101001'
- '01110100111001100110011110000111001100001001101001001111'
- '00000010001011010111101111000111010111111101010010101101'
- '10110110000001011000110111100010110001110100111101111010'
- '10100001011000001111100100110100111110110110011011011011'
- '00000100111111010100100110100110111101001100000011111000'
- '10101011011001100010111000010110111011100011100011110111'
- '00000000011000111111000100010101001101001111100110000001'
- '11110111111000100111010010110011101010001001101111101101'
- '10100100111000001001001011010000010110110011010100110101'
- '11000010101100110010110101000011101000001101011010011010'
- '11110101111001111111001010010100000001110011011001110000'
- '01010010011000100111000101001101000010100100111010100100'
- '01100001111000000001101110110010011001000110010100001100'
- '11101100101010100101010000000100111100101010101101000001'
- '01111000101110000110110100010011100001010000010000001000'
- '01001001010011001101011011000101001010001011010011110000'
- '01000101110110001010100000010110011100011101000111011111'
experiment: batch_run/rand_str_56_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
