ancilla_dim: 16
bitstrings:
- '01001100010010010010001001010011'
- '10010111000110011111110000000001'
- '10111010111100011111000111001000'
- '11110100011000000101110001010010'
- '11111101101000001010100000000001'
- '11011001001110000011110000010010'
- '01110101111101011000100001101110'
- '01100001001011111000011000011110'
- '10111000010010100010000111001011'
- '10100001110011100010010010010010'
- '00000111000011000111011001100111'
- '01100000011011001000100001111110'
- '10010011101101000100000110100100'
- '00100001110000100111010001111010'
- '11111010101111011101001111100101'
- '00101111100111011110111011100001'
experiment: batch_run/rand_str_32_16_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
