ancilla_dim: 16
bitstrings:
- '110000011000010101010000111111001010110101000111001010010110010101110111'
- '111010010000110011111101101111011011111011000000001011001010000000000100'
- '110000101100000000110000101101101111101010100001101100010010001010001001'
- '010100101110001100111101000000111101101111101010001110101101001110111100'
- '011011100110011001001001111110000101100010110110000011111011110010000010'
- '001100101001010101111100101010100100111101011110000111111110110101000010'
- '100001010110110111011011111010110011010101001010000001000011001011010101'
- '010111011000101010000110111001100101110110010011110010100010111010110001'
- '100110011001111101011010110101011011111010110110110111110101000101011100'
experiment: batch_run/rand_str_72_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
