ancilla_dim: 512
bitstrings:
- '1010101100'
- '1100111000'
- '1010011001'
- '1001110101'
- '0111101001'
- '0001111001'
- '1101000001'
- '1010000110'
- '1110100110'
- '0000110000'
- '1101111110'
- '0000111010'
- '1000100010'
- '0001000011'
- '1111001001'
- '1011110111'
- '0110100100'
- '0000100001'
- '0100111010'
- '0000111101'
- '1100101011'
- '0000101110'
- '1101111010'
- '0000111001'
- '0011110001'
- '0000100100'
- '0011000011'
- '0011111101'
- '0110100011'
- '1001100000'
- '0110000101'
- '1011010000'
- '1010101111'
- '0100011001'
- '1001100010'
- '0101100000'
- '0011000100'
- '1000110110'
- '0110011100'
- '1000111011'
- '1101101000'
- '1010110100'
- '0100100100'
- '1010001100'
- '0001110011'
- '0001101011'
- '1110110010'
- '0011111010'
- '1011011000'
- '1010010001'
- '0010011011'
- '0000001001'
- '0110001010'
- '0110101110'
- '1110101000'
- '0011010011'
- '1100011010'
- '0111111101'
- '1011000001'
- '1001001001'
- '0010001110'
- '0100110011'
- '1100000001'
- '0111110111'
- '0000010010'
- '0101100011'
- '1111000100'
- '1011001100'
- '1111000111'
- '1110010110'
- '1100110110'
- '0101110100'
- '1001111101'
- '1000000100'
- '0100010001'
- '0000001010'
- '0111111111'
- '1101110111'
- '0101011100'
- '1011111000'
- '1000110001'
- '1000000110'
- '1011000010'
- '1110001101'
- '1111011001'
- '0111011000'
- '1110000011'
- '1110100011'
- '1101000000'
- '1111000010'
- '0000101010'
- '1010001111'
- '0110001000'
- '1101110001'
- '1001001110'
- '1010111010'
- '1001011100'
- '1010010011'
- '1011001110'
- '1000011010'
- '1101010011'
- '0101110011'
- '0110011010'
- '1110110011'
- '0010000000'
- '1011100011'
- '1010000011'
- '1110011100'
- '0000011001'
- '0110110111'
- '0000000010'
- '1100111010'
- '0000110110'
- '1100000101'
- '0001000000'
- '1110001001'
- '1100100000'
- '1010010111'
- '1110011000'
- '1110101100'
- '1010000100'
- '0101110001'
- '0101010101'
- '1010010100'
- '1111010110'
- '0110001110'
- '1111111101'
- '1001101101'
- '1000000011'
- '0011111000'
- '1001000010'
- '0111011100'
- '0110111000'
- '0001100001'
- '0100101000'
- '1100110001'
- '0100011011'
- '0110011011'
- '1110101111'
- '1011001010'
- '1101011000'
- '1101011010'
- '1010110111'
- '0100010000'
- '1110011101'
- '1011010110'
- '0001010011'
- '1101001001'
- '1111001010'
- '1000011011'
- '0101011010'
- '1010000101'
- '1110010101'
- '0001010101'
- '1101101110'
- '1111000011'
- '0101000011'
- '1000100101'
- '0100100101'
- '0100010110'
- '0001011100'
- '0100010100'
- '1001000111'
- '0111000101'
- '0111001111'
- '1111011000'
- '0000011011'
- '0100111110'
- '1110000001'
- '1101010010'
- '1101100101'
- '1110001110'
- '0010010111'
- '1011111111'
- '0101101011'
- '0111100001'
- '0001011001'
- '0011101100'
- '1100110101'
- '0111111010'
- '1010000001'
- '1000001001'
- '1101000100'
- '0101101010'
- '0110110011'
- '0001001000'
- '1010111000'
- '1110100101'
- '0011001001'
- '0011011101'
- '0101101111'
- '0111010101'
- '1110010000'
- '1001100100'
- '1000011111'
- '1100111111'
- '0101111111'
- '0101110101'
- '0010101111'
- '0101001111'
- '1011101011'
- '0000000001'
- '0000110001'
- '0111110001'
- '1101010110'
- '1111011111'
- '0110000001'
- '1010100001'
- '1010110110'
- '1001100001'
- '1001010101'
- '1100101111'
- '0010110110'
- '0100001111'
- '1110111100'
- '1110001000'
- '1110010111'
- '1110010100'
- '0100101111'
- '1100100001'
- '0000001110'
- '0001010111'
- '1101101011'
- '0000111100'
- '1100101110'
- '0011100000'
- '1101000010'
- '0111010011'
- '0011001000'
- '0111011001'
- '0110101101'
- '0111110000'
- '1000001100'
- '0110100111'
- '0111000010'
- '0001111000'
- '0010100100'
- '0111111011'
- '1001000000'
- '0000100011'
- '1110111001'
- '0110010001'
- '1010011111'
- '1000100111'
- '1110000010'
- '0010011111'
- '1011110110'
- '0100000000'
- '1110100000'
- '1100010110'
- '1010001000'
- '0110100010'
- '0000000011'
- '0101011101'
- '0100001010'
- '1100101000'
- '1110111011'
- '1010110101'
- '0101111101'
- '1000111111'
- '0011001010'
- '1000010000'
- '1010011110'
- '1111110111'
- '0111001000'
- '1011110001'
- '0001101110'
- '1010111100'
- '0001110000'
- '0110011110'
- '1011110000'
- '1001010011'
- '0010111111'
- '0001000110'
- '0000111110'
- '0010011101'
- '1011000000'
- '0001001011'
- '1110111010'
- '0011111001'
- '1101000101'
- '0100010011'
- '1100010010'
- '0000101011'
- '0100110111'
- '1011010101'
- '1100000100'
- '0111010110'
- '0010010110'
- '0010010000'
- '0111000011'
- '1101101101'
- '0001000001'
- '0001011110'
- '0010010101'
- '0011101001'
- '1101101010'
- '0101010011'
- '0101101110'
- '1110101001'
- '1101111111'
- '1111010011'
- '0110011001'
- '0000011000'
- '1010011000'
- '0100011010'
- '0011101110'
- '0000000111'
- '1010101001'
- '1111000110'
- '0000001011'
- '1111111001'
- '0000010111'
- '0111111001'
- '1010111011'
- '1000100011'
- '1000000010'
- '0100000111'
- '1101100011'
- '1111001101'
- '1101101111'
- '0010011010'
- '0000000000'
- '1001010010'
- '0000100000'
- '0100001101'
- '1110111000'
- '0111011110'
- '1111011010'
- '1001110001'
- '0100000011'
- '1111101100'
- '1101011011'
- '0000011111'
- '0010011000'
- '0101011110'
- '0010111101'
- '0000010110'
- '1000111001'
- '1110101110'
- '0100111001'
- '0110010110'
- '0001110110'
- '0100101101'
- '1001011110'
- '1011000110'
- '1000110010'
- '1011010111'
- '1001000011'
- '1101001100'
- '0010100010'
- '0111010100'
- '1110101010'
- '0011110110'
- '1111010100'
- '0100100001'
- '0001100010'
- '0111000001'
- '0101011111'
- '0000000101'
- '1011011011'
- '1100001001'
- '0100110001'
- '1001101110'
- '1000111000'
- '0001101001'
- '0100010111'
- '1011010011'
- '0111101101'
- '0110101011'
- '1011001000'
- '0111011111'
- '1110001011'
- '1100011101'
- '1110100100'
- '0111100111'
- '0110010111'
- '0101100010'
- '1011100000'
- '1100100110'
- '1000101111'
- '1101111011'
- '1111110110'
- '0101001010'
- '0011111100'
- '1000001110'
- '0011010010'
- '1010100110'
- '0100000110'
- '0111001100'
experiment: batch_run/rand_str_10_390_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
