ancilla_dim: 16
bitstrings:
- '110000101111111111100101101001101001'
- '101110011100001110011110101000111100'
- '001101001100101101101001111101101110'
- '011011100110000001010011000100010111'
- '010010001110100100100101101010001010'
- '010000100111101100100011110111001110'
- '010111100010111101111011111100100110'
- '100001010010101001110011001111111000'
- '110101001011110100100100111000111011'
- '100001101001001010110100101011111011'
experiment: batch_run/rand_str_36_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
