ancilla_dim: 1
bitstrings:
- '00101001'
experiment: batch_run/rand_str_8_1_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
