ancilla_dim: 8
bitstrings:
- '10011101'
- '10011110'
- '01001011'
- '01111111'
- '11100001'
- '01100001'
- '10100000'
experiment: batch_run/rand_str_8_7_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
