ancilla_dim: 32
bitstrings:
- '00010101101001111001111010110011000110101000011001011011100110100111'
- '00011110101101010010101011101010111000110000000011101011101100110101'
- '10001100110001110110111101111001100011000111001000101000101100100000'
- '11000110100100100100001011011010101110111001000111110101011001001111'
- '00111100010000001011011110100011101011100111101011110100111110111100'
- '11100101011100010110010010110101100100000101101001000010001011001010'
- '10000100011011010100010001011001000011101100111100110100001101010011'
- '11100100000101110101010000101010010010101010100100000011101001000000'
- '01101001100010110101001001100000001010100010001100100100100101110110'
- '11111001111111110011101010111000001001011011001000010010010001111110'
- '10001110100111000010010011011010110010010001100101010101111100101110'
- '11000101001011110001001110110001011001010101010100101001010101000101'
- '00100101111111001110101101000110110110111001000101001101110001111011'
- '01110110110110001110011100110011001011000110100011110000101000000011'
- '11111000100111100111110110110111111111001110100101010011111111010110'
- '01100000000000101101101101001000110110011001011000000101000100010100'
- '01001110010100101011111010100110110110001001111100001101110101100001'
- '00110111010001000010011001010101001111100001101010100011110010001111'
- '11001001000111001011110000100011101110100100001100010101101100001000'
- '00011001011010100111010100101000001110000100000000101000111111100000'
experiment: batch_run/rand_str_68_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
