ancilla_dim: 16
bitstrings:
- '0011011111101001100010110010010100011100101101110111101000010101'
- '1110111001010101101000010101100111110011011000100110100111101111'
- '0100010010110101010101110101000101101001000110000000110111001010'
- '1000010010110011101110011110100011110011010111010011011100100110'
- '0000010101111100100101011100010010111010110011101110101110011011'
- '0000001100101111010111111110011101111110001010110001010010110100'
- '0111101001111110101111101001000000111111010110101001110101011010'
- '1100010101111000100011001010000001111011101110100100111010111111'
- '0100001000101111010011101000000101100011001101010000001111000010'
- '1010101010011001110110111000110010110010111001010011101101111111'
- '1000101101000101010000001100110001110010011001001110100110101100'
- '0110011111001010000101011000010001010100101011110000001001100000'
- '1000111100111010100110101000010111110001101001101111111110000100'
- '0001001100001011111001000011101110011110000100010100010110100001'
- '1100010110110111101101111000011011111000001011000111110101000010'
- '0100100010101110110100110001011000100110111011010101101000001010'
experiment: batch_run/rand_str_64_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
