ancilla_dim: 8
bitstrings:
- '0001010111101001010100100011101011011001110110101111'
- '1000011110100000111001101011010011000111100100011001'
- '0001010010000111111101000011010001000101111010111110'
- '0101111100101100111101010000011010010000101011010100'
- '0111000010001100010110000011100001001100001100011000'
- '1101010001001011010101001101101111111100110100101011'
- '1110110011110101111100101111001101100110101010110000'
experiment: batch_run/rand_str_52_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
