ancilla_dim: 16
bitstrings:
- '1000101111111100010001101111110100010111'
- '0001010001100110011000011000110010110001'
- '1011101101001101000001101100001101001111'
- '1010111101001011101100111101111101001011'
- '1110000100001100011111001001011011110010'
- '1101011101111111111000110000000010000110'
- '0001010000110000110010100111001111011011'
- '0100011000000100100010101011101000010101'
- '0110011000101011100101110011010100000011'
- '1110000011101111000001001011110101101110'
- '1001001101110100111010100110010000011000'
experiment: batch_run/rand_str_40_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
