ancilla_dim: 64
bitstrings:
- '1110110101'
- '0000000011'
- '0001101111'
- '1010000011'
- '0110010001'
- '1001111100'
- '1011100010'
- '1111101100'
- '0001110011'
- '1000011001'
- '0010100110'
- '1001111011'
- '1000111100'
- '0111011010'
- '1000010101'
- '0110010100'
- '1111101010'
- '0010010011'
- '0101010010'
- '0101011011'
- '0001000010'
- '0111100101'
- '1110101011'
- '0110000111'
- '1111100111'
- '0000100010'
- '0010111001'
- '1001010110'
- '1111101101'
- '1110001110'
- '0001001001'
- '1101001100'
- '1100101101'
- '1101000010'
- '1101010011'
- '0000101000'
- '0001110110'
- '1001100111'
- '0111010101'
- '1101001000'
- '1011011010'
- '0011000111'
- '1111110100'
- '0000111011'
- '0011101000'
experiment: batch_run/rand_str_10_45_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
