ancilla_dim: 32
bitstrings:
- '1011110010001010100101110000011110000011010010010110001010000101'
- '0000000011010100110100110111101111000101010010110101011110011100'
- '0010011001101111110111100111110011111001111100101101011011001100'
- '1111000110101100010111000011110100110100111000101011110010000011'
- '1011011111111000000101101111101010111000100000000111111110010101'
- '0111000100100000101101001111000110001000110110001100000100001000'
- '0001011111111010101100100110010110000000000001011101110000011100'
- '1100100000011011010000110111010100001001111111011111010100111000'
- '0001100001011101111011101101100100000111110111011001100001010100'
- '0110101001101000101111011111101000111101011110001111101101110011'
- '0010100111011011001101010010011010011011000110010011110011100101'
- '0111001110100001000110010100101101001110100111100000000000010010'
- '0111000010101110111001101010110110000011001010111001100111111101'
- '1001110101110101101000110001100111010000000100000001010111110011'
- '1000011101111001011001111111000000101111000111100101110111100000'
- '0000001110000000010001101011100101001110001001101010110110010110'
- '1101010110101010001010001011011011100010000011111000111001011110'
- '0001100011000100001011111111111111100011110101111101001000110010'
experiment: batch_run/rand_str_64_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
