ancilla_dim: 8
bitstrings:
- '111001010010100111111010100100110101100110101101110101000001'
- '100100111010011100011101010000111000101000110011001010010101'
- '010011000110111000110111101011111001000111011000100111110100'
- '111000111100011110101101000110110100011100001111001101111111'
- '111011010011010110000111110100010110101101000100010001100011'
experiment: batch_run/rand_str_60_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
