ancilla_dim: 8
bitstrings:
- '00101001000011011011011111010101010111101101'
- '10011111100111101001100000111101111101011100'
- '00011111001101001001001010010100011010111100'
- '10110001000110100111100001110001001111101110'
- '01010000111001110110010011011010111011100000'
experiment: batch_run/rand_str_44_5_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
