ancilla_dim: 16
bitstrings:
- '010001111110001111001010111110010100000010110010000011001000'
- '011110100101101101101010101001011001101000001100000010110110'
- '010000101011111100100110100001000111111110101011100101101010'
- '001010010010110000101111111111001001100001111100100001001111'
- '000111111110111010101101100000001100100100010101001000001010'
- '100100100001010100100010111000001100101110101111111001110010'
- '100001100010100010000010100111110110011100011111010111010100'
- '010101101011001000001011001101110111011101001101110010011101'
- '110110111010010100001001011101000010011100101000000101000111'
- '001001100011110000001010001011010001110101100110111101000101'
- '100101101011100011111111000010110101010011111101000110011010'
- '000100011011001110111010100111100111101000001100011110110010'
- '110110100110001111001001100010111111001110011100110111000110'
experiment: batch_run/rand_str_60_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
