ancilla_dim: 64
bitstrings:
- '01001011'
- '10111110'
- '11101101'
- '00000100'
- '01110011'
- '10011110'
- '01100101'
- '11100000'
- '11010110'
- '01001111'
- '01000110'
- '10010101'
- '00001101'
- '11100101'
- '00010110'
- '00011010'
- '10111111'
- '00000010'
- '11101111'
- '01101100'
- '10100000'
- '11011000'
- '11101000'
- '01101111'
- '00000111'
- '10010000'
- '11001111'
- '01111010'
- '01110001'
- '10011100'
- '00100101'
- '00001010'
- '01101000'
- '01011110'
- '10001111'
- '10111000'
- '11000001'
- '11100100'
- '00010100'
- '00010111'
- '10111100'
- '00000110'
- '11100111'
- '10001001'
- '11111101'
- '00101111'
- '00000001'
- '11100011'
- '01111001'
- '00100000'
experiment: batch_run/rand_str_8_50_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
