ancilla_dim: 8
bitstrings:
- '0001111010111110111000011001100000001100000000111110111110001010'
- '1010001110101110110011101111011001110001001011101110101111010101'
- '0111000110101110111110111000000000110011000001110111110000101101'
- '1011101100000000110111101000111010011101100011111001110110011100'
- '1100010011000010001110101100101111100010010101110001110100100101'
- '1111010010100110110111100110001010000010011110100111100011000101'
- '1100011100001000011011111100100010011001111110011101010001001111'
- '0111001101000101001011000001101001000101010001101011110010101100'
experiment: batch_run/rand_str_64_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
