ancilla_dim: 32
bitstrings:
- '101110001010101010010111010010110100001001011000'
- '100001001100001101111001001100110011100010100101'
- '111111010010010100110011001010000011111000110000'
- '100010100001100101101101010110111000000010100110'
- '011101101010001110111010001011010111000101110001'
- '100000110101100100111111101111101000100111000001'
- '000101100101001011010010110111110011110010011100'
- '010010101011100110111010110011100010100110011000'
- '010011110111100011110001101011001001100111001010'
- '000110111101000111011000011110111010100111100100'
- '111001111011001100011110011101101011100010110001'
- '010101110100000100110010000110111000101010100001'
- '101100001110011001100101101100101000100000111011'
- '101100001111001000101101111111111011101100010111'
- '011101101000111011110111111001100111011101111010'
- '010010011100100011001000011010111011100111110111'
- '110100010001001110101001001001111001010111011000'
- '111011001110111101010100001101010110011100010101'
- '100100010100010101001111011010110101101001110100'
- '110000010111000000010110110011101101110100000000'
- '000110000001110011100100011010101011111110111111'
- '001100111010101011111011101110100101110101011111'
- '100110010000000010100111101100110101100101110101'
experiment: batch_run/rand_str_48_23_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
