ancilla_dim: 32
bitstrings:
- '111000101101101010001010100110001000000011101000111111100101'
- '010000100101110101110101110001110110011000000111110001101111'
- '010111100110111001101101010011101111000111111000101010000010'
- '111111110000100001010101110010000110111001001101000011000011'
- '111111000001111111010100001001110110101000001010101011011101'
- '000100101011011110010010111001000001101001110100000111110001'
- '110001101011000010001100111101000000000001111010100000010100'
- '101011101011010010111001100001100111001101011001110010010101'
- '111000001001110100110111110001000101110111110101011111111111'
- '100000111111010110111100010110011010111100111111100101101000'
- '100000001110011011111101000100000100000011011001001001010001'
- '000110101011110000001000000000001000000101000100111110011111'
- '100100010010111011001110100000111100001100111100001101101001'
- '000101011110001001010110100010110010001111011010011001111011'
- '000011001100000100010111101111101011100100101011110011100000'
- '001011011001011101011010110110001001010001011100111111010010'
- '001110011100011100110100101001101111100100101001010100111110'
- '101111010101111001010111001010111101101001110010001111110011'
- '011000000110110010010001110000101101100111001011100000011111'
- '000010010101000001000100110110011100110100100110000010001000'
experiment: batch_run/rand_str_60_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
