ancilla_dim: 16
bitstrings:
- '1111000100110111110110101100100110110111001001010001'
- '1010111000110000011100001100110010011110011100010000'
- '0110000110011101111101000100101110010101001011100000'
- '0010111000111110111010110000001010010110110011010011'
- '0010101010001011001000000001010110001000001011011110'
- '1100000111000101001100100100000010100001111101110100'
- '0111000101001000100011100110010010110000010000100010'
- '0110000010101101000101010100100011010111101111001100'
- '0100011000001110110001101110000101000010111111011000'
- '0101001110010100100100101000010001111110100110000111'
- '1111110000001001001000000001101101010010100101111110'
- '0001100110000010010110111101010111101001110001011010'
- '1111001000111011100111110011100100110110110111101111'
- '1111010000100100101100001100001100001011111001011110'
- '1111101001011011000010001000100111000100000101000011'
- '1111111110101100110000000010011000000100111110000010'
experiment: batch_run/rand_str_52_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
