ancilla_dim: 16
bitstrings:
- '1011101010000110011000011101011101010011'
- '0010110101011101000010011101101010001101'
- '0111100010000010101111011111100010011110'
- '1100011000011000011100010100101110001100'
- '0000000001010111110010100011001001100000'
- '1110110010110001000010001100011001001100'
- '1110010101101000011011101111110001101111'
- '1111101111100011011100111110011011010111'
- '1000000010101000100001101001010110110010'
- '1011111110011100010110001110010001111011'
- '0000101111011001001011111101111110000110'
- '1001111010010101100000100110110011001010'
- '1011110000010100100110011010101000010010'
- '0001010011011001101110010001000000010001'
- '1100010111110100111011001101100010101111'
experiment: batch_run/rand_str_40_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
