ancilla_dim: 16
bitstrings:
- '01011111100010000001010000000110110111001001'
- '10100010010110001110101000011001000001011001'
- '00010110110000010100100011010011010110011000'
- '10110010100100101011001010000100011011101100'
- '00111110100011100111100011110101010111101011'
- '10100100001011001011101001100101001101110010'
- '10100111011100010010011100001111011111010110'
- '11001111101101010101000100011001100100111001'
- '01100111010001111011100100001010010110000011'
- '01100010011001011100011011110111000100000100'
experiment: batch_run/rand_str_44_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
