ancilla_dim: 16
bitstrings:
- '10110011000011011000111010110101001011100000000011000001111111110001'
- '00101010010000000010011010110100010110110000100110011100100111001010'
- '11000001110010000001010101110111010110011000110100010010110100000001'
- '10011110000000010110101111011011000000111101000101010110111010010000'
- '00101111000110101100001000110011010011110001011110100111100100110011'
- '00010011000111011111111011111110101100101010010011101011100111101101'
- '00111111011011100100011001100010011101101110000001101100111111110101'
- '00000111111010001010101101001111010100110001001100110011111111010101'
- '01011001101011100110000100001110010000000001101001011001011010010010'
- '10111010110101010001110010100001101011001001000110100111011000100010'
- '10100001001011000010100000001110011101010110001111111101111110010011'
- '10101011001010110110101011011101111101000110111010111110010010100100'
- '10010001000000110001000011111110110000010111011100010100011011101101'
- '01101110100011000011000010100010100010010001011101010100100110011101'
- '10101001010111110001111011011001101111010100001110111110000011000100'
- '11000100101000001011000001110111011001010111110100100111101101111010'
experiment: batch_run/rand_str_68_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
