ancilla_dim: 32
bitstrings:
- '0100000010010110010010100110010010111001111111000100'
- '0001101011011001110010111111011100010011110010000000'
- '1111100100101001100100001101101011100010000011101010'
- '1110011111111001000000101001011110101111101011100111'
- '1100101111110111010000111111010011100100000101100011'
- '0001000110101000111010000111110011010001101101110100'
- '0110110100110001100010011011000010110100110000100110'
- '1000101000011000010100110001000001000011010001111011'
- '1000011001000110100000000101110000000111101000010011'
- '1100000101011111101111011011011110011110011011101010'
- '0110111101100100101011100100101000001001110100111011'
- '0100010101010111101010001110011000010100111101110110'
- '0000101010010011101001101001001010010111000010011010'
- '1001000000011001001011011101011000111001110001100010'
- '0100000110110001101010111100110010001110011100100011'
- '0001001100000110010101010000010001001011111100100011'
- '1001110011011001110011000000100100001111101001011111'
experiment: batch_run/rand_str_52_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
