ancilla_dim: 4
bitstrings:
- '1011101111001101000110110000001111000111011110000100110000010011'
- '0001110111000100000101110011101000100000010111011010010101001100'
- '0000100001001110011100000000010101111111010101011100011110110101'
experiment: batch_run/rand_str_64_3_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
