ancilla_dim: 2
bitstrings:
- '00001011001001110101101010111001'
- '11111101000111100011001001101000'
experiment: batch_run/rand_str_32_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
