ancilla_dim: 16
bitstrings:
- '1010011011101110000110111011011010100111110000101111'
- '1111011111010111001000000011111111001010100100111010'
- '0000000011111110110101110010000100011101111011001011'
- '1110010010010000111011010011011111110101110010100001'
- '1110011011001110010011000011011110000110000110111001'
- '0100011001110010110100000000000011011110010010000011'
- '0001010011010111110010110111010011101100110100000101'
- '0010011001001100000111110111011111001101110100010010'
- '1011000011111100011000101010111111110000011101001110'
- '1110110101100010011001110101000110100101000111100100'
- '1100011110010000110000110001001111001101100110001010'
- '1110010100101111101110110010011100111110111011000111'
- '1010011110011000001100111010110100111111100001000100'
- '0111100110010110001110110101000110000101111000011000'
- '0011000111010011111001100100111110101100011010100011'
experiment: batch_run/rand_str_52_15_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
