ancilla_dim: 16
bitstrings:
- '01111001000000111000011011010010'
- '01011011100101111001111110000111'
- '11101100110001110100001000010011'
- '00111101111000010111001010001000'
- '11011011000010001001000000100000'
- '10000010001000010011110010100111'
- '00011011101111010100111110011111'
- '11111001000101111110110110110111'
- '11111101000010010101101110000110'
- '10000110000011010101110100010101'
- '10100101101000010000111000101010'
- '11101111100010110010111100010000'
- '11110010011001100111000001011000'
- '00111010100010100000000111110110'
experiment: batch_run/rand_str_32_14_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
