ancilla_dim: 8
bitstrings:
- '011110110000100010000001000010100011'
- '101010101110111011001001001011000110'
- '110000011100101011100101000001100010'
- '100011111010100110011000011001001110'
- '100110110011101100010001110101010111'
- '001001000001000011010111111000101101'
experiment: batch_run/rand_str_36_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
