ancilla_dim: 4
bitstrings:
- '1111010001101111'
- '1001011011110010'
- '0111010011001001'
- '0110000011000101'
experiment: batch_run/rand_str_16_4_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 16
