ancilla_dim: 16
bitstrings:
- '111101110001101101101001100101110000100111011010'
- '010010111110101100101011110101000100001000100110'
- '001010110010111111011000011001110011101011110010'
- '010111011011110011000000111011110011101010011110'
- '111011110100110010001110100000001001010110110101'
- '011110101101101010110110010001110010110000101010'
- '100110001011100101011111100001011111000001101000'
- '000011110010100001101111110111000010011111110100'
- '011011100111001111110100000011001101101000001000'
- '011100110101101010111011111101001110000011111100'
- '100011000010000110011001110011100010001101011110'
- '010101010000010100000101011010111110110001101000'
experiment: batch_run/rand_str_48_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
