ancilla_dim: 4
bitstrings:
- '100000111000011101001001'
- '111100110100011110010001'
- '001110101010100001110110'
experiment: batch_run/rand_str_24_3_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 24
