ancilla_dim: 2
bitstrings:
- '111001001011100000100100'
- '101100101010100100011111'
experiment: batch_run/rand_str_24_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 24
