ancilla_dim: 32
bitstrings:
- '1000011000011111010100101110011011100111'
- '1000110100010011101111001100011011000101'
- '1100110000111111011010100110111101101011'
- '0000000111000010100010011000101010001000'
- '1110000001111101100101011000101010010001'
- '0011011001110111101111001111101110011000'
- '1010110010101001011110111001010111011000'
- '0000000100010100000011010010000010001010'
- '1001001110100110111111000101011011100110'
- '0110101100101011000100011111001111010001'
- '0010100011001010111101101110111100111011'
- '1000111110110101101011011000111000111001'
- '0100100010111111001111100111001000111010'
- '1000100111001111111101101001001111110110'
- '1010010101000011101011100010000000101110'
- '0001111010000001101000001100010101001001'
- '0110011001110010100111110000000001101001'
- '0100011100101010101011010100011100110000'
experiment: batch_run/rand_str_40_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
