ancilla_dim: 16
bitstrings:
- '0111010111101100101001010101100010110011'
- '1101100110011001111011110010110100110111'
- '1100111110111101011010101111000001110110'
- '1101010111110100001101000011010000111111'
- '1111100101001110100010110100110100011110'
- '1011011110011100111001110101001110011100'
- '1000100110110001111011001110100100011110'
- '0001000101101010111010111000101100101111'
- '1111100001111010011100010111110010010011'
experiment: batch_run/rand_str_40_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
