ancilla_dim: 16
bitstrings:
- '001010111101100011010011111110111011101100101111001011000101'
- '110100100000001111111010111000011001101011001100111010110011'
- '101100110110001010100110000011101101010101010011011101110111'
- '101001001101000101001100111010110110111111010101110001101110'
- '111101100110011001101001101000010010000010110101100101101001'
- '100001100110000001110011011000110101000001111100011001111111'
- '100011011001010001001111001101110101100000100010101001011010'
- '000110111010110110010110110001110010111000110011100011100011'
- '011001010101101001011100100010010100100100011000100100101111'
- '001001110111000000100110000010000111110110011101101110111110'
- '101101110001001000111000101111100011100101100011001101101010'
- '100101101010111100110111000110100001100101100111110110101011'
- '000011001100110010110101010101011111101101110100011000111011'
- '001100001000011101010001010110111000001100101001011100111110'
- '101111101110101111000011010110000101101011011000110011100110'
- '111110011110101101101100000111001010011000000011110000111000'
experiment: batch_run/rand_str_60_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
