ancilla_dim: 16
bitstrings:
- '0100011010100001100101100100101100111110'
- '0110001001001001001000101110000110001011'
- '0110010111101110100101001101100001110110'
- '0011101000001101111111111010000000110001'
- '0001100000010011111111101011000111010011'
- '1110000111010110100001110011101011010110'
- '1111111110111101111011011001010111000101'
- '0100110101100110110101100100010010001011'
- '1101110001011110111000101011101000000101'
- '1110100111010000110110010111010111001101'
- '1011110010100100100011010011010101000010'
- '0111110000100110000011011100001101010000'
experiment: batch_run/rand_str_40_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
