ancilla_dim: 16
bitstrings:
- '0011100111100100001010100000101001000011'
- '0000010000000110001111100000110010100100'
- '0000101101101001011111110011111100000111'
- '0001000011011000010110011101011000110100'
- '1111110001000111101111100000001010111000'
- '1111001000101100111111010110001000100110'
- '1000000010101001110111101011101011000100'
- '1101001001000000011000110000100100001011'
- '1100100110000101011010110000000101000000'
- '0011110110000011100000111101101101010110'
- '1111011100001010001110111101010010100100'
- '1010010001010111100000101000000111111101'
- '1111000101110101010011000100110110010100'
- '1111101001011011101000110101111010011000'
experiment: batch_run/rand_str_40_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
