ancilla_dim: 16
bitstrings:
- '0100100011001111110000010111'
- '1101101101010110100110111111'
- '0110001001000111110011100101'
- '0111100010010010111110110101'
- '0001000010101110010111000011'
- '0011110000000101110100010101'
- '0110100100111001100001011100'
- '1000001000111100110011101010'
- '0100001011110011110000100110'
- '1100000110001100000011011101'
- '1011001011101010111011011000'
experiment: batch_run/rand_str_28_11_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
