ancilla_dim: 16
bitstrings:
- '011111110101100010011000000011011110110011000110000101110111001010010100'
- '000010100101011110000110010101000010011110001111000001001110001100001111'
- '101000011010101100010000011101100100011000011101000110001110100010001111'
- '001101001011010010001000001110001101011001010000000101111111010001001010'
- '100011000101001110000110110010011111010101101000110010010001001001000011'
- '010101011101001011110001100010010001101001010010010011100111011011010110'
- '111010000001100111001110010001010111110100100110010001101101010110110111'
- '100110101001000101010111101101010100100101111010111001101101100101010000'
- '010110000110000111101010101000111010101111010111010011101110010111100101'
- '101001000101000001001001110100101011011110111001001111111101111000111000'
experiment: batch_run/rand_str_72_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
