ancilla_dim: 512
bitstrings:
- '0001010100'
- '0010001111'
- '0011011110'
- '0100110100'
- '0101000011'
- '1110110110'
- '0111000011'
- '1101100000'
- '0111010001'
- '0110001100'
- '0110001000'
- '1111100110'
- '1000111100'
- '0111111100'
- '0111111000'
- '0000100010'
- '1010100101'
- '1011111001'
- '0100010000'
- '0000001001'
- '1101000001'
- '1011001100'
- '1111011000'
- '0000011101'
- '1111111100'
- '0010101001'
- '0011010111'
- '0110100100'
- '1011110000'
- '0110000110'
- '0111011000'
- '1001101100'
- '1000111011'
- '1100000010'
- '1111101001'
- '0010101010'
- '0110001010'
- '0001011010'
- '0101100111'
- '1101101100'
- '0101010100'
- '1110001011'
- '0001101111'
- '0111101111'
- '1010000100'
- '0000110010'
- '1001110100'
- '1011110001'
- '0100101010'
- '0100110011'
- '1011100110'
- '0010111001'
- '0110101110'
- '0001011101'
- '0101010110'
- '1010111111'
- '0011011111'
- '0000101100'
- '1111010000'
- '1000111010'
- '1000111001'
- '0100011001'
- '0001001111'
- '0000110011'
- '0001001101'
- '1101011111'
- '0101101001'
- '0000001000'
- '1100111011'
- '0101011110'
- '1001010010'
- '0101010010'
- '0100001110'
- '1011010111'
- '1000011110'
- '1011000101'
- '1010000000'
- '0101100010'
- '0110011001'
- '1101010100'
- '1011101000'
- '1010011011'
- '0000000110'
- '0010000110'
- '1011100001'
- '1010010011'
- '1101101000'
- '1111110000'
- '0111110001'
- '0011111101'
- '1001101101'
- '1001011100'
- '1010100010'
- '1100011001'
- '1000001010'
- '0010101111'
- '0111001111'
- '1110001000'
- '1110111001'
- '1100000011'
- '0101111111'
- '1000110111'
- '1111110011'
- '1001011000'
- '0101100110'
- '0010100011'
- '0111110101'
- '1111101000'
- '1011010110'
- '1000011010'
- '0001000001'
- '0001110000'
- '1000101001'
- '0011011001'
- '0100011110'
- '1001111111'
- '0101101010'
- '0010101011'
- '0001010111'
- '0010000011'
- '0111110110'
- '1001001110'
- '1100110100'
- '0010111011'
- '0010001101'
- '1100110010'
- '0100010011'
- '0111000000'
- '0000010101'
- '1000110110'
- '1001000110'
- '0011101011'
- '1101111011'
- '0001011110'
- '1000100001'
- '1011111111'
- '1001110010'
- '1010000011'
- '0111010011'
- '0000111111'
- '0110010111'
- '0111001000'
- '0111010010'
- '1001111101'
- '1010101110'
- '0001001011'
- '0000011001'
- '1000101011'
- '1010111010'
- '1000000011'
- '1010111000'
- '0110111011'
- '1000001110'
- '1110101101'
- '0100000101'
- '0010111101'
- '0001010010'
- '0011111000'
- '0110111010'
- '0000101101'
- '0101110111'
- '0000011010'
- '1011101110'
- '0010110101'
- '1011111011'
- '1001100101'
- '1110101000'
- '0001100001'
- '0100110101'
- '1110000100'
- '0011110010'
- '0111100111'
- '0111110100'
- '0000001111'
- '0101101101'
- '1111001111'
- '1110010111'
- '1110110001'
- '0001110111'
- '0011110000'
- '1010011111'
- '0101000110'
- '0010110010'
- '0110011101'
- '0000000000'
- '1111100100'
- '0111011001'
- '0011000001'
- '0110010100'
- '1001111100'
- '1001100100'
- '0101001110'
- '1010101001'
- '0011101010'
- '0110101010'
- '0010101100'
- '1100110101'
- '0100010110'
- '1111011101'
- '1011110010'
- '0100011000'
- '1010000111'
- '0000010000'
- '0010010110'
- '1101011001'
- '1100011111'
- '1111101010'
- '1110100001'
- '1011010100'
- '0001100000'
- '0111101101'
- '0010010111'
- '0110000000'
- '1010001101'
- '0100100011'
- '1101000111'
- '1110011110'
- '0110001101'
- '0001010101'
- '1011110011'
- '0010100111'
- '0011110001'
- '0101100011'
- '0011000011'
- '0101011000'
- '0100100000'
- '1000000000'
- '1010110101'
- '0001010011'
- '1110011001'
- '0001100110'
- '0101100001'
- '1011101111'
- '0010100000'
- '0101001101'
- '0010000000'
- '0010001110'
- '0010110111'
- '1101001000'
- '0111011110'
- '1111010110'
- '1110100000'
- '0001101011'
- '0011011011'
- '1001101010'
- '0000110001'
- '0011100110'
- '1100000110'
- '0000110100'
- '0101110011'
- '0111011111'
- '0001111110'
- '1110101111'
- '1001001001'
- '1111111000'
- '1100101110'
- '0100011101'
- '1011010001'
- '1100000001'
- '1001110011'
- '1010011000'
- '1101010011'
- '0010100110'
- '0001111011'
- '1001101011'
- '0001001110'
- '0100010111'
- '1110110100'
- '0010001001'
- '1011111010'
- '1010001010'
- '0001110101'
- '0111111001'
- '1010010000'
- '0100000001'
- '1100101000'
- '0011010100'
- '1010110100'
- '1110011011'
- '1011001110'
- '0111001101'
- '1110010000'
- '1100100111'
- '1100101101'
- '1100100100'
- '0001010000'
- '1110001101'
- '1110100101'
- '1111001001'
- '0011011100'
- '1110100011'
- '1100001010'
- '0000111101'
- '1100010110'
- '0000110110'
- '0011000000'
- '0001001000'
- '0011011010'
- '0001000011'
- '1011101101'
- '0110100001'
- '0100011010'
- '0101111100'
- '1010011110'
- '1000111000'
- '1000011011'
- '0000101010'
experiment: batch_run/rand_str_10_307_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
