ancilla_dim: 16
bitstrings:
- '000010111101010010011101101001001000110000011001'
- '001111111110100011100100100100011111110011010010'
- '100100101101010000101101110000001101001010100011'
- '100111101111001010100100010000110000011001111010'
- '001111111101011000000010000010010100001100100011'
- '111010010001101110111101100000100001110010100000'
- '001101100000010110000100110111101110101100000110'
- '100001111100001111111111010011011110011000111001'
- '011001111101110111011101000011111111110011001110'
- '011010001100100110101101011100010100000101101111'
experiment: batch_run/rand_str_48_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
