ancilla_dim: 8
bitstrings:
- '001000100100111100011110011110000101001001001001'
- '111101001100101000101000001010001001011101111100'
- '011000101001100100111010010010010101100111110001'
- '010010101011010101111011000111111101001101110101'
- '101001111101110111010010011010110011100011010111'
- '111001001101111101100100011100010111001011101011'
- '000000111011010101101100110000011010100110000110'
- '101001001010110000110001100111011111110010101101'
experiment: batch_run/rand_str_48_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
