ancilla_dim: 32
bitstrings:
- '111111000111101010101010011111000010010111011101111001010110'
- '111010101111101011111111001000011101100011001000111010110101'
- '101011100000101100110101000000011001100000000000101000001111'
- '101010001000100100010001000011001110111000111101010111100111'
- '100111011001010011001001111101101110110101011011100010010111'
- '110110011001100010100010001100011110001101011011000100001101'
- '110000010011111000010110101000011011110110111101010111001010'
- '011101001011101011010000000010100111000010011011111110100111'
- '001100100000011011010010111010110010011010000110110000010010'
- '101101000001100101111011111101100111101001110100111000011110'
- '001011000110111000110101001000000100011001001001110000010010'
- '111111010110001111000100100010010001101000010100010111101001'
- '000010110001101001111100101111001111010000000111101111110110'
- '010001010101011000001001100010011101011011110010000101110111'
- '100010010100001010101111001101110111011100100011010001100010'
- '110111010000001111001010101100101111001011110110001111100111'
- '100100101000001001001110100011011001100010110001101011101100'
- '110000000100000110100010111111100100110101110101000000111010'
- '100000101001001000110011000100001011000101100110101101111101'
- '111001010000001011111111100101001101101011010100110001000101'
- '110000001100111001001001111001100011011111000001101011010100'
- '111001000011011111000110011010110100010000110101110101000000'
- '001101101001001010111110110100101011001101111111100001101100'
- '001110110100001001110000010101000111000001010000011101111101'
- '111101100100000111001000111000101111001011010011000000000110'
- '111110010000011101111011001100010000010001001010001101000100'
experiment: batch_run/rand_str_60_26_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
