ancilla_dim: 32
bitstrings:
- '001011011111001100010111100110001101101100010000'
- '110000111000110100000001100111100010100011011010'
- '000010111101011101001001110001101100011100111101'
- '111100100100111100011111110001110010000101001001'
- '111011011111101110011110100010010000110010100011'
- '001101110000010110000010111100000110000011110011'
- '000000000010110101101110101000010011001000010001'
- '110101101100010000110110100101111001011101101000'
- '011001101100011001011110000011010111101011011000'
- '010000011110000001101011111010000000111001001011'
- '110111101011010101001000100000100100001111010101'
- '000001001100111010011011100010011011111011101010'
- '110001101000010011001110100111110101001100111100'
- '100011010001110101111000100110001001100000101001'
- '000111000001110011011101010111010011100000100010'
- '001011001100001100110111100000111010011010011001'
- '110011000000101110110111000000000110110100011000'
experiment: batch_run/rand_str_48_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
