ancilla_dim: 32
bitstrings:
- '10100111010110101001010011111010001011101011010011000110'
- '01110010100010110101010011001111000111111001101101010010'
- '00011100010101110110101110101010010110011101110011101010'
- '01111111111010000101101011000110100010100010001100000001'
- '10100100011111010100101010101000111011010111001101010110'
- '11100100011110001101011000101001011100011001000001010011'
- '01101001000101011000110000101101010001110111001101101100'
- '10011101011101000011000100101101001111010101010001111000'
- '10011010110010101001000000100001100001011000111100111100'
- '10000100010111000101101001100100110000000101111010100110'
- '10111000001011011101111010010100110110110001111111000101'
- '11001010001111100101001010100100001100110000001110011101'
- '01100100000110000111001001101011111000001011101100011000'
- '11101111000001001111000011000011110111001110011010100111'
- '10000111010111000101111010001001101011001010100000010011'
- '11001001011001011001001101100000100001110001001000000011'
- '00010010100010101010100010011011101101100011101101111010'
- '11001100010000101111101011101010011011101010001110101100'
- '10101010010011111110100111011011110100000100101011100101'
- '01010100111110110110011001110011101000001011101000101010'
- '01100011000111011110000111100010101000111100000111001101'
- '11100100101010011010100001010000000010000110100111001101'
experiment: batch_run/rand_str_56_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
