ancilla_dim: 16
bitstrings:
- '00111010001100000011111101100100'
- '00111001101100110001111011100101'
- '11100110100100110010001001000110'
- '10001000110110100011010101010011'
- '01110100111111000111101111101010'
- '11101011011000100100010111101010'
- '10100111111001001000001001101001'
- '11111101110101100011101101110011'
- '00011001110101101110001101001101'
- '10110000011001011001011111010100'
experiment: batch_run/rand_str_32_10_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
