ancilla_dim: 2
bitstrings:
- '10100011'
- '00011001'
experiment: batch_run/rand_str_8_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
