ancilla_dim: 32
bitstrings:
- '110011110010110110001000111110111100010011011101001100010110'
- '011000001110111111110101110100000100011101011001010100001110'
- '000110000110000100000101001111000010011011101011101000001111'
- '110011101101110100011011001101110101010110111100001101001010'
- '100111000111110011001011111000000011111011010101010101001010'
- '101011100111011100000100101000011010111001100110000110010001'
- '101010000101000110000010000111001001110011111111000110101110'
- '111101010000100100010001100011010110111100011011101111100011'
- '001000000011111100110011001111101000011111000001011000001110'
- '110100010000000110111000100100001000100000110011001110101100'
- '011111101000100000010010001100000111011010011000100000110110'
- '100000111111101001000110000001110011010010001100010000101000'
- '010011011111001101111110110110000100111110000111111011101100'
- '111000000010000101100001000010101101110001111111101101010101'
- '010010000011101000001000011100100101100001110000000010100110'
- '110010000111001000001111010110100110000101100001111010110010'
- '111011011101001011111001111010100110011000100110000001110011'
- '111011111101100010110111001100101011001110011100101101100101'
- '011101101011101001000100010011100100000101010100001000001100'
- '110001100000110110011110011001010010100101001001010111001100'
- '100100100001111111000110010101101011101111011101010000110111'
- '000011001110001011110100101110011011110101000100010000110100'
- '011111100110110111100010000011001111100101000110100001110001'
- '111110010111110010101111011001111111010000111101110110001010'
- '110010010011110000001011110010111101011110110010011110000100'
- '011010010010011001111110110000010110101100000101110110111001'
- '101111011001101011100100101110001111100010010111000111010111'
- '100010011100001101111001010110000010110101100101100110101101'
- '010101011100011101001110110000000100010000000101110001011101'
experiment: batch_run/rand_str_60_29_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
