ancilla_dim: 32
bitstrings:
- '1110000101110000000010110010101101100111000110110100111000001111'
- '1010110110000111010010101011110111010111000010100001101001110111'
- '0011001011110110001011101110101101110010001101001100111111010011'
- '1000010100000010110001101101010101111111111001101110111101100100'
- '1001101001110011101110100101001010111111011011000110010100000001'
- '1111111000110000110010001010000001100101100001001101010111110101'
- '1101101111111010010001010110000011101111110100111000110001010100'
- '0101011010011010000100110010010000100000011010101110000111010101'
- '1110010010000010010100110011010100100011110101001111111010001001'
- '0100111101001111101101000110111011111101111000111001101000010011'
- '0110010011101010110100010011110011000101010111101001001010101000'
- '1001000111111100001010010111110000000011000011111001010101001100'
- '0100100111011010101010111011100101100000000011011110100000001000'
- '0000100110101010111010101000100110001010011111101100011000011101'
- '0011001011110101011101001111000011001010000000100111110010000011'
- '0100110100010010011110001000110000011111010101010001110011111010'
- '1100001100000001000100101101000011000100010110100100011110000111'
- '1011110101111001011011011101000110000000110111100001011111111010'
- '0111110000000111100011110110111110101110000000111101101000111010'
- '1001001100100100101110101110011011000110110011111000011011001000'
- '0100000000111011110001001001100000111111111111011000100100100100'
- '0101100110001110101110100100101010010010000110001110101111000001'
- '1000010101101111010011000000100001000110101010000010011100000100'
- '1000010001110000111111111100101011001011100101111101100110111101'
- '1010110010111011011111011101001001111000010111101000000100001110'
- '0111101111000010001111011111010110111110011000000010000110111000'
experiment: batch_run/rand_str_64_26_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
