ancilla_dim: 8
bitstrings:
- '1101000101'
- '0011000101'
- '0111101010'
- '1000001110'
- '0001001010'
experiment: batch_run/rand_str_10_5_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
