ancilla_dim: 16
bitstrings:
- '0101111110'
- '0011100100'
- '0010010001'
- '0010110111'
- '1110100101'
- '1100000111'
- '0001100110'
- '0000011001'
- '1010111000'
- '1101110111'
- '1001011110'
- '1111001010'
- '0010111011'
- '1010111101'
experiment: batch_run/rand_str_10_14_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
