ancilla_dim: 16
bitstrings:
- '011011111110000100010111100010011011'
- '100100011100011101001110101011000111'
- '111011001110100110110100100001100111'
- '100101101101101010010100101001100001'
- '111001101010101011010011001010110100'
- '100010100111101001001001001101100100'
- '101100000010001010011010111011101010'
- '011000100011110001101000011001111010'
- '101100010100111001110110111010010010'
experiment: batch_run/rand_str_36_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
