ancilla_dim: 32
bitstrings:
- '0110100111100011101010011111010100111011101010110001'
- '0110001000001000010010011011011100000011110110111000'
- '0010101000001100110011010111110100010010010111001110'
- '0000100010100110010100011100000111111000001000011000'
- '1101010000010001101111111011101011010000101101101001'
- '1111011100010011001001110001001100001110010011011111'
- '1101100010000101011000001100101111100101101001101100'
- '1111010001011000010010100101000000011101001010111101'
- '0001001011101010101001101110100011101100101101010110'
- '0101010111111101011110100010110100010010100110001110'
- '0110011001101111011001101010000011000101111101101111'
- '1101000011101011111111011110000011010000101100010011'
- '0011100100000101101000011010100111110011110010001101'
- '1110011010011001000100011101011111000110011111001010'
- '1000111000101010101111100000001011000111110111100100'
- '0001110101110101010001111010010011000111101110111110'
- '0100111110111011101110101011011011001001001111101101'
- '0110011011110101010100011100001111111110101101000001'
- '0001010111100011101100011010000110000100010000100011'
experiment: batch_run/rand_str_52_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
