ancilla_dim: 256
bitstrings:
- '0001001110'
- '0111000110'
- '1101101101'
- '1110011111'
- '0100100101'
- '1100100111'
- '1010010011'
- '1110000001'
- '1000110101'
- '0111101111'
- '0001110001'
- '0001101100'
- '1111000010'
- '1010000000'
- '0100001000'
- '1001101001'
- '0000110010'
- '1101101100'
- '0110001101'
- '1001010010'
- '1001111101'
- '1111010111'
- '0110101111'
- '1010010100'
- '0111001100'
- '0101000011'
- '1101101001'
- '1000011011'
- '0011110011'
- '1110011001'
- '0010110100'
- '1000010100'
- '0110110011'
- '0000101101'
- '0001000001'
- '1011001110'
- '1100001100'
- '0101010011'
- '0010100101'
- '0001011110'
- '0000011011'
- '1101111101'
- '1011110001'
- '0110101011'
- '0100000010'
- '0100011100'
- '1100110100'
- '0011111010'
- '0100010011'
- '1011001100'
- '1000100011'
- '0001110100'
- '1000101001'
- '0000111001'
- '0111111000'
- '1001111000'
- '1110011101'
- '1001001010'
- '1000001011'
- '0010010111'
- '0110001100'
- '1100010100'
- '1100111010'
- '1101000101'
- '1101001010'
- '1101101110'
- '0111000001'
- '0000110011'
- '1110101101'
- '1011011010'
- '0100101111'
- '0011001101'
- '1110001010'
- '1100011010'
- '0001100000'
- '0010000110'
- '0000110000'
- '0111001111'
- '1001110101'
- '1001011110'
- '0011100001'
- '1100000101'
- '1010010111'
- '1000001010'
- '0010100011'
- '1101000110'
- '0001110000'
- '0010101110'
- '1110110000'
- '0011000100'
- '1100010010'
- '0001000110'
- '0010001111'
- '0010111001'
- '0101001011'
- '0101000101'
- '1101011001'
- '1011011101'
- '0110000110'
- '0100100001'
- '1110010111'
- '0101111000'
- '1000110010'
- '0011100100'
- '0011110101'
- '1100101110'
- '0101111111'
- '1010000001'
- '0100010010'
- '0001101010'
- '0110110111'
- '0000100011'
- '0011101111'
- '1111000110'
- '0001001101'
- '0110111001'
- '1101101011'
- '0100001011'
- '1001100101'
- '0000110111'
- '1010001101'
- '0010011111'
- '0001111010'
- '1110000100'
- '0100011011'
- '0001001010'
- '1111011001'
- '1010101000'
- '0000101011'
- '1100111000'
- '0100010111'
- '0100101100'
- '0111101110'
- '0100011010'
- '1101111001'
- '0110111011'
- '0110001111'
- '0111110000'
- '1110000011'
- '0110111101'
- '1011110110'
- '0110011001'
- '0101100010'
- '0110001010'
- '0011100111'
- '1011111101'
- '0001100001'
- '0000001101'
- '0111000010'
experiment: batch_run/rand_str_10_149_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
