ancilla_dim: 8
bitstrings:
- '0000010101111100101110010010011100000101110010101110'
- '0001110110011100111011110010101000100100001001111110'
- '1000000000001100000011000011111111011110110000100011'
- '0100001000010111110111110110011000101001001010011000'
- '0011100100101111011110100000111101000101000001111011'
- '1010101011101101011001001110011101101111101011011001'
- '0001000010110001001010000111101101010110111101100101'
- '0000010000011100111000100010110101000000100010100101'
experiment: batch_run/rand_str_52_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
