ancilla_dim: 32
bitstrings:
- '0011110000001000011111000100111100000110011101111111'
- '0100011101101000010111000100110111000011110001101011'
- '1000101000100111110010111011111010100000100110100111'
- '0111001000110001001111101110100011010011100010111011'
- '1101000010000110110111011010011100101110100110010010'
- '0011001110001011111110110001101001000011101001010110'
- '0111110101111110101010001110111001001011110011100101'
- '1111100010101010001110111001011100111101011100001001'
- '1100100110101110100011011010110111101100110111011010'
- '1010110000100101000111100000001101000111111111100100'
- '0001001000000011101100110011101001111111011010110101'
- '0101010010011110011010010001010111110110111111101101'
- '1101100011111110100001100011000101111110110110000000'
- '0111100000011111111100110011001001100000100000101110'
- '1111100011101001001111010111000100101010110000101001'
- '1110011010011010110000111010101011000011010110110110'
- '0101101101110000010111101000101011110001100110110100'
- '0111010100000011011001111101000001101101101011110010'
- '1000101010001001001111101101011001010011111110011100'
- '1101111000010101011100000010011100111101011101100001'
- '1000001100011001000001100101000000111100000100000011'
- '1000001110011100011110110101100000000110000111100001'
- '1011101000110001111001000110100011100111101010100111'
- '0000010001011101111010001100100001011101001110101000'
experiment: batch_run/rand_str_52_24_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
