ancilla_dim: 16
bitstrings:
- '11000101111010101001011011010100000111111100010010000111'
- '01111100010010010000100010001011011101111000000100101000'
- '00011011000010100101011000001010110101110111001100110000'
- '11010101001000010001110010001011110110001101011111011100'
- '00110101111100000101011101110000010001111100110101111110'
- '00111010101110111010110101010011000000110100101110011011'
- '11010111111101101101110011100111001110111101010010000101'
- '01010000001100010010001001100111110000101101100100001110'
- '00010101110111011101100111110101010010010000000011000110'
- '10011101110100110011111011000100100110100110110000011110'
- '10100110000110011101101101100111101001100101001000001111'
- '01110001110000101001010001011100010111110010001000101111'
experiment: batch_run/rand_str_56_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
