ancilla_dim: 8
bitstrings:
- '11111010010011101101111100010010111010110011'
- '00111100101100111100011101000010011011101000'
- '11000110011001010111001101101110110010000000'
- '10010110101010100100100001001000101101001100'
- '11011010111001010110101011110110001111000111'
- '01011110100000011011101101110110011111100011'
- '01101110111000000111100010101100110100000111'
experiment: batch_run/rand_str_44_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
