ancilla_dim: 16
bitstrings:
- '110100111111101000110100000001110000100100001000101111001001011010111010'
- '000101101110101011011100101001101111101000011110101001010011000100000101'
- '001101110010101100110100111110100101101100000110011000100011100100101101'
- '011010010110000100101001101101111110001111100101101111000100011111110011'
- '100000010100010001000101011111111101001010001010101101011001111110110001'
- '010010010100110001011010011100000111000011010110110111110101010110001111'
- '001101110111111001011111111101000101011010110100110010000010011001101110'
- '010001110000001000111111000000110100110110110001100001110100000001011111'
- '111011011111000001100001011000000101110000101101011110011111010011100000'
- '111000101111001000101010010110110101010100000001110011011100101100000100'
- '000011110100100011100000011100011101001100011001101011111000011000010100'
experiment: batch_run/rand_str_72_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
