ancilla_dim: 32
bitstrings:
- '00010010000101011100100111001110110100011100101001010011001111111101'
- '01000000101101100011111010101001000001000011101011011001100010110011'
- '01110101110001111110100100100111100101000010000101110111101100011101'
- '10010000001100100000011011000111000011101110011001010111000100101001'
- '11010011000010111010101111011010000101111001011111111101111111101001'
- '00100101001001001101110110001100001011101101101110111011010000000110'
- '11111011011000101101000110011001001100111010101110010111000111110100'
- '01110010001011010010011010101111110100111111010010011001010101000111'
- '10000100011111000111001101000110111111111100110101110100011110010100'
- '00100101111001000101101000101100101110110110101101011001101101100000'
- '11111011100010110001000011100110101010110010001101010100001101110010'
- '00010011111011111000111001000100010011101110111100001100011110011110'
- '10101111010101100001100110100011110000110101100100110000001001000001'
- '10011001110010101110011101101010010100110010101010010100101100000110'
- '11111010111111011110011100001011100011001000010111110100110010101001'
- '01011110010011100101111100011100000101101001001110110111011111111010'
- '00010010000101111111101000100100011110001000011001000100110100010000'
- '01010011100011110111000101111010010110101111000010000101101100011001'
- '11011010111001000111011011010010111100011100010001010001110001101101'
- '11111011100000101101110101110001100011100101010100011010010100001011'
- '00011001100110001101110011011101000000000111010011101001101101100110'
- '01110000111001110011000001011000110100110000100101111001100001010111'
- '01101101110101100000010110011000101100100000111010011100001111110001'
- '10010111000001010110110000011110111001011011011011000111100100101110'
- '01111100100001011000111111010001101100010010101111010100000001100011'
- '00010111111110100010001011001000001000001111000011101100010100001101'
- '10010010000111101000000111101000111000100111111101101101100101100001'
experiment: batch_run/rand_str_68_27_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
