ancilla_dim: 16
bitstrings:
- '00111000011010111110101110001000100010011111000111100011'
- '11011110110000000000111110110001001001110101111001101000'
- '01111000100010100001100011101101100111100001110111101100'
- '10000101100100101110101100000111111110101110011101101001'
- '10110011011001000111111001110111010001011010110001010000'
- '00010010110101011110100101011100011110111011101010001011'
- '00011111111000110100101001110001011011010001011100100011'
- '11101010100000001011010011010100001000001011110000100011'
- '00011001011011110011011001100100010001111011000010100110'
- '00011000100100111011111111001001111100001001011100000111'
- '01001110100010001001101110001111100110100100011101001011'
- '01001111110010001000000001011011011101010010111001000111'
- '10100011001010100010111110010111000001001101101110011001'
- '11010111010110011000100010110111011110111111001110110001'
experiment: batch_run/rand_str_56_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
