ancilla_dim: 16
bitstrings:
- '10010000000100101100111111000000111011011110'
- '00000111001101011000110101100110111101000110'
- '11000101101000111100000100001001101001101100'
- '01010000100000010010101001110111101000110001'
- '01011101000111100000100010111000000111011001'
- '10010110001100101100100011010111110000110011'
- '00111111001101110010011101110110100101110001'
- '01000100000011100000011000011101001000000111'
- '10100110011101000101101100100000001010111100'
- '01101010010011010001010110011001001101100110'
- '10100011110010011011111110111010111000111100'
- '00010010110011100101100011011111100011111010'
- '00010010101111010100111010011100101011111101'
- '11111111000100010111110111100001100001101010'
experiment: batch_run/rand_str_44_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
