ancilla_dim: 16
bitstrings:
- '1011111011110001111111001000111100101110010010100001'
- '1000010011100011010011110100001111111100010011000100'
- '1001001111111100001110101101000110110000001110101110'
- '0110010101010111010001011010100100100101000000011111'
- '0010001110000101001011011110110100110101101100100001'
- '0101010011101110111000101110000010010101111111110100'
- '1001001100110010111000011011110111011000101101100110'
- '0101100110101010110110100101111100110011110100111011'
- '1010010000011010011001011000011111111110101101010110'
- '0010000111011101111000001011000010001010100011001000'
- '1110010110100010101111110110100111111001000101110111'
- '0000001000001010001010111010000011111011110100011010'
- '0010111011001001011010111001101010111010011001110110'
experiment: batch_run/rand_str_52_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
