ancilla_dim: 4
bitstrings:
- '001110101011010101011100011001101101'
- '000010111000010101011001111111011001'
- '001011100000110100010101001010001101'
- '101010100111110111011001111001001100'
experiment: batch_run/rand_str_36_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
