ancilla_dim: 64
bitstrings:
- '00111001'
- '00000001'
- '01101110'
- '01111010'
- '01110100'
- '11100011'
- '11010010'
- '00110001'
- '00111011'
- '11110001'
- '01001101'
- '00101011'
- '00011000'
- '11111110'
- '11101000'
- '10011001'
- '00011110'
- '00000000'
- '01101000'
- '01001000'
- '10111010'
- '01011011'
- '00110100'
- '10101000'
- '01100100'
- '00100010'
- '01000000'
- '00101000'
- '11101100'
- '11101011'
- '10110001'
- '10101011'
- '11111010'
- '10100101'
- '01010000'
- '00001010'
- '11010110'
- '11011001'
- '10010001'
- '00000010'
- '01101001'
- '11111000'
- '00010000'
- '11000011'
- '11001010'
- '10000110'
- '10010100'
- '00010100'
- '00000100'
- '00010011'
- '10011100'
- '11001001'
- '10001111'
- '10011011'
- '01000011'
- '11001000'
- '01000010'
- '00100000'
- '01000101'
- '10010000'
- '01010010'
- '10110101'
- '10101100'
- '11010001'
experiment: batch_run/rand_str_8_64_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
