ancilla_dim: 16
bitstrings:
- '100011110010100011001011011110000100111110010000000110110111001100101111'
- '001101010111000010101000111110110100101110101010111011110110010101110010'
- '101010000101001101000110101010011010000101100110010010000111111010010011'
- '110101100100111010000110010010000000101011100000111110001011000100110001'
- '011001101011010100100111110001000111001100010010010010100000101010011111'
- '100101110101100110001110010001110011100010001111001110100111010011101010'
- '010111110110101010001001011010101110101011110101100010001111011110111110'
- '111011110111111101010111100101110001000111010010100101111110101101011011'
- '100000100111001010110101001100110000001001000100110000111010111001010101'
- '100111101111001011010000011011111000110110101100100010111111010011001010'
- '000111100000110100001100101010111111101101000111000100110110110101100101'
- '111101011101001011001001010110001110111000101111010011001101010110010110'
experiment: batch_run/rand_str_72_12_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
