ancilla_dim: 4
bitstrings:
- '010010110010111101110110010111111100111111111100010000100111101111101011'
- '000011010000110100001010101011111110110000110010110010000000001110010001'
- '000111111000110011001011101001111011011111100110110011000010011100110010'
- '111000010110011010101001000101010001110000001100000101011111110101010111'
experiment: batch_run/rand_str_72_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 72
