ancilla_dim: 8
bitstrings:
- '101101011010011111100111011001001001101100110001'
- '110001111101110001101011011111100101110011100111'
- '101001110010100010100111111001111111000000101000'
- '111101011101101011001011101011000010110111110011'
- '101100101010111110110000000111000001100010101001'
- '010111111101010001010011100011001111100011010001'
experiment: batch_run/rand_str_48_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
