ancilla_dim: 16
bitstrings:
- '0100001110111101011100000110001101001000'
- '0100101000011010001111011000010011100111'
- '0010111011110111101010001010101100100011'
- '1010001101011111100011100001101111000100'
- '1011101111110011111101010001110101110001'
- '0111111111011101000110101000111000110100'
- '1011001010010110010111010101011011011110'
- '1000001001001000010001011010010001110110'
- '0001011001101100000000000100110000100101'
- '0010101101000011010101101011101000001001'
- '1001010101000000100000111010010110111101'
- '1100011101101010111000001110010101110000'
- '1110011000000110001100110101010010000010'
- '1000001000011001110100001010000110101010'
- '1101001000111000110011110010110011101110'
- '1110100010011000111001010111110100010111'
experiment: batch_run/rand_str_40_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
