ancilla_dim: 16
bitstrings:
- '0011010100100111010101100111001101011000101011000011000111001010'
- '1111100001011101011011010001111110100000000110001111010011011111'
- '0101001110000011100011011111100010100000010000111000001110010111'
- '0101011001001000100000011001111100111000011101100011001001110101'
- '1110010000101010111111001100100001101011010110010100010110111001'
- '1010010011010010101111010000100010001101111011010011010100111100'
- '0000110101010101101111111101101000101101101011101011110110001110'
- '0101111010010101111100110100000101011000011100000110000100010100'
- '1000111111100001010100101010111010111111011011111101000010111000'
experiment: batch_run/rand_str_64_9_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
