ancilla_dim: 8
bitstrings:
- '111011000110011100010100101100110101001011001101000010000110'
- '000100010110011111010100111110011010001010111000000101000011'
- '010010000000010110110001011111111100100010101101010011001110'
- '111001011101000101101010011101000000000110001100110101111111'
- '111111010100111001001101010000010111011110111010001011000111'
- '011101010010101000101110101110000001101010100011110111010001'
- '100100111101111101101010110000001110001001000000010111110010'
experiment: batch_run/rand_str_60_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
