ancilla_dim: 8
bitstrings:
- '00000010111001000010'
- '01101100100101110001'
- '11011111111011111000'
- '00011100111011000001'
- '01110100001011010001'
- '00010011111011100100'
- '10010111011110101010'
experiment: batch_run/rand_str_20_7_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 20
