ancilla_dim: 16
bitstrings:
- '11100101010010011011110110001111'
- '00111110000001000000110001000010'
- '10101000111000111000110111101100'
- '00000110000111011010101001110101'
- '10101001110001101000000000110110'
- '01010011011111110011110101010110'
- '01000101100011100111000000100100'
- '00111100010110101100000101110100'
- '10010100111000000000001101100000'
- '11010100000111111111011001101110'
- '01100010110100110110010101111001'
- '00001000100010111110111100101100'
- '01111110010010101111101011000111'
experiment: batch_run/rand_str_32_13_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
