ancilla_dim: 128
bitstrings:
- '0000000101'
- '0011000110'
- '0001111000'
- '1011110101'
- '0101100111'
- '0011000100'
- '0100110101'
- '1110100111'
- '1000011110'
- '1111100010'
- '1110010001'
- '0111001011'
- '1001010000'
- '1000000001'
- '0001011101'
- '1011110001'
- '0100101011'
- '0000011010'
- '0110010101'
- '1011100101'
- '1010110110'
- '1101000011'
- '0000100011'
- '1111110100'
- '0000010111'
- '1100000100'
- '0101000011'
- '0101101001'
- '0101011010'
- '0001100010'
- '1001111101'
- '0001010001'
- '1111010110'
- '0100111010'
- '0010010111'
- '1010100110'
- '1101000000'
- '1011001001'
- '1010011110'
- '1110010111'
- '1000100101'
- '1110111101'
- '0111001110'
- '0010111110'
- '0101011001'
- '1010001100'
- '1100000111'
- '1000010010'
- '0100100011'
- '1010100011'
- '0111010100'
- '1000011001'
- '1111011100'
- '0011110100'
- '0001010011'
- '0010001111'
- '1010001111'
- '0001001101'
- '1110001100'
- '0110000001'
- '1101011101'
- '1110100101'
- '0110000110'
- '1011011111'
- '1111111001'
- '1100011001'
- '1001010111'
- '0100101010'
- '1111100011'
- '0001001100'
- '0100001010'
- '1010101101'
- '0111100011'
- '0000111100'
- '0011011110'
- '0011010011'
- '0011110111'
- '0000101011'
- '0010101100'
- '1010101010'
- '1000100011'
- '0100000100'
- '0111001101'
- '1110010110'
- '0011111101'
- '0011011000'
- '0110110100'
- '1100100000'
- '1101011010'
- '0101001111'
- '0111011101'
- '1001110000'
- '0001101110'
- '1100011110'
- '0010001000'
- '1101011100'
- '1011000100'
- '0001000001'
- '0101011110'
- '1101100111'
- '0011101100'
- '0001001110'
- '0101000101'
- '1101101111'
- '1000001001'
- '1000110001'
- '1011001100'
- '0010100100'
- '0001011110'
- '1001100010'
- '0111101100'
- '0010010110'
- '1111001011'
- '0110000100'
- '1001100101'
- '1011010100'
- '0010011111'
experiment: batch_run/rand_str_10_117_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
