ancilla_dim: 16
bitstrings:
- '0001000000100001001000111011011000001111100111111110'
- '0111100000111100010001101100101000011100011101011101'
- '1111010010100101010110101111111000001101100001011111'
- '0101110010010111001011010011110001001110101000001000'
- '0101001000100111011010011010011000011111000101000101'
- '1100100011101110010011011100111101001111001000001001'
- '0100001011011001010010011011100010100000011001110010'
- '1111001010100011100110101011100110110110011011100000'
- '1101011011100110101010100000011100000010011100000000'
- '1010010110110100001001101000001000111001001101001111'
experiment: batch_run/rand_str_52_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
