ancilla_dim: 32
bitstrings:
- '000001110000011101111100100111011111000010000101000011011111'
- '010101100100010100011011001111111110110001111100100101110110'
- '011101110101100000011110000110010011101011101001111111010100'
- '111010011101000111111101100110101011011100011101000110001101'
- '100111010111110000111111000111111011111110000101011000001000'
- '100000011000111001000101101110000000001011101010011100011001'
- '100001010000111011001101111111010111011010001110101010011011'
- '111100000111010100100101110100000100111011010110100011110101'
- '011110001000000001101100110100011011001011100111001100111111'
- '011011010110010110010011110110100100101001001101100110010010'
- '001100001010001111001111100000001001010000110101000110101000'
- '010100010000100000100011011100100011011110011101100110101011'
- '111011011010101100111111100101111111010110011111111011101110'
- '011111010001001001101100011001011010011100111111110111110111'
- '111001110101100101011000100101110110111110111110101000010111'
- '100111011110110011010111000100011100010101101110010000100100'
- '010101000011011100000010110111110101010001010010000100110110'
- '001001000010100111110101110111011111001100000010010100011001'
experiment: batch_run/rand_str_60_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
