ancilla_dim: 32
bitstrings:
- '0010101001010101110111111000011110010011111011111111'
- '1010111000100001001001011010111100001011001001001000'
- '0011001010100010011001000000100010001001110101100001'
- '1101010110101100000000011111111101011001010001000001'
- '0010011001111111110100110110101010101101001111111011'
- '1000011000111011111111011101110101100110001110011110'
- '1111001010110011110101101001111000110000110001011101'
- '1011100111100001001001011100100110010000110110010100'
- '1110001111111011010100011111000011101000001001100001'
- '1110101001110100100000011101010011000101001110110000'
- '0100110110100100011110100111010010101111011111000100'
- '0011111001000011111010111110101000011111000011011101'
- '1010101100011100100000001010110010001000111010100010'
- '0000010010100000100110011001110100101000000101111010'
- '0000010011001001000110001000011110100001110001101100'
- '0001100100110000000001111010001011101101100011000110'
- '0011001111000000001010011110100100011101100001010010'
- '0100100101000101111100000011101011001001110001010000'
- '1110100100010100011001011000111011101010100100011111'
- '1110101101110110111001001010110101000100111110111101'
experiment: batch_run/rand_str_52_20_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
