ancilla_dim: 16
bitstrings:
- '1100110101000001100011110000'
- '0010010110010010110111001101'
- '0101111111100111000000000100'
- '1111100011111100000011001000'
- '0100111001111010111100000000'
- '0000111110000011110100100010'
- '0100101101001100001001010011'
- '0100011110011010101000011101'
- '0011100100101100011111001011'
- '0001100111000110000100001000'
- '1110010011111100010110100000'
- '1100100000010011000101000000'
- '1001011000110111111111101011'
experiment: batch_run/rand_str_28_13_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
