ancilla_dim: 32
bitstrings:
- '001100100110111001010100001000100110111011111101110001001100'
- '100000110001101110010000110000111111111101111100001101100111'
- '010000011011000011101110110011100110010110100011010101111100'
- '010001001010001000011110011110101110111110000001000100011000'
- '001000011101011010111011101101100100110111001101100101001111'
- '000010110011101010010111111101011011101010001001101101000100'
- '101001110101100100101100111101100000111010101100101110001100'
- '010111101110010111111101110100101010101001001011001011010110'
- '111001100100010110011000111101101101100010101001110000110101'
- '111101101101010110111001110011000100100100000001001100100100'
- '111100001000011001100111001110110111100100110000111100100101'
- '000010100101001010110110100000011000000100000011101101110000'
- '110110010001111000010111011000101011011010000000110101100001'
- '011011010001100010111011110110101110010000010101010011000010'
- '111010011010000011001111110000010110110011100101100001011100'
- '001011010011101111010001111000000001100011010100110010000111'
- '110111111001110110011110111010011011011111011000000010001110'
- '110110000011011000100111011010101011101111000111001111001011'
- '011100110100010000011101001010100011101111001010111011010010'
experiment: batch_run/rand_str_60_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
