ancilla_dim: 2
bitstrings:
- '0110001101011001'
- '1110110101000110'
experiment: batch_run/rand_str_16_2_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 16
