ancilla_dim: 32
bitstrings:
- '00000011001100100100111010010011111111101001000000001110101001010001'
- '00011110100111001110010110100001001100101110100010001000100110010000'
- '01001101011001011011010110010000101101101000001000010100010100100011'
- '11001010000000011110010001101000100110000101001011000101001000110010'
- '00111101101001101011110010110010001110100101110100010011011001100100'
- '00101000001110100001001110100010101010010001010100111001111100001110'
- '10000100110011101001101011011100000101100000001111001010010111111001'
- '00110010100011101000001011011000111010110000101101010000111011111110'
- '10001110010000001000000100001111111101010010011001001010010101011101'
- '01010000010011011011011010110101111011110110111001100110100111010011'
- '11010101010100111101011011101101010101111010101111101110010000110110'
- '10100100000010000011000100000001100010001111111010001101100010000000'
- '10101111000011001100001101001111000101111100010100100010011001001001'
- '10101011001001010111100110111010101010110001100101101011000010110000'
- '10010011110101100100110110010100001000000100111101011010001001001000'
- '01011100100100001110001010100000001011001011010000010011001111100100'
- '01000001111111010000110101110011110100100000110111000000010101111010'
- '00001011011110010111010010011101100011000111011100001101011110101111'
- '01111101001001111000011101111011111001000100101011010010100110101011'
- '01101101011011110100100110000111000110011110101010011001101110001111'
- '10111100111111100100001111000111011011010110101100001001111101011010'
- '00010000001000010001110010100100100111101101111011110101111111000010'
- '11100101010000000100001011000111100110110111101011100001010111000001'
- '10010111001000010011001111111101100001011111100100111110000111010010'
- '10100000110100100100001110000110111100001100000100011001110100100111'
- '00010110010010100001101100101111101100000101001010000110100100001011'
experiment: batch_run/rand_str_68_26_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
