ancilla_dim: 16
bitstrings:
- '1100100110011101110011111010'
- '1001011111100000110111010011'
- '0011111111100011010111001111'
- '0000000110110110111010001110'
- '0101000111000000011101000001'
- '0001110101001110111010100011'
- '0100101010000001110000001000'
- '1001100111100011110100001100'
- '1010001011110011110001110110'
experiment: batch_run/rand_str_28_9_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 28
