ancilla_dim: 32
bitstrings:
- '100101010000110010011110111011000011010011111101000111001101'
- '100011101001001001010000000100111011001000011101111101111011'
- '000000101000001010000010011101001101100011101000100110011000'
- '000001010100000100010101000010100110100010001100101101001001'
- '011110011001011010000001010110011100000000100010111101101111'
- '001011111001001111100111000101100011101000111111101110100101'
- '110011001000101010100100011101101011001010100011101001000010'
- '011100110100100011101001010010011100110111000010000001001001'
- '100000010001010000010110101111111111111001111010100100000111'
- '111001110110010011011101011100101001111000010110100001110010'
- '001000111010100110010010001101001111111111100001111000011010'
- '101010011110100011110110001011011010000000001001110001110110'
- '000000010111100111011011110100110011011110001101011111000000'
- '000100110110011010100011111000110000000001100011100111010001'
- '011111001010101111000101010111010000110010010110111100011111'
- '011000110100011010101001111111011110111011110100100100110000'
- '000001111010000010001110100100011001101011010111101001101110'
- '100011011111100001010010011100111001111011100000101101100111'
- '100011010010001100110111101110010101101110010000000011110101'
- '100101011000101011101111111000000100010100001001110111001101'
- '101110110001100100101110010000101100010011010100000111010111'
- '000010011110101110111010010011111011000011010111011101100111'
- '000111000100011010101110011101100010111001110011111110001100'
- '101001010011011011101011110011000010010101110101011001011110'
- '001101000011110100010110100010110110010100100101101100001011'
- '100110010100000001101111110001101010000111011000101010111010'
- '001000101010010101101001001110010110111001010101001110000110'
- '011100011101000111111101100011011001000111010001110111000010'
experiment: batch_run/rand_str_60_28_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
