ancilla_dim: 32
bitstrings:
- '011111001001000011100010010111000111100100111110010000111000'
- '010110111001100001110101110100100001100111111011000100110101'
- '010111000011111001001011100110110101111101111001111011110001'
- '111001011000111010110011101001001000100111111010010001111101'
- '100010110000011110111101110000000000100000111001100111001011'
- '001011110101011101011011110000100100011001001000111000101011'
- '111110110001100101110010000010010000110101110110000011001111'
- '011010000010101100000110000110010000011001100111001001100000'
- '101000111110100100110010111110011100011110100111011101001110'
- '001000011110111101110000111101011111101110011110101100011000'
- '100000010010101001000110100001101100111001010000010101001110'
- '011000010011101010110001000100001001001000011001000111111101'
- '100110011000001001110000101001110100000110011011001010111000'
- '110011111101100010100010001011110011100010010101101100011001'
- '100100101100100101110001101001100000111001100000100000110000'
- '011011100110011011110010010111000011100111101001000001011101'
- '000111111011001101111111100101010101001111011011110000000101'
- '101011001001000001001011001111111100100000111100001001011000'
- '000010001010011100011010101100100010010000100100000110000101'
- '100110010100110010001100001011110001011010101000110010100011'
- '111010111011101111101111101000100101000110011001000101110000'
- '111001111101001101110010111110010000001001000010011111100011'
experiment: batch_run/rand_str_60_22_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
