ancilla_dim: 4
bitstrings:
- '01010011111101111111011110100111110000000111'
- '00111111010101001001000110001000100001100110'
- '10011001100110000100001011000110000001100101'
- '10010110100101011110100110101111011001000111'
experiment: batch_run/rand_str_44_4_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
