ancilla_dim: 32
bitstrings:
- '01100010011000100100010001100010001001101000'
- '11100101011111001100011001110101110000110011'
- '11111111000110010001000010110000110011101011'
- '00110100000110001100110110110011010001100000'
- '10111011101100101000011011101110100010000101'
- '00101101101011110100111100011010101100111000'
- '10001110001011000000010110000011111100000100'
- '11010001010011111100001111111011010100100010'
- '01001100111110000111000100101111111010111110'
- '11011110000001001111111100111101110110111000'
- '00101111101001110011001100111001100110011101'
- '00111110100110111100111000101001101000010011'
- '10100101001010011100000111010010100101100010'
- '00010101000101101100110010101101100111100001'
- '00001111100111010111110111110010010100100110'
- '11111010001011001111110111100100100011001110'
- '00001010111011110010111010011001000110010110'
- '01001000011100000011101010100101001101100010'
experiment: batch_run/rand_str_44_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
