ancilla_dim: 32
bitstrings:
- '11111101001111000100000101101000100011100010010101111000101001000111'
- '11000000100010011000111011111101001011001010010001010100011100100110'
- '01000011100100010111001100010110001011111011110001011101000010110011'
- '00111011001101100100000100100001100110011111010100110010100101011011'
- '01001100010011001001100000110000001000101111001100000100101001101111'
- '11010101110000010110001010111010110110011100011111100100101110010010'
- '11000010101000011000011100101011001101101000100110111000101111010101'
- '10100000100110001001011011001010110101101110100100000000110101000110'
- '00011110100000011011111111111011000111001010110110011100111001100101'
- '00110001100111110101010111000001110111110001000101100111101101010101'
- '00101010110001111000110011111011000100000100000100111001100000001011'
- '01001000001100100101110000100011101010011110110110110101100000111100'
- '00100011000000110100011010000001011111000100001000001010010100011110'
- '01111111110111001110010101100011011011000011100111011011111001010110'
- '01011110000110010011100011101000100111111111001100101111000100100001'
- '01011000111110110000000101101101111100011001011001000000000101011000'
- '11001001100110100100101011110110010001000010001011010110111110101110'
- '10100111101101011111010100010101110110111001100000101011001101111100'
experiment: batch_run/rand_str_68_18_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
