ancilla_dim: 16
bitstrings:
- '111001011111010101111000111100101110010101001010'
- '010011101100111011001100000111101011010000000010'
- '011111011101111011111101100001000010111000011110'
- '000111011000011101101101010100000001100101110110'
- '001000001010110101000011101111000010001110000101'
- '010011011111011101001111111100110100001011110111'
- '111001110100000001010111000110101000111100001001'
- '011000101100001010011101000111110100111100010100'
- '011100101111101110110100100101100110101100010111'
- '010100111100100000100110010110010110010101010011'
- '110100000111000000100011010011011101110101111010'
experiment: batch_run/rand_str_48_11_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
