ancilla_dim: 32
bitstrings:
- '10101010101111110100110101110110100011011101101110011011110000010100'
- '01000010111011100011101010001011010001110101110111110001111001100110'
- '00101111100000001010010001101101001110101001011101101110100011100100'
- '11000010000111011101111100001110101001100001101111010111010000001100'
- '10000100001000110010110001101000100101011010010001111000000000010110'
- '00100110110001110100010011101101001010010011100001100000111100101101'
- '11100111101010000010000010001010001010101000111110001110001011010001'
- '01011000000101111000011001010110110000011011111001110110010000100010'
- '00001011111110010000111010000100101010000111000100011101101101010100'
- '10101110101111000110010100001111110011000011001110110000100010001011'
- '01110001010001011000111011100000010101011001000001111010000000010100'
- '00001100011100001010011100111111110101100110111101011010100100100101'
- '11011101110100010100111000110100110011100000110001110001000100010001'
- '11100011111100010100101000011100000010111010010010010010110001011011'
- '10010100000111010010011100011000100011010100111000110100001010110100'
- '11000111100100011111111110111111011101101011001011000010000110001011'
- '01111001011111010010110000010110110111000110100001100011011000100111'
- '10011100111110110111010011011100100010011000100001001110101100101001'
- '10010010100000001101110100011000101010000011000111011100100000011100'
- '10010101111101001011010101101110110110100111101000000110001100100100'
- '01100010001111100010111111000000111111001011110101101110011001000011'
- '01100000011010011111011000110110111011100010011101001111111000010100'
- '01100101011100100001000110001001111001100000111111000001110011010100'
- '10010000101101010100110001101101001100110011010110101001101111111010'
- '01010101100111000101100110101011100010011000101101010000101111001110'
- '10010111001110100111011010101000000000001011111101001110010100110010'
- '11000110100000001000111010100100010110110011011100000010000111110010'
- '00010010010010100100101100101001110000101010111111111001100110110101'
- '10100110100010010010000010110010011111110011100111011110100110001001'
experiment: batch_run/rand_str_68_29_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
