ancilla_dim: 16
bitstrings:
- '010110001110011110111111100101000111101001001011011010011101'
- '001100101111000010110111001001001011111101110100110110111010'
- '011111100010010011001001010111100001000111011000110011000001'
- '011000000001100101100100011111110100100000000000110000111000'
- '010001010001110000101111101100110100011110011111110100010010'
- '101111101010110111110011111110010101100010001110111010111011'
- '100111010011111101101110011011100100000000011101111010010001'
- '010110100111111001011111101111010110111101110001110001001011'
- '100001001010111110000101011101101100111100000010001111101100'
- '011100101011000100110011111001111101001111000010110001101100'
experiment: batch_run/rand_str_60_10_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
