ancilla_dim: 1
bitstrings:
- '0001111100'
experiment: batch_run/rand_str_10_1_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
