ancilla_dim: 16
bitstrings:
- '000110110011111100011101110111100011000111101010'
- '011110010101001110001101100011001001110001101010'
- '011001100110111100001101000111111100010100101100'
- '101011111101101011001110000010101110000010111011'
- '011000000010011101000111000010111111001011001110'
- '011011000000111001011101001111000100001110011111'
- '000000011010011110101111001000110000100100000101'
- '010101101111011011100111110001010001001101000101'
- '100111001101110011000111011101000110010100001010'
- '001010111100111011111110110111111111101100110010'
- '000001010111011001000100110101111111011110001100'
- '100110011001111111110100011011010001000000000100'
- '000001100110100100101111111101011111101110100101'
experiment: batch_run/rand_str_48_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
