ancilla_dim: 32
bitstrings:
- '0000110000101000100101101010011001011101'
- '0100010111101010001101011101001000111000'
- '1010111111100101111010101101000101000100'
- '0001100111111101011001110000010011101110'
- '0000110010100010010001000000101000011110'
- '1010000111010010110001001101001001110101'
- '1000101001101100110110110010101111010011'
- '0111110000100000001110101001111101001011'
- '0101111010100110101100100111111001101110'
- '1001010010101000111011000000101011100011'
- '1110001000011000110110100001101110011101'
- '1101000000011101101100011010001011010010'
- '1000001101001101100110001100110111000010'
- '0010110101110000011110100110111000110100'
- '0010101011100001000001010001111101111010'
- '1010100011011011101011111010011100101010'
- '0111001101110010011111101001111111001001'
- '0111001001011100111001111001010000101100'
- '1111001000001111100101010111111001111110'
experiment: batch_run/rand_str_40_19_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 40
