ancilla_dim: 32
bitstrings:
- '0100110100111010101001101010110000000001101110010101'
- '0001010011001111101000101111110101010111110110001111'
- '1001100010100001100001000010110101010100000011101010'
- '0000111111000110010010101000001111110001110000110000'
- '0011011000100111111110011101101011010011000000111001'
- '1001000110010011111011001011000001110000111110000001'
- '0011010011010011000101111001000011110001111000010110'
- '0100000000101110100110011001111111000100110000000001'
- '1001100011001111111101001011110100010110111000110111'
- '0001010101111000010110010001101001010010111011100110'
- '1101110110110000111010100011010110101000100010001010'
- '1100111000000110111000101000101011100000010001101001'
- '1100110001001010101001110010101011111111011010110111'
- '0100011111111001110010101100111011001010000101101110'
- '0110100111011101110011000000001001000101111010001111'
- '0101010001100011011111001100011100001000001101000111'
- '1001010011111000011101110101110011111001010111001011'
- '0011011100100101100111101000010111011010011111011011'
- '0010111010111001100000001001101000100110000011010110'
- '1100001110101101110111000101101101001000011000001111'
- '1100100001000101110101000110101000110110010111110100'
- '1100001011111101110010001010110000000011101011010111'
- '0110110001010101101100010010111000111100101011101100'
- '0111110001010101100111000111100010000011010010110101'
- '1101010010101000001101110001001011011000100111100110'
- '0110110101110100000100100111100100001010101101000000'
experiment: batch_run/rand_str_52_26_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 52
