ancilla_dim: 8
bitstrings:
- '01101111010100000101001010100111001100110111'
- '01101001011101001101101101110011101000100110'
- '00001111110011000011111101110010100001110000'
- '01101111011111010010100110110101110001011101'
- '11000000100000011101101101011010011001010010'
- '10101100011011111100011110110101100110000110'
experiment: batch_run/rand_str_44_6_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
