ancilla_dim: 4
bitstrings:
- '0101000111'
- '0010110010'
- '0101011101'
experiment: batch_run/rand_str_10_3_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
