ancilla_dim: 32
bitstrings:
- '00000001'
- '11101000'
- '10010111'
- '11100001'
- '01001101'
- '11110110'
- '00100001'
- '00010100'
- '10111111'
- '11010011'
- '11101001'
- '11001100'
- '00001111'
- '10011111'
- '01000101'
- '01110111'
- '10001110'
- '11000111'
- '10110110'
- '11110101'
- '01000000'
- '10000101'
- '11000000'
- '00100011'
- '11110001'
- '11100111'
- '01011001'
- '10100011'
- '11010000'
- '11011101'
experiment: batch_run/rand_str_8_30_comp
input_type: bitstring_list
methods:
- ours_no_ancilla
- qualtran
- qiskit
- gleinig_sparse
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 8
