ancilla_dim: 16
bitstrings:
- '01011100001100101000111110011101'
- '00111000100000000001111110101000'
- '00001001001001000111001101000110'
- '10001001100000011101011110001110'
- '00111100100010110001101110111010'
- '01010000101001011010001110101110'
- '00101101110110010010000000101011'
- '01001100100110011011000110010000'
- '01010110001000100011011001111111'
- '00010000011100111011001001001010'
- '10001101101011001011100111011000'
experiment: batch_run/rand_str_32_11_not_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
- qiskit
- qualtran
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 32
