ancilla_dim: 16
bitstrings:
- '111011001000111000100100001010111111110000100000'
- '011111000101100110101110001110011000101100010001'
- '100010101000001010111000010100011111001010100100'
- '010011000010101101100011001111111110011010101110'
- '111000100110100111000111100101100100010110001011'
- '001000010100100101001110101001100101001010110111'
- '110000100000010101001100111010101100000001001101'
- '000001110001110011101000010001000011011001100000'
- '101011110100001100101000001001110100011000010101'
- '000011110010000001011101100011101000111100011101'
- '001000001011011011010000101011111111011010100001'
- '101100110010001110011000111000101101110101001100'
- '011001001011111011110110000000101111000100011110'
- '000001110000001111011001000101110110000000001011'
- '010111101011000100111111111100100110011100010000'
- '100000001101000010010011000001000000000111110110'
experiment: batch_run/rand_str_48_16_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 48
