ancilla_dim: 32
bitstrings:
- '001100101110110000111000100110001101111010000100010000000011'
- '100110111110001110111000110000101001110001100111110000100001'
- '111110010011100110011011001001100101000110111100110110001101'
- '111101010111000101000110100111100101110111001110001011110010'
- '100101101001000100111111000101110111000010000000100011101101'
- '110010011101001000101100010011011100100011001001000001011001'
- '011011101110001011110101011100010010111111111001110001100100'
- '010000000101010111010011000111010011001000001100000001110100'
- '100101011110000100000111111011110100111110100110110100010111'
- '100100000111001101001111010110001111010010011111001011011101'
- '000110000010001101010100100110111111010000010011101011100100'
- '000010010100001100110110010011000110110101101000010010111101'
- '100100101111000110010101001001101010100001001111000010010110'
- '000111010111101001000110110110111110010001000000010111101011'
- '010100010100101001000110010111111110111000000000101011011100'
- '110101111000011011001011001100100100001110011010110001010111'
- '100101110000100111101011011100110111110110100000110100000011'
experiment: batch_run/rand_str_60_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 60
