ancilla_dim: 32
bitstrings:
- '00011111110111101110101101110110010111010000101000010100'
- '01110111001100010110110100001001100101010101011010001100'
- '10010110101001111001010000011000101110011100110001010100'
- '10100100001100010110111001000100111101110011100100111001'
- '01010101100110101011101111011101101100010111100001001001'
- '00010100010001001010111101011111011011010010111010011100'
- '11000101011001100011100101111001101011011111100000011110'
- '01100011011000000111110000110000100100111101010110110111'
- '10000011011011110110100010000110100010110010000100001110'
- '11000101111001000011100000100100000101010100110101010100'
- '10001110010011100110110011000100000101011010011001100001'
- '11010101000010011111000101001000110101010000111111101010'
- '00000011001100001101010001101100001101011011010100100110'
- '10011010000111010111110010011010110001001010000011111100'
- '11001100001000111100010101000000011100000101001111110000'
- '11010000110110101101110111101001000100110111111001111111'
- '11000101100101011110100000011000101111000001101111001011'
- '01100101000001100001100101000001100010111001001110101011'
- '01000011000001000101110011011100110001001100101100100110'
- '10110011111101001010101001011101100000010110101000100110'
- '00000110001110110001001000111011001010000001010001101000'
- '11000111001100111100111011011000010110010010110101111001'
- '11101101110100101001101110011001101101101110011101001010'
- '00101110010111001111101110010010000110111010000110100111'
- '00000011000111001001110011010010010111110000111101100001'
- '00000001011001101010111010010010011101101000100110000110'
- '10111110010001011100001111001110101110111101001010000011'
- '00101110001001100011101000000011001011011010010110110100'
experiment: batch_run/rand_str_56_28_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 56
