ancilla_dim: 16
bitstrings:
- '100011001000001011000110011001001111'
- '011110101001100110011100110111010101'
- '000111011011101011110110101111000000'
- '001100110000110001001101000110001110'
- '011100000000101101001101001010011110'
- '011111111010110101011101100001010000'
- '010101011101111100111101110110101101'
- '001111000010011001101010101000010011'
- '111110011001111111110100101110011001'
- '100111111001110010000101111100000111'
- '011001000000001011110010001110010001'
- '110101001111001111001010000011100110'
- '001011000011000100110101010111100101'
experiment: batch_run/rand_str_36_13_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 36
