ancilla_dim: 16
bitstrings:
- '0001000100'
- '0011111001'
- '0001110111'
- '1101100011'
- '1011111000'
- '1011101000'
- '1110111000'
- '0000001101'
- '0101111110'
- '0111110010'
- '0000010010'
- '1010111100'
experiment: batch_run/rand_str_10_12_end
input_type: bitstring_list
methods:
- ours_no_ancilla
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 10
