ancilla_dim: 8
bitstrings:
- '1101110000000010000001011111010011001101000110011111110000010111'
- '0010011110111101111100110110010000001110011111011010010111011100'
- '0000000011001111101100000000111111100011011011110101001111100101'
- '0111001011110111111111000001011011001110100110101100011111000100'
- '1000110001000111101110110010100011011000001110011110101101111010'
- '0100011000000000100110000010111010110000100101100101111100011100'
- '0010110111100011011111100110011100001000000101011001000101111101'
experiment: batch_run/rand_str_64_7_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
