ancilla_dim: 32
bitstrings:
- '1010101010111101101101001000101101011100000110001111001000110000'
- '1000001110111110100000001101111011111100001001101000000101101100'
- '1011100011000101011011010110101101011011011101111000011010000010'
- '0010000111101101011011000100111010001011111010111101100011011110'
- '1110111010111000101011011111011000110111100101111001111101000100'
- '1110111011000011011010011000011001110000100000101101011100010000'
- '1111101101110111110011010111001101101000100111010110101101111100'
- '1001010011111111110000110000100001011110101010001100100101001111'
- '1101011111011000101011011011100010010010111001000101010110101010'
- '0010100100010001000111011010101001001001101110110100001111110001'
- '0100111011001110010100011101101000011111010010111110111010101111'
- '1000011111011001101111110000010000010011111000001010100000011110'
- '0010011001011010100000000101110100110001111011100111010100001010'
- '1010101001100011011001010110010001000101011011010111110000011101'
- '0110111001100001110011000001000100000000100010001001111101000011'
- '1010000111110100000111010110101101011000000111111111010000000111'
- '1000001011001110101001101100001100011011001110100010011010001010'
- '1001101011000100110000010100101111101110001000011010110000111011'
- '1011010110000100010001011000110110100110111001001011101010011000'
- '1110000000001111001011101000001100100001100010010011010010110101'
- '1011100110010101101110000010000100111100001101000011101001000110'
- '1010000110011010001001000011001000001011001110111110010010101001'
- '0010000011001010101000100001001101101010011110101110100111000101'
- '0111000011000100011000100001110010011010001000101101110000110001'
- '1010101011001110101011011010101001101011011000111001010110000000'
experiment: batch_run/rand_str_64_25_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
