ancilla_dim: 32
bitstrings:
- '10101001001010001010001100110000000010011000101000000111101111100011'
- '00101111001001010110000000100100001000000100111010100000110100101111'
- '11110111011000110011001000001011011010001111111101101100100101011100'
- '11011110011110110010110101101011001110111111101111001100001101001010'
- '00001110011111111111000001111011010010100101101110101011100001011101'
- '11110011110010011001100101110000100000001111011000010111011010111100'
- '01000100011101111000101010100011001101100100101101100010100101101100'
- '11001011011011101001110001111010000100011011101100101010011110111010'
- '11101111101101100110001001111100100000111100011010110110011100010001'
- '10100111101111000101100100001101101100110111100110101111110101011100'
- '11111100001100000101100100001100000011111010011101100011010010001010'
- '11100100000101001010111111010011010000110110000101110000110100011101'
- '01110010011011100010100100011111001000100100011000011000011001011011'
- '01011001101101110100001011111110000111000111110110001010000011100110'
- '01011111100010010011101000000001110000001010111110000001111000100101'
- '10011000000000001110101011000110001001100001100001101101011100111101'
- '10111001101000101100011001000000011111001001000100111110100111011110'
experiment: batch_run/rand_str_68_17_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 68
