ancilla_dim: 8
bitstrings:
- '01000101011111110100100110110010111110001110'
- '01111100000001111111011100111001000011101001'
- '01001000000011101100110101111111101000100010'
- '11110010000011011000110001110100110001001100'
- '01100001001010101011111101010000011011000100'
- '10100000111001000010111100000001110010110110'
- '11011000111101111010100111010000001000000101'
- '01100010101110001000110001011101100010000111'
experiment: batch_run/rand_str_44_8_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 44
