ancilla_dim: 16
bitstrings:
- '1001010100011100101000110011110011010100100111001010110110001100'
- '0100100110110001101001101000001011001111000010011010011000011100'
- '0101000100001010001110111010010010100010010001001000100110110111'
- '0111110111111111101101001011111101010011100010001100100110001011'
- '1010000110001000011100100101011011101101110101100010011101010011'
- '1011000111011100110011100111100111011101000100111000011010111101'
- '1001100011001100011101010100001001110000110101100100000010110001'
- '0100001011000011000101111100000000100100100111101001110011100011'
- '0010110100100110011101011010001101101001011001001111101010110100'
- '0110110110110101011110011111101111101000100000111001000000011100'
- '1111010010100110011000001110011001010010001001001110001001111011'
- '1111000010000000110010111001100000111110010011011011100110001011'
- '0001110000111100000101110010001101001100111101011101100100001001'
- '1000111110001010100000111101010001110010001101010110001001110111'
experiment: batch_run/rand_str_64_14_only_ours
input_type: bitstring_list
methods:
- ours_efficient
- ours
plot_output: figs/rand_str_batch_run.pdf
plotting: false
system_sizes:
- 64
